/* MBManagerDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol MBManagerDelegate
@optional
-(void)managerDidLoseConnectionToService:(id)manager;
-(void)manager:(id)manager didFailRestoreWithError:(id)error;
-(void)manager:(id)manager didFailScanWithError:(id)error;
-(void)manager:(id)manager didFailBackupWithError:(id)error;
-(void)managerDidCancelRestore:(id)manager;
-(void)managerDidFinishRestore:(id)manager;
-(void)managerDidFinishScan:(id)manager;
-(void)managerDidFinishBackup:(id)manager;
-(void)manager:(id)manager didUpdateProgress:(float)progress estimatedTimeRemaining:(unsigned)remaining;
-(void)manager:(id)manager didSetBackupEnabled:(BOOL)enabled;
@end
