/* QuotaInfoResponse.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface QuotaInfoResponse : XXUnknownSuperclass {
	BOOL _basicAccount;
	NSDictionary* _quotaInfo;
	NSDictionary* _storageInfo;
	NSDictionary* _accountStatus;
	NSDictionary* _urls;
	NSArray* _topToolbarItems;
	NSArray* _otherToolbarItems;
}
@property(readonly, assign, nonatomic) NSDictionary* accountStatus;
@property(readonly, assign, nonatomic) NSString* availableStorageText;
@property(readonly, assign, nonatomic) NSString* totalStorageText;
@property(readonly, assign, nonatomic) NSString* appDetailsURLString;
@property(readonly, assign, nonatomic) NSString* manageStorageURLString;
-(BOOL)hasPurchasedMoreStorage;
-(id)storageFooter:(BOOL)footer;
-(void)dealloc;
-(id)initWithHTTPResponse:(id)httpresponse data:(id)data;
@end
