/* UsageTotalUsedHeader.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "PSHeaderFooterView.h"
#import "UsageSettings-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface UsageTotalUsedHeader : XXUnknownSuperclass <PSHeaderFooterView> {
	UILabel* _usedLabel;
	UILabel* _availableLabel;
	UILabel* _titleLabel;
	float _height;
}
-(float)preferredHeightForWidth:(float)width;
-(void)layoutSubviews;
-(void)dealloc;
-(void)setUsed:(id)used;
-(void)setAvailable:(id)available;
-(void)setName:(id)name;
-(void)recalcHeight;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithSpecifier:(id)specifier;
@end
