/* UsageStorageMonitor.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, UsageTotalUsedHeader, NSMutableDictionary, UILabel, UIBarButtonItem, NSMutableArray, NSArray;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface UsageStorageMonitor : XXUnknownSuperclass {
	float _availableSize;
	float _usedSize;
	float _totalSize;
	UIBarButtonItem* _footerItem;
	UILabel* _footerLabel;
	NSArray* _footerItems;
	UsageTotalUsedHeader* _totalUsedHeader;
	NSMutableDictionary* _mediaCache;
	NSMutableArray* _appsCache;
	NSArray* _usageBundlesCache;
	NSObject<OS_dispatch_queue>* _cache_operation_queue;
	int _storageClientCount;
}
@property(readonly, assign) NSMutableDictionary* mediaCache;
@property(readonly, assign, nonatomic) UsageTotalUsedHeader* totalUsedHeader;
@property(readonly, assign, nonatomic) NSArray* footerItems;
+(id)sharedMonitor;
-(void)dealloc;
-(id)init;
-(void)flushViews;
-(void)_setTotal:(float)total;
-(void)_setUsed:(float)used;
-(void)_setAvailable:(float)available;
-(void)fetchSystemSizeStrings;
-(void)populateUsageAppsCache;
-(float)specialStorageUsageForBundleID:(id)bundleID;
-(id)checkAndFixUpVersion:(id)version;
-(void)populateMediaCache;
-(float)sizeForMediaQuery:(id)mediaQuery withGroupingType:(int)groupingType storingInCache:(id)cache withKey:(id)key;
-(void)populateUsageBundlesCache;
-(void)deregisterUsageStorageClient;
-(void)registerUsageStorageClient;
-(void)clearUsageDataCache;
-(void)populateUsageDataWithCompletion:(id)completion;
@end
