/* CompassAppDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Compass-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIApplicationDelegate.h"
#import "UIApplicationDelegatePrivate.h"

@class UIWindow, CompassController;

__attribute__((visibility("hidden")))
@interface CompassAppDelegate : XXUnknownSuperclass <UIApplicationDelegate, UIApplicationDelegatePrivate> {
	CompassController* _compassController;
	UIWindow* _window;
}
@property(retain, nonatomic) UIWindow* window;
-(void)dealloc;
-(void)applicationWillTerminate:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationWillEnterForeground:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillResignActive:(id)application;
-(void)_application:(id)application statusBarTouchesEnded:(id)ended;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
@end
