/* ActionPanelActivityItemsSource.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIActivityItemsSource.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSURL, BrowserPrintPageRenderer, UIPrintInfo;

__attribute__((visibility("hidden")))
@interface ActionPanelActivityItemsSource : XXUnknownSuperclass <UIActivityItemsSource> {
	BrowserPrintPageRenderer* _printRenderer;
	UIPrintInfo* _printInfo;
	NSData* _imageOnlyDocumentData;
	NSURL* _urlToShare;
}
-(id)activityViewController:(id)controller thumbnailImageForActivityType:(id)activityType;
-(id)activityViewController:(id)controller subjectForActivityType:(id)activityType;
-(id)activityViewController:(id)controller itemsForActivityType:(id)activityType;
-(id)activityViewControllerPlaceholderItems:(id)items;
-(id)_activityItemsIncludingURLAsString:(BOOL)string;
-(id)_customActivities;
-(void)dealloc;
@end
