/* BackForwardNavigationController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BackForwardTableViewControllerDelegate.h"
#import "BrowserPanel.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, BackForwardTableViewController;

__attribute__((visibility("hidden")))
@interface BackForwardNavigationController : XXUnknownSuperclass <BrowserPanel, BackForwardTableViewControllerDelegate> {
	BackForwardTableViewController* _tableViewController;
	int _savedStatusBarStyle;
}
@property(assign, nonatomic) BOOL reversesListOrder;
@property(copy, nonatomic) NSArray* backForwardList;
-(BOOL)shouldShowButtonBar;
-(id)toolbarItems;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelType;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)rotatingFooterView;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)backForwardTableViewController:(id)controller didSelectWebHistoryItem:(id)item;
-(void)done;
-(void)dealloc;
-(id)init;
@end
