/* ContinuousReadingPreviewView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UILabel, ContinuousReadingBannerView, ContinuousReadingItem;

__attribute__((visibility("hidden")))
@interface ContinuousReadingPreviewView : XXUnknownSuperclass {
	ContinuousReadingItem* _continuousReadingItem;
	UIView* _contentView;
	ContinuousReadingBannerView* _bannerView;
	UIView* _headerView;
	UILabel* _headerLabel;
}
@property(retain, nonatomic) UILabel* headerLabel;
@property(retain, nonatomic) UIView* headerView;
@property(retain, nonatomic) ContinuousReadingBannerView* bannerView;
@property(readonly, assign, nonatomic) float headerHeight;
@property(readonly, assign, nonatomic) float rubberBandingHeight;
@property(retain, nonatomic) UIView* contentView;
@property(readonly, assign, nonatomic) ContinuousReadingItem* continuousReadingItem;
-(void)_layOutContentView;
-(void)_layOutHeader;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithContinuousReadingItem:(id)continuousReadingItem;
-(id)initWithFrame:(CGRect)frame;
@end
