/* FadeView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobileSafari-Structs.h"


__attribute__((visibility("hidden")))
@interface FadeView : XXUnknownSuperclass {
	id _target;
	SEL _action;
}
@property(assign, nonatomic) SEL action;
@property(assign, nonatomic) id target;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame;
@end
