/* FindOnPageToolbar.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UISearchBarDelegate.h"

@class UILabel, UIActivityIndicatorView, NSTimer, UIToolbar, NSArray, UISearchBar, UIBarButtonItem, UISegmentedControl;
@protocol FindOnPageToolbarDelegate;

__attribute__((visibility("hidden")))
@interface FindOnPageToolbar : XXUnknownSuperclass <UISearchBarDelegate> {
	UIToolbar* _leftToolbar;
	UIToolbar* _rightToolbar;
	UISegmentedControl* _previousNextControl;
	UIBarButtonItem* _previousNextControlBarButtonItem;
	UILabel* _currentMatchLabel;
	UIBarButtonItem* _currentMatchBarButtonItem;
	UISearchBar* _inputBar;
	UIBarButtonItem* _inputFieldBarButtonItem;
	UIBarButtonItem* _doneBarButtonItem;
	id<FindOnPageToolbarDelegate> _findDelegate;
	NSTimer* _textChangedUpdateTimer;
	UIBarButtonItem* _fixedSpaceItem;
	UIActivityIndicatorView* _indicatorView;
	NSArray* _keyCommands;
	BOOL _ownedByAddressView;
	BOOL _useActivityView;
}
@property(assign, nonatomic) BOOL useActivityView;
@property(assign, nonatomic) BOOL ownedByAddressView;
+(id)toolbarWithItems:(id)items;
+(id)sharedToolbar;
-(void)_showPreviousResult;
-(void)_showNextResult;
-(id)keyCommands;
-(void)dealloc;
-(id)inputField;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(void)_transitionToFindOnPageMode;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)_doUpdateSearchText;
-(void)_done;
-(void)_previousNextSegmentedControlValueChanged:(id)changed;
-(void)didEndSplitTransition;
-(void)updateUI;
@end
