/* HighlightRecognizer.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HighlightRecognizer : XXUnknownSuperclass {
	unsigned _numberOfTouches;
	id _highlightTarget;
	SEL _highlightAction;
}
@property(assign, nonatomic) SEL highlightAction;
@property(assign, nonatomic) id highlightTarget;
-(void)reset;
-(unsigned)numberOfTouches;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(id)initWithTarget:(id)target action:(SEL)action;
@end
