/* HorizontalPanGestureRecognizer.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HorizontalPanGestureRecognizer : XXUnknownSuperclass {
	unsigned _direction;
}
@property(assign, nonatomic) unsigned direction;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(id)initWithTarget:(id)target action:(SEL)action;
@end
