/* PurplePageLoadTestRunner.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "PageLoadTestRunner.h"

@class NSString, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PurplePageLoadTestRunner : PageLoadTestRunner {
	NSMutableDictionary* _pptResults;
	NSString* _testName;
	BOOL _showLoadTime;
	BOOL _showFirstVisualLayoutTime;
	BOOL _showRenderTime;
	BOOL _showRenderFps;
}
@property(assign, nonatomic) BOOL showRenderFps;
@property(assign, nonatomic) BOOL showRenderTime;
@property(assign, nonatomic) BOOL showFirstVisualLayoutTime;
@property(assign, nonatomic) BOOL showLoadTime;
@property(copy, nonatomic) NSString* testName;
-(void)collectPPTResults;
-(void)pptResultFor:(id)aFor measure:(id)measure time:(double)time;
-(void)pptResultFor:(id)aFor measure:(id)measure value:(double)value units:(id)units;
-(void)finishedTestRunner;
-(void)startingTestRunner;
-(void)dealloc;
-(id)initRenderTestWithName:(id)name showRenderTime:(BOOL)time showFPS:(BOOL)fps;
-(id)initWithTestName:(id)testName;
@end
