/* ReadingListTableViewCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface ReadingListTableViewCell : XXUnknownSuperclass {
	unsigned _bookmarkID;
	NSString* _siteName;
	NSString* _previewText;
	UILabel* _siteNameTextLabel;
	NSString* _fetchingStatusText;
}
@property(copy, nonatomic) NSString* fetchingStatusText;
@property(retain, nonatomic) UILabel* siteNameTextLabel;
@property(copy, nonatomic) NSString* previewText;
@property(copy, nonatomic) NSString* siteName;
@property(readonly, assign, nonatomic) unsigned bookmarkID;
-(void)_setFetchingStatusTextForBookmark:(id)bookmark;
-(void)setBookmark:(id)bookmark isArchiving:(BOOL)archiving;
-(void)setBookmark:(id)bookmark;
-(void)dealloc;
@end
