/* ReadingListProgressView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface ReadingListProgressView : XXUnknownSuperclass {
	double _progress;
	BOOL _usesSmallVersion;
	UIImageView* _glasses;
	UIImageView* _track;
	UIImageView* _fill;
}
@property(assign, nonatomic) BOOL usesSmallVersion;
@property(assign, nonatomic) double progress;
-(CGPoint)pressFeedbackPosition;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(void)setToolbarTintColor:(id)color;
-(id)initWithFrame:(CGRect)frame usesSmallVersion:(BOOL)version;
@end
