/* ReadingListViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "CatalogCategoryViewController.h"
#import "WebBookmarksClientDelegateProtocol.h"
#import "MobileSafari-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "BookmarksPanelStateRestoring.h"
#import "BookmarksToolbarItemProvider.h"

@class WebBookmarkList, EmptyCollectionExplanationView, NSTimer, WebBookmarksServerProxy, UITableView, WebBookmarkCollection, NSString, UIButton, UIBarButtonItem;
@protocol ReadingListViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface ReadingListViewController : XXUnknownSuperclass <BookmarksPanelStateRestoring, BookmarksToolbarItemProvider, CatalogCategoryViewController, UITableViewDelegate, UITableViewDataSource, WebBookmarksClientDelegateProtocol> {
	UITableView* _tableView;
	UIBarButtonItem* _unreadFilterButton;
	WebBookmarkCollection* _collection;
	BOOL _networkIsReachable;
	WebBookmarkList* _readingList;
	WebBookmarksServerProxy* _webBookmarksServerProxy;
	NSString* _archivingBookmarkUUID;
	EmptyCollectionExplanationView* _explanationView;
	NSTimer* _deletionNotificationTimer;
	BOOL _showingAllBookmarks;
	id<ReadingListViewControllerDelegate> _delegate;
}
@property(readonly, assign, nonatomic) UIButton* navigationBarButton;
@property(readonly, assign, nonatomic) NSString* collectionType;
@property(assign, nonatomic) id<ReadingListViewControllerDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL showingAllBookmarks;
-(id)safari_tableViewScrollPositionSaveIdentifier;
-(id)safari_tableViewForScrollPositionSaving;
-(void)bookmarksServerProxy:(id)proxy didStopFetchingReadingListItem:(id)item;
-(void)bookmarksServerProxy:(id)proxy didStartFetchingReadingListItem:(id)item;
-(void)bookmarksServerProxyConnectionInvalidated:(id)invalidated;
-(void)bookmarksServerProxyDidFinishFetching:(id)bookmarksServerProxy;
-(void)restoreScrollPosition:(float)position;
-(float)currentScrollPosition;
-(BOOL)restoreStateWithDictionary:(id)dictionary;
-(id)currentStateDictionary;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)_disconnectWebBookmarksServerProxy;
-(void)_connectWebBookmarksServerProxy;
-(void)_postChangeNotification;
-(void)_scheduleDelayedChangeNotification;
-(CGSize)contentSizeForViewInPopoverView;
-(void)_updatePopoverSize;
-(void)didMarkBookmarkUnreadAtIndex:(unsigned)index;
-(void)didAddNewReadingListBookmark;
-(void)_addReadingListItem;
-(id)bookmarksRightBarButtonItem;
-(id)_unreadFilterButtonTitle;
-(void)_didChangeUnreadFilter;
-(void)_reloadReadingListAndTable;
-(void)_reloadReadingList;
-(void)_networkReachabilityChanged:(id)changed;
-(id)_bookmarkAtIndexPath:(id)indexPath;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)updateAddBookmarkButtonEnabledWithTabDocument:(id)tabDocument;
-(void)setAddBookmarkButtonEnabled:(BOOL)enabled;
-(void)loadView;
-(void)_clearExplanationView;
-(void)_showExplanationView;
-(id)bookmarksNavigationController;
-(void)dealloc;
-(id)init;
@end
