/* SecurityInfo.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL;

__attribute__((visibility("hidden")))
@interface SecurityInfo : XXUnknownSuperclass {
	NSURL* url;
	int urlSecurityAssessment;
	int urlSecurityProvider;
	BOOL hasWarnedUser;
}
-(void)setURLSecurityProvider:(int)provider;
-(int)urlSecurityProvider;
-(void)setHasWarnedUser:(BOOL)user;
-(BOOL)hasWarnedUser;
-(BOOL)isKnownToBeUnsafe;
-(void)setURLSecurityAssessment:(int)assessment;
-(int)urlSecurityAssessment;
-(void)setAssessedURL:(id)url;
-(id)assessedURL;
-(id)description;
-(void)dealloc;
@end
