/* TabDocumentDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol TabDocumentDelegate
-(void)setStoreBannerPinnedToTop:(BOOL)top forTabDocument:(id)tabDocument;
-(void)removeStoreBannerFromTabDocument:(id)tabDocument animated:(BOOL)animated;
-(void)setShowingStoreBanner:(id)banner isShowing:(BOOL)showing;
-(void)composeEmailWithMailToURL:(id)url forTabDocument:(id)tabDocument;
-(void)hideAlertForTabDocument:(id)tabDocument;
-(void)showAlertForTabDocument:(id)tabDocument;
-(void)tabDocumentWillStartLoadFromUserClick:(id)tabDocument;
-(void)tabDocument:(id)document didDetectReaderAvailability:(BOOL)availability;
-(BOOL)tabDocument:(id)document handleCertificateError:(id)error forDataSource:(id)dataSource;
-(void)tabDocument:(id)document didCancelAuthenticationChallenge:(id)challenge;
-(void)tabDocument:(id)document didReceiveAuthenticationChallenge:(id)challenge fromDataSource:(id)dataSource;
-(void)tabDocumentStoppedLoadingResource:(id)resource;
-(void)tabDocumentStartedLoadingResource:(id)resource;
-(void)tabDocument:(id)document progressChanged:(float)changed;
-(void)tabDocumentDidChangeLocationWithinPageForMainFrame:(id)tabDocument;
-(void)tabDocumentDidUpdateBackForward:(id)tabDocument;
-(void)tabDocumentDidUpdateURL:(id)tabDocument;
-(void)tabDocumentDidUpdateTitle:(id)tabDocument;
-(void)tabDocumentProgressDidStall:(id)tabDocumentProgress;
-(void)tabDocument:(id)document didFinishLoadingWithError:(BOOL)error;
-(void)tabDocumentDidStartLoading:(id)tabDocument;
@end
