/* PHAudioPlayerDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol PHAudioPlayerDelegate
-(void)stoppedPlayingWithDataSource:(id)dataSource withError:(id)error;
-(void)updateWithElapsedTime:(double)elapsedTime playableTime:(double)time totalTime:(double)time3 isPlaying:(BOOL)playing isPlayable:(BOOL)playable dataSource:(id)source;
-(void)startedPlayingWithDataSource:(id)dataSource;
@end
