/* PHAudioPlayerDataSource.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;

@protocol PHAudioPlayerDataSource <NSObject>
@optional
@property(readonly, assign) unsigned long long expectedTotalBytes;
@property(readonly, assign) unsigned long long availableBytes;
@property(readonly, assign) double duration;
@required
@property(readonly, assign) BOOL fullFileAvailable;
@property(readonly, assign) NSString* audioFilePath;
@end
