/* PHFavoritesCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHFavoritesEntry, NSLayoutConstraint, PHFavoritesContactPhotoView, UILabel, NSArray, UIImageView;

__attribute__((visibility("hidden")))
@interface PHFavoritesCell : XXUnknownSuperclass {
	UILabel* _titleTextLabel;
	UILabel* _labelTextLabel;
	UIImageView* _iconGlyphView;
	PHFavoritesContactPhotoView* _contactPhotoView;
	long _buildConstraintsOnceToken;
	NSLayoutConstraint* _contactPhotoLeftInsetConstraint;
	NSArray* _mutableConstraints;
	NSLayoutConstraint* _rightViewRightInsetConstraint;
	NSLayoutConstraint* _titleLeftInsetConstraint;
	PHFavoritesEntry* _favoritesEntry;
}
@property(readonly, assign) BOOL shouldShowContactPhotos;
@property(readonly, assign) BOOL shouldShowIconGlyph;
@property(readonly, assign) BOOL shouldShowTextLabel;
@property(assign, nonatomic) PHFavoritesEntry* favoritesEntry;
+(float)height;
+(id)faceTimeAudioGlyphPress;
+(id)faceTimeAudioGlyph;
+(float)editingMarginWidth;
+(float)marginWidth;
+(BOOL)shouldShowContactPhotos;
-(void)_updateFonts;
-(void)customAccessoryButtonTapped:(id)tapped withEvent:(id)event;
-(BOOL)_drawsTopSeparatorDuringReordering;
-(void)_setReordering:(BOOL)reordering;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)_populateSubviewsFromFavoritesItem;
-(void)_rebuildMutableConstraints;
-(void)_handleContentSizeCategoryDidChange:(id)_handleContentSizeCategory;
-(void)_handleFavoritesShowsContactPhotosChanged:(id)changed;
-(void)_handleFavoritesEntryChanged:(id)changed;
-(void)layoutSubviews;
-(void)updateConstraints;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
