/* PHRecentCall.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface PHRecentCall : XXUnknownSuperclass {
	int _category;
	int _type;
	NSString* _destination;
	CFPhoneNumberRef _destinationPhoneNumber;
	NSDate* _date;
	double _duration;
	NSString* _compositeName;
	NSString* _destinationLabel;
	NSString* _destinationLocation;
	NSString* _mobileCountryCode;
	NSString* _mobileNetworkCode;
	NSString* _isoCountryCode;
	NSString* _CNAPFirstName;
	NSString* _CNAPSecondNames;
	int _uid;
	void* _addressBookRecord;
	int _identifier;
	unsigned _destinationIsFormatted : 1;
	unsigned _destinationIsBlocked : 1;
	CTCallRef _underlyingCTCall;
	int _unreadCount;
	double _bytesOfDataUsed;
}
@property(assign) int destinationIdentifier;
@property(assign) void* addressBookRecord;
@property(readonly, assign) int uid;
@property(assign) int unreadCount;
@property(assign) CFPhoneNumberRef destinationPhoneNumber;
@property(retain) NSString* isoCountryCode;
@property(retain) NSString* mobileNetworkCode;
@property(retain) NSString* mobileCountryCode;
@property(copy) NSString* _CNAPSecondNames;
@property(copy) NSString* _CNAPFirstName;
@property(assign) double bytesOfDataUsed;
+(int)callCategoryForCall:(CTCallRef)call;
+(int)callStatusForCall:(CTCallRef)call;
-(int)numberOfOccurrences;
-(id)callerDisplayName;
-(id)description;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(id)underlyingCTCalls;
-(void)deleteUnderlyingCTCall;
-(void)uncacheIdentity;
-(id)compositeName;
-(BOOL)representsCallAtDate:(id)date;
-(id)callOccurrences;
-(id)date;
-(void)setDate:(id)date;
-(double)duration;
-(void)setDuration:(double)duration;
-(void)setDestinationLocation:(id)location;
-(id)destinationStringForDisplay;
-(id)destinationLocation;
-(id)destinationLabel;
-(BOOL)destinationIsEmailAddress;
-(void)setDestinationIsBlocked:(BOOL)blocked;
-(BOOL)destinationIsBlocked;
-(id)formattedDestination;
-(id)destinationToDialAssisted:(BOOL*)dialAssisted;
-(id)addressBookDestination;
-(id)destination;
-(void)setDestination:(id)destination;
-(int)type;
-(void)setType:(int)type;
-(void)setCategory:(int)category;
-(int)category;
-(BOOL)canCoalesceWithCall:(id)call;
-(void)setCNAPFirstNameAndSecondNamesFromString:(id)string;
-(void)dealloc;
-(id)initWithCTCall:(CTCallRef)ctcall;
-(id)init;
@end
