/* PHStarkRootContainerViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UINavigationControllerDelegate.h"

@class UINavigationController, PHStarkMainMenuContainerViewController;

__attribute__((visibility("hidden")))
@interface PHStarkRootContainerViewController : XXUnknownSuperclass <UINavigationControllerDelegate> {
	UINavigationController* _wrapperNavigationController;
	PHStarkMainMenuContainerViewController* _mainMenuContainerViewController;
}
@property(retain) PHStarkMainMenuContainerViewController* mainMenuContainerViewController;
@property(retain) UINavigationController* wrapperNavigationController;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
