/* PHStarkManager.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHStarkHardwareControlsBroadcaster, UIWindow, PHStarkRootContainerViewController;

__attribute__((visibility("hidden")))
@interface PHStarkManager : XXUnknownSuperclass {
	PHStarkRootContainerViewController* _containerViewController;
	UIWindow* _starkWindow;
	PHStarkHardwareControlsBroadcaster* _hardwareControlsBroadcaster;
	PHStarkRootContainerViewController* _rootContainerViewController;
}
@property(retain) PHStarkRootContainerViewController* rootContainerViewController;
@property(retain) PHStarkHardwareControlsBroadcaster* hardwareControlsBroadcaster;
@property(readonly, assign) BOOL activeInterfaceMechanismIsHardware;
@property(retain) UIWindow* starkWindow;
@property(retain) PHStarkRootContainerViewController* containerViewController;
+(id)starkScreen;
+(id)sharedStarkManager;
-(void)screenshotStarkScreen;
-(void)attachStarkToScreen:(id)screen;
-(void)screenDidDisconnectNotification:(id)screen;
-(void)screenDidConnectNotification:(id)screen;
-(void)dealloc;
-(id)init;
@end
