/* PHVoicemailSlider.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class UIImageView;
@protocol PHVoicemailSliderDelegate;

__attribute__((visibility("hidden")))
@interface PHVoicemailSlider : XXUnknownSuperclass {
	UIImageView* _thumbImageView;
	BOOL _isTracking;
	id<PHVoicemailSliderDelegate> _voicemailSliderDelegate;
	CGPoint _previousLocationInView;
}
@property(assign) CGPoint previousLocationInView;
@property(assign) BOOL isTracking;
@property(assign) id<PHVoicemailSliderDelegate> voicemailSliderDelegate;
-(void)_setValueFromTracking:(float)tracking;
-(void)setValue:(float)value animated:(BOOL)animated;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(id)createThumbView;
-(CGRect)_thumbHitFrame;
@end
