/* PHVoicemailFolderCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PHVoicemailListViewController, UILabel, NSString;
@protocol PHVoicemailListViewControllerConcrete;

__attribute__((visibility("hidden")))
@interface PHVoicemailFolderCell : XXUnknownSuperclass {
	UILabel* _folderLabel;
	UILabel* _countLabel;
	PHVoicemailListViewController<PHVoicemailListViewControllerConcrete>* _viewController;
}
@property(retain, nonatomic) PHVoicemailListViewController<PHVoicemailListViewControllerConcrete>* viewController;
@property(readonly, assign, nonatomic) NSString* deletedText;
+(float)height;
-(void)_updateCount;
-(void)_handleContentSizeDidChange:(id)_handleContentSize;
-(void)_handleStoreChanged:(id)changed;
-(void)dealloc;
-(void)_updateFonts;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
