/* PHWallpaperView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobilePhone-Structs.h"

@class _UIBackdropView, UIImageView, UIImage;

__attribute__((visibility("hidden")))
@interface PHWallpaperView : XXUnknownSuperclass {
	BOOL _blursBackground;
	BOOL _hidesContactImage;
	BOOL _shouldLockContactImage;
	UIImage* _contactImage;
	float _blurProportion;
	UIImageView* _contactImageView;
	_UIBackdropView* _backdropEffectView;
}
@property(retain) _UIBackdropView* backdropEffectView;
@property(retain) UIImageView* contactImageView;
@property(assign) BOOL shouldLockContactImage;
@property(assign, nonatomic) BOOL hidesContactImage;
@property(assign, nonatomic) float blurProportion;
@property(assign, nonatomic) BOOL blursBackground;
@property(retain, nonatomic) UIImage* contactImage;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
