/* VoicemailOfflineView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIButton;

__attribute__((visibility("hidden")))
@interface VoicemailOfflineView : XXUnknownSuperclass {
	UIButton* _callButton;
	UILabel* _unavailableLabel;
	UILabel* _moreWaitingLabel;
	id _delegate;
}
-(void)_callButtonClicked:(id)clicked;
-(void)setMoreWaiting:(BOOL)waiting;
-(void)setDelegate:(id)delegate;
-(void)dealloc;
-(id)initWithWidth:(float)width dueToDisabledData:(BOOL)disabledData dueToRoaming:(BOOL)roaming;
@end
