/* VoicemailTrashMailboxController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "VoicemailMailboxController.h"
#import "MobilePhone-Structs.h"


__attribute__((visibility("hidden")))
@interface VoicemailTrashMailboxController : VoicemailMailboxController {
}
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)clearAll;
-(void)performMailboxDeleteActionForVoicemail:(id)voicemail;
-(BOOL)voicemailBelongsInThisMailbox:(id)thisMailbox;
-(void)refreshVoicemailsArray;
-(int)_trashedCount;
@end
