/* ChartIntervalButtonRow.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Stocks-Structs.h"

@class NSArray;
@protocol ChartIntervalButtonRowDelegate;

__attribute__((visibility("hidden")))
@interface ChartIntervalButtonRow : XXUnknownSuperclass {
	NSArray* _intervalButtons;
	id<ChartIntervalButtonRowDelegate> _delegate;
	int _maxChartInterval;
}
@property(assign, nonatomic) __weak id<ChartIntervalButtonRowDelegate> delegate;
@property(assign, nonatomic) int maxChartInterval;
-(void).cxx_destruct;
-(void)setSelected:(BOOL)selected forInterval:(int)interval;
-(void)intervalButtonsTappedOrSwiped:(id)swiped;
-(int)intervalForTouchLocation:(CGPoint)touchLocation;
-(void)layoutSubviews;
-(id)init;
@end
