/* ADCalendarEventJSO.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, EKRecurrenceRule, NSString;

__attribute__((visibility("hidden")))
@interface ADCalendarEventJSO : XXUnknownSuperclass {
	BOOL _allDay;
	NSString* _eventDescription;
	NSString* _location;
	NSString* _summary;
	NSDate* _start;
	NSDate* _end;
	EKRecurrenceRule* _recurrence;
}
@property(retain, nonatomic) EKRecurrenceRule* recurrence;
@property(assign, nonatomic) BOOL allDay;
@property(retain, nonatomic) NSDate* end;
@property(retain, nonatomic) NSDate* start;
@property(copy, nonatomic) NSString* summary;
@property(copy, nonatomic) NSString* location;
@property(copy, nonatomic) NSString* eventDescription;
-(id)_recurrenceRuleFromJSValue:(id)jsvalue;
-(id)EKEventInEventStore:(id)eventStore;
-(id)initWithDictionary:(id)dictionary;
-(void)dealloc;
@end
