/* ADCalendarJSO_Bindings.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "JSExport.h"

@class JSValue, NSDictionary;

@protocol ADCalendarJSO_Bindings <JSExport>
@property(assign, nonatomic) JSValue* rect;
@property(retain, nonatomic) JSValue* listener;
@property(retain, nonatomic) NSDictionary* event;
-(void)presentComposerWithEventProperties:(id)eventProperties listener:(id)listener popoverRect:(id)rect;
@optional
-(void)presentComposerWithEventProperties:(id)eventProperties listener:(id)listener popoverRect:(id)rect __JS_EXPORT_AS__presentComposer:(id)composer;
@end
