/* ADSAdImpressionController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AdSheet-Structs.h"

@class ADSCreativeController, ADAdImpressionPublicAttributes, NSTimer, NSString, ADSAdImpression, NSMutableSet;

__attribute__((visibility("hidden")))
@interface ADSAdImpressionController : XXUnknownSuperclass {
	BOOL _supportsAuthentication;
	BOOL _policyEngineManagedAd;
	ADSAdImpression* _ad;
	NSString* _authenticationUserName;
	id _loadCompletionHandler;
	NSMutableSet* _pendingRequiredItems;
	NSMutableSet* _allDownloadJobs;
	NSTimer* _loadTimeoutTimer;
	ADSCreativeController* _creativeController;
}
@property(retain, nonatomic) ADSCreativeController* creativeController;
@property(retain, nonatomic) NSTimer* loadTimeoutTimer;
@property(retain, nonatomic) NSMutableSet* allDownloadJobs;
@property(retain, nonatomic) NSMutableSet* pendingRequiredItems;
@property(copy, nonatomic) id loadCompletionHandler;
@property(assign, nonatomic) BOOL policyEngineManagedAd;
@property(readonly, assign, nonatomic) BOOL shouldUseTimeBasedConfirmedClick;
@property(assign, nonatomic) BOOL supportsAuthentication;
@property(copy, nonatomic) NSString* authenticationUserName;
@property(readonly, assign, nonatomic) ADSAdImpression* ad;
@property(readonly, assign, nonatomic) ADAdImpressionPublicAttributes* publicAttributes;
+(void)validateAdData:(id)data forClient:(id)client completion:(id)completion;
+(id)probeDictionaryForAdData:(id)adData;
+(id)sharedDownloader;
-(void)reportServerErrorWithCode:(int)code details:(id)details failingURLs:(id)urls;
-(void)reportContentErrorWithInfo:(id)info;
-(void)reportContentEvent:(id)event;
-(void)reportSystemEvent:(int)event;
-(void)reportExternalActionApproved:(BOOL)approved;
-(void)reportConfirmedClick;
-(void)adActionEndedWithSystemEvent:(int)systemEvent;
-(void)adActionBeganWithClickLocation:(CGPoint)clickLocation withAdViewFrame:(CGRect)adViewFrame;
-(void)adActionBegan;
-(void)reportImpression;
-(void)loadCreativeControllerForSize:(CGSize)size completion:(id)completion;
-(void)_load;
-(void)_loadTimedOut;
-(void)_fetchWebArchiveWithURL:(id)url injectQueryString:(id)string completion:(id)completion;
-(void)_fetchDataAtURL:(id)url completion:(id)completion;
-(BOOL)_handleArchiveSubResource:(id)resource maxAge:(double)age;
-(id)_assetRetrieveErrorForURLString:(id)urlstring errorMessage:(id)message;
-(void)_failWithError:(id)error;
-(void)cancelLoading;
-(void)_processCompletionOfItem:(id)item error:(id)error;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(id)initWithAdData:(id)adData loadedCompletion:(id)completion;
-(void)dealloc;
@end
