/* ADSAdSpace.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AdSheet-Structs.h"
#import "ADSAdSpace_RPC.h"

@class ADSSession, NSURL, NSString, ADSAdSpaceController;
@protocol NSObject, ADAdSpace_RPC;

__attribute__((visibility("hidden")))
@interface ADSAdSpace : XXUnknownSuperclass <ADSAdSpace_RPC> {
	ADSSession* _session;
	BOOL _shouldNotCycle;
	BOOL _setupComplete;
	BOOL _hasSentVisibleWithoutContentError;
	BOOL _hasLoadedAdOrSentError;
	BOOL _closed;
	id<NSObject, ADAdSpace_RPC> _clientAdSpace;
	int _creativeType;
	ADSAdSpaceController* _adSpaceController;
	NSString* _identifier;
	NSURL* _serverURL;
	NSString* _section;
	NSString* _authenticationUserName;
	int _visibility;
	int _options;
	double _creationTimestamp;
	double _lastVisibleTimestamp;
	CGRect _frame;
}
@property(assign, nonatomic) BOOL closed;
@property(readonly, assign, nonatomic) int options;
@property(assign, nonatomic) BOOL hasLoadedAdOrSentError;
@property(assign, nonatomic) BOOL hasSentVisibleWithoutContentError;
@property(assign, nonatomic) int visibility;
@property(copy, nonatomic) NSString* authenticationUserName;
@property(copy, nonatomic) NSString* section;
@property(copy, nonatomic) NSURL* serverURL;
@property(copy, nonatomic) NSString* identifier;
@property(assign, nonatomic) CGRect frame;
@property(retain, nonatomic) ADSAdSpaceController* adSpaceController;
@property(assign, nonatomic) double lastVisibleTimestamp;
@property(readonly, assign, nonatomic) double creationTimestamp;
@property(assign, nonatomic) BOOL setupComplete;
@property(assign, nonatomic) BOOL shouldNotCycle;
@property(readonly, assign, nonatomic) BOOL shouldPreloadAction;
@property(readonly, assign, nonatomic) BOOL excludedFromControllerPool;
@property(readonly, assign, nonatomic) BOOL policyEngineManagesLoading;
@property(readonly, assign, nonatomic) int creativeType;
@property(retain, nonatomic) id<NSObject, ADAdSpace_RPC> clientAdSpace;
@property(assign, nonatomic) __weak ADSSession* session;
-(void)_remote_cancelScheduledAd;
-(void)_remote_playbackFailedForURL:(id)url;
-(void)_remote_playbackFinishedForContentHash:(id)contentHash;
-(void)_remote_playbackResumed;
-(void)_remote_playbackPaused;
-(void)_remote_playbackStarted;
-(void)_remote_scheduleAd;
-(void)_remote_interstitialRemovedFromSuperview;
-(void)_remote_presentInterstitialStoryboard;
-(void)_remote_bannerCancelAction;
-(void)_remote_bannerRefuseAction;
-(void)_remote_bannerBeginActionFromFrame:(id)frame tapLocation:(id)location;
-(void)_remote_setShouldNotCycle:(BOOL)_remote_set;
-(void)_remote_setVisibility:(int)visibility;
-(void)_remote_setAuthenticationUserName:(id)name;
-(void)_remote_setSection:(id)section;
-(void)_priv_cycleImpressionImmediately;
-(void)_priv_setServerURL:(id)url;
-(void)_remote_setIdentifier:(id)identifier;
-(void)_remote_setFrame:(id)frame;
-(void)_remote_close;
-(void)_remote_setupComplete;
-(void)close;
-(id)initWithClientAdSpace:(id)clientAdSpace creativeType:(int)type options:(int)options;
-(void)dealloc;
@end
