/* ADSAssertionManager.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, NSCountedSet;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface ADSAssertionManager : XXUnknownSuperclass {
	int _assertionCount;
	NSCountedSet* _objectAssertions;
	NSObject<OS_dispatch_queue>* _queue;
	unsigned _powerAssertionID;
	double _shutdownScheduledTime;
}
@property(assign, nonatomic) unsigned powerAssertionID;
@property(assign, nonatomic) double shutdownScheduledTime;
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* queue;
@property(retain, nonatomic) NSCountedSet* objectAssertions;
@property(assign, nonatomic) int assertionCount;
@property(readonly, assign, nonatomic) int numberOfActiveAssertions;
+(id)sharedInstance;
-(void)returnObjectAssertion:(id)assertion;
-(void)takeObjectAssertion:(id)assertion;
-(void)_shutdown;
-(void)_returnClientAssertion;
-(void)_takeClientAssertion;
-(void)_takePowerAssertionForInterval:(double)interval;
-(void)_releasePowerAssertionIfHeld;
-(void)returnClientAssertion;
-(void)takeClientAssertion;
-(id)init;
@end
