/* ADSCreativeView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AdSheet-Structs.h"
#import "ADWebView.h"

@class ADSAdImpression;

__attribute__((visibility("hidden")))
@interface ADSCreativeView : ADWebView {
	ADSAdImpression* _adImpression;
}
@property(retain, nonatomic) ADSAdImpression* adImpression;
-(void)dealloc;
@end
