/* ADStoreItemOfferJSO_Bindings.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "JSExport.h"

@class NSString;

@protocol ADStoreItemOfferJSO_Bindings <JSExport>
@property(readonly, assign, nonatomic) BOOL preorder;
@property(readonly, assign, nonatomic) NSString* action;
@property(readonly, assign, nonatomic) NSString* price;
@property(readonly, assign, nonatomic) NSString* identifier;
@end
