/* Base.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class NSObject;

__attribute__((visibility("hidden")))
@interface Base : UITableViewCell {
	NSObject* sectionRef;
}
+(short)lookUpECNO:(unsigned)ecno;
-(void)replaceArray:(id)array With:(id)with;
-(void)clearElementsInArray:(id)array;
-(void)updateLogCodeDict:(id)dict;
-(id)getLogCodeArray;
-(id)getSectionName;
-(void)updateWithData:(id)data logCode:(int)code;
-(void)updateSectionRef:(id)ref;
-(id)init;
@end
