/* EURLogGenerator.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "LogGenerator.h"

@class NSMutableData;

__attribute__((visibility("hidden")))
@interface EURLogGenerator : LogGenerator {
	NSMutableData* _binData;
}
-(id)getSaveContentsFromState:(id)state;
-(id)generateDlfFromState:(id)state;
-(void)dealloc;
-(id)init;
@end
