/* FieldTestCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIScrollView, UILabel;

__attribute__((visibility("hidden")))
@interface FieldTestCell : XXUnknownSuperclass {
	UILabel* key;
	UILabel* value;
	UIScrollView* view;
}
@property(retain, nonatomic) UILabel* value;
@property(retain, nonatomic) UILabel* key;
-(void)setLayout;
-(void)setLayoutKey;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)initWithStyleKey:(int)styleKey reuseIdentifier:(id)identifier;
@end
