/* UTRANClassIndex.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "ClassIndex.h"

@class CCTRCHSIRMeasurement, UTRANServingCellInfo, PDPContextList, SimInfo, RRC_State, CellReselectionRankList, UTRANNeighbhorMeasurements, GSMNeighbhorMeasurements, TRCHBLERMeasurement;

__attribute__((visibility("hidden")))
@interface UTRANClassIndex : ClassIndex {
	RRC_State* rrc_state;
	UTRANServingCellInfo* servingCellInfo;
@private
	UTRANNeighbhorMeasurements* tdMeasurements;
@protected
	GSMNeighbhorMeasurements* gsmMeasurements;
	TRCHBLERMeasurement* trchMeasurements;
	CCTRCHSIRMeasurement* cctrchMeasurements;
	CellReselectionRankList* reselectionList;
@private
	PDPContextList* pdpList;
@protected
	SimInfo* simInfo;
}
-(void)dealloc;
-(id)init;
@end
