/* StocksListWeeAppTableViewCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "StocksWeeApp-Structs.h"

@class UILabel, Stock, StocksListBoxView;

@interface StocksListWeeAppTableViewCell : XXUnknownSuperclass {
	UILabel* _symbolLabel;
	UILabel* _priceLabel;
@private
	UILabel* _boxLabel;
@protected
	StocksListBoxView* _boxView;
	UILabel* _changeSignLabel;
	UILabel* _percentSignLabel;
	Stock* _stock;
	int _rowDataType;
}
@property(assign, nonatomic) int rowDataType;
@property(retain, nonatomic) Stock* stock;
-(void).cxx_destruct;
-(CGRect)changeButtonRect;
-(void)layoutSubviews;
-(void)setBoxValueFromRowDataType;
-(void)updateValues;
-(void)prepareForReuse;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
