/* VOTOutputRequestRunner.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "vot-Structs.h"

@class NSArray, VOTOutputRequest;

@interface VOTOutputRequestRunner : XXUnknownSuperclass {
	BOOL _isActive;
	unsigned long _currentActionIndex;
	VOTOutputRequest* _currentRequest;
	NSArray* _currentActions;
	BOOL _didProcessNoSyncActions;
	NSRange _currentRange;
}
-(void)_processActions;
-(void)_handleProcessActions:(id)actions;
-(void)_handleNotifications:(id)notifications;
-(void)resume;
-(void)handleEvent:(id)event;
-(void)sendNotification:(unsigned long)notification;
-(void)runOutputRequest:(id)request;
-(BOOL)isActive;
-(void)setIsActive:(BOOL)active;
-(void)dealloc;
@end
