/* AccessibilitySettings-Structs.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct _NSRange {
	unsigned _field1;
	unsigned _field2;
} NSRange;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct BTDeviceImpl* BTDeviceImplRef;

typedef struct BTLocalDeviceImpl* BTLocalDeviceImplRef;

typedef struct BTSessionImpl* BTSessionImplRef;

typedef struct BTDiscoveryAgentImpl* BTDiscoveryAgentImplRef;

typedef struct BTPairingAgentImpl* BTPairingAgentImplRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CFString* CFStringRef;

typedef struct __CFNumber* CFNumberRef;

typedef struct CGColor* CGColorRef;

typedef struct CGFont* CGFontRef;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct NSString {
	Class _field1;
} NSString;

typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct __IOHIDEvent* IOHIDEventRef;
