/* ASTGestureRecorderControlsView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIButton, UIProgressView, UIImage;
@protocol ASTGestureRecorderControlsViewDelegate;

__attribute__((visibility("hidden")))
@interface ASTGestureRecorderControlsView : XXUnknownSuperclass {
@private
	id<ASTGestureRecorderControlsViewDelegate> _delegate;
	UIButton* _leftButton;
	UIButton* _rightButton;
	UIProgressView* _progressView;
	UIImage* _padBackground;
}
@property(retain, nonatomic) id rightButton;
@property(retain, nonatomic) id leftButton;
@property(assign, nonatomic, getter=isRightButtonEnabled) BOOL rightButtonEnabled;
@property(assign, nonatomic, getter=isLeftButtonEnabled) BOOL leftButtonEnabled;
@property(assign, nonatomic) float progress;
@property(assign, nonatomic) id<ASTGestureRecorderControlsViewDelegate> delegate;
+(float)defaultHeight;
+(void)_loadImages;
-(void)_buttonTapped:(id)tapped;
-(void)drawRect:(CGRect)rect;
-(void)setLeftButtonColor:(int)color title:(id)title icon:(id)icon enabled:(BOOL)enabled rightButtonColor:(int)color5 title:(id)title6 icon:(id)icon7 enabled:(BOOL)enabled8 animationDuration:(double)duration completion:(id)completion;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
