/* AXCaptionStyleChooserController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import "AccessibilityBaseListController.h"
#import "AXCaptionPreviewDelegate.h"

@class UIWindow, UIView, NSArray;

__attribute__((visibility("hidden")))
@interface AXCaptionStyleChooserController : AccessibilityBaseListController <AXCaptionPreviewDelegate> {
@private
	UIWindow* _fullScreenPreviewWindow;
	UIView* _landscapeBlackBackgroundView;
	UIView* _topHalfSplitImage;
	UIView* _bottomHalfSplitImage;
	UIView* _padSidePortionImage;
	CFStringRef profileId;
	NSArray* captionPreviewSpecifiers;
	NSArray* videoOverrideSpecifiers;
}
@property(readonly, assign, nonatomic) NSArray* videoOverrideSpecifiers;
@property(readonly, assign, nonatomic) NSArray* captionPreviewSpecifiers;
@property(readonly, assign, nonatomic) CFStringRef profileId;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)captionPreviewWasTapped:(BOOL)tapped;
-(BOOL)isPreviewExpanded;
-(id)_snapshotWindow:(id)window;
-(id)_splitImageAppropriately:(id)appropriately statusBar:(id)bar secondHalfStart:(CGPoint)start;
-(BOOL)isStoredColorType:(int)type equalWithColors:(id)colors;
-(BOOL)isStoredTransparencyType:(int)type equalWithTransparency:(id)transparency;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(BOOL)shouldAutorotate;
-(id)_videoOverrideText;
-(void)_setVideoOverridesStyle:(id)style specifier:(id)specifier;
-(id)_videoOverridesStyle:(id)style;
-(void)willResignActive;
-(void)updateTableCheckedSelection:(id)selection;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
