/* AXCaptioningThemeController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import "AXCaptionStyleChooserController.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface AXCaptioningThemeController : AXCaptionStyleChooserController {
@private
	NSMutableArray* _editableHiddenSpecifiers;
	NSMutableArray* _editableVisibleSpecifiers;
	BOOL _isEditingTable;
	NSMutableArray* _customProfiles;
	NSMutableArray* _defaultProfiles;
}
@property(retain, nonatomic) NSMutableArray* defaultProfiles;
@property(retain, nonatomic) NSMutableArray* customProfiles;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)_manageHiddenSpecifiers:(BOOL)specifiers editing:(BOOL)editing;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)_donePressed;
-(void)_editPressed;
-(void)_addEditButton;
-(void)viewWillAppear:(BOOL)view;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)_selectProfile:(id)profile;
-(void)_setVideoOverridesStyle:(id)style specifier:(id)specifier;
-(id)_videoOverridesStyle:(id)style;
-(BOOL)_profileOverridesStyle:(CFStringRef)style;
-(void)viewDidLoad;
-(void)_resetActiveProfileToDefault;
-(id)specifiers;
-(void)_themeCountChanged:(id)changed;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(void)dealloc;
@end
