/* AXColorWell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class StrokableLabel, UIColor;

__attribute__((visibility("hidden")))
@interface AXColorWell : XXUnknownSuperclass {
@private
	StrokableLabel* _sampleTextLabel;
	int _colorType;
	UIColor* wellColor;
	int _transparencyType;
	long _edgeStyle;
	float _textAlpha;
}
@property(assign, nonatomic) float textAlpha;
@property(assign, nonatomic) long edgeStyle;
@property(assign, nonatomic) int transparencyType;
@property(assign, nonatomic) int colorType;
@property(retain, nonatomic) UIColor* wellColor;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(void)layoutSubviews;
-(void)updateProperties;
-(id)initWithFrame:(CGRect)frame;
@end
