/* InstructionsView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "PSHeaderFooterView.h"

@class NSMutableArray, PSSpecifier, UILabel;

__attribute__((visibility("hidden")))
@interface InstructionsView : XXUnknownSuperclass <PSHeaderFooterView> {
@private
	PSSpecifier* _specifier;
	CGSize _totalSize;
	UILabel* _headerLabel;
	NSMutableArray* _contentLabels;
	float _backgroundInset;
	float backgroundInset;
}
@property(assign, nonatomic) float backgroundInset;
-(float)preferredHeightForWidth:(float)width;
-(void)dealloc;
-(void)_initializeContent;
-(void)layoutSubviews;
-(id)initWithSpecifier:(id)specifier;
@end
