/* SCATScanTimeoutPickerViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SCATDelayPickerViewController.h"


__attribute__((visibility("hidden")))
@interface SCATScanTimeoutPickerViewController : SCATDelayPickerViewController {
}
-(double)stepAmount;
-(id)localizedTitle;
-(id)localizedFooterText;
-(void)setDelayFromUser:(double)user;
-(double)delayFromPreferences;
-(double)minimumTime;
-(double)maximumTime;
-(BOOL)userCanDisableDelay;
-(void)setDelayEnabledFromUser:(BOOL)user;
-(BOOL)delayEnabledFromPreferences;
@end
