/* VoiceOverController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilityListController.h"

@class PSSpecifier, VoiceOverGestureHelpViewController;

__attribute__((visibility("hidden")))
@interface VoiceOverController : AccessibilityListController {
@private
	PSSpecifier* _voiceOverOnSpecifier;
	PSSpecifier* _voiceOverGestureHelpSpecifier;
	PSSpecifier* _voiceOverGestureHelpSpacerSpecifier;
	VoiceOverGestureHelpViewController* _gestureHelpViewController;
	BOOL _ignoreNextReload;
}
+(void)setVoiceOverEnabled:(BOOL)enabled;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)speakingRateInRotor:(id)rotor;
-(void)setSpeakingRateInRotor:(id)rotor specifier:(id)specifier;
-(id)navigateImagesPreferenceForSpecifier:(id)specifier;
-(id)cursorStyleForSpecifier:(id)specifier;
-(void)cursorStyleSetPreference:(id)preference specifier:(id)specifier;
-(id)brailleDisplayNameForSpecifier:(id)specifier;
-(id)compactVoiceEnabled:(id)enabled;
-(void)setCompactVoiceEnabled:(id)enabled specifier:(id)specifier;
-(id)pitchChangeEnabled:(id)enabled;
-(void)setPitchChangeEnabled:(id)enabled specifier:(id)specifier;
-(id)soundEffectsEnabled:(id)enabled;
-(void)setSoundEffectsEnabled:(id)enabled specifier:(id)specifier;
-(id)phoneticsEnabled:(id)enabled;
-(void)setPhoneticsEnabled:(id)enabled specifier:(id)specifier;
-(void)setTypingFeedback:(id)feedback specifier:(id)specifier;
-(id)typingFeedback:(id)feedback;
-(id)speakNotificationsInLockScreen:(id)lockScreen;
-(void)setSpeakNotificationsInLockScreen:(id)lockScreen specifier:(id)specifier;
-(id)hintsEnabled:(id)enabled;
-(void)setHintsEnabled:(id)enabled specifier:(id)specifier;
-(id)speakingRate:(id)rate;
-(void)setSpeakingRate:(id)rate specifier:(id)specifier;
-(id)voiceOverTouchEnabled:(id)enabled;
-(void)startGestureHelp:(id)help;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)setVoiceOverTouchEnabled:(id)enabled specifier:(id)specifier;
-(void)voiceOverActivateWorkaround:(id)workaround;
-(void)_changeVOActivationSpecifierIntoSwitchCell:(id)cell;
-(void)_changeVOActivationSpecifierIntoButtonCell:(id)cell;
-(id)specifiers;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)_bluetoothBrailleDisplayChange;
-(void)reload;
-(void)_manageGestureHelpButton;
-(void)viewWillAppear:(BOOL)view;
-(void)_manageCompactVoiceOption;
-(void)dealloc;
-(id)init;
@end
