/* VoiceOverBluetoothDevice.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface VoiceOverBluetoothDevice : XXUnknownSuperclass <NSCopying> {
@private
	NSString* _name;
	NSString* _address;
	BTDeviceImplRef _device;
}
-(void)unpair;
-(void)acceptSSP:(int)ssp;
-(void)setPIN:(id)pin;
-(void)disconnect;
-(void)connectWithServices:(unsigned)services;
-(void)connect;
-(unsigned)authorizedServices;
-(BOOL)isServiceSupported:(unsigned)supported;
-(unsigned)connectedServicesCount;
-(unsigned)connectedServices;
-(BOOL)connected;
-(BOOL)paired;
-(id)description;
-(unsigned)deviceClass;
-(unsigned)minorClass;
-(unsigned)majorClass;
-(int)type;
-(id)address;
-(id)name;
-(BOOL)isNameCached;
-(void)_clearName;
-(void)setDevice:(BTDeviceImplRef)device;
-(BTDeviceImplRef)device;
-(int)compare:(id)compare;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithDevice:(BTDeviceImplRef)device address:(id)address;
@end
