/* XXUnknownSuperclass.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AccessibilitySettings-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (ASTExtensions)
-(id)ast_subImageInRect:(CGRect)rect;
@end

@interface XXUnknownSuperclass (AXPriv)
-(BOOL)isEditableCaptionProfile;
@end

@interface XXUnknownSuperclass (AXPriv)
-(BOOL)isEditableCaptionProfile;
-(BOOL)isCaptionProfile;
@end

@interface XXUnknownSuperclass (AXPriv)
-(id)imageScaledToSize:(CGSize)size;
@end
