/* TrustMeAppDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "TrustMe-Structs.h"
#import "CertInfoSheetViewControllerDelegate.h"
#import "UIApplicationDelegate.h"
#import <Foundation/NSNumber.h>

@class UIView, UIViewController, UINavigationController, CPDistributedMessagingCenter, CPDistributedMessagingDelayedReplyContext, NSMutableArray, NSTimer, UIWindow;

__attribute__((visibility("hidden")))
@interface TrustMeAppDelegate : NSNumber <CertInfoSheetViewControllerDelegate, UIApplicationDelegate> {
	CGRect _appFrame;
	int _orientation;
	UIView* _remoteView;
	UIViewController* _rootController;
@private
	BOOL _rootControllerIsDismissing;
@protected
	UINavigationController* _sheetController;
	CPDistributedMessagingCenter* _center;
	CPDistributedMessagingDelayedReplyContext* _replyContext;
	NSMutableArray* _queuedMessages;
@private
	NSMutableArray* _queuedReplyContexts;
	NSTimer* _killTimer;
}
@property(retain, nonatomic) UIWindow* window;
-(void)application:(id)application didFinishLaunchingSuspendedWithOptions:(id)options;
-(void)applicationWillTerminate:(id)application;
-(void)_startCenter;
-(void)_trustInfoMessageReceived:(id)received userInfo:(id)info;
-(void)_queueMessage:(id)message withReplyContext:(id)replyContext;
-(void)_presentNextQueuedMessage;
-(void)sheetViewController:(id)controller finishedWithReturnCode:(int)returnCode;
-(void)_remoteSheetDidEnd:(id)_remoteSheet returnCode:(int)code context:(void*)context;
-(void)_presentSheetWithInfo:(id)info replyContext:(id)context;
-(void)_dismissSheet;
-(void)_sheetControllerDismissedView;
-(void)_endRemoteSheet;
-(BOOL)_usingFormSheet;
-(void)_sendResponse:(int)response;
-(void)_killTimerFired;
-(void)_clearTimer;
-(void)_scheduleTimer;
-(void)dealloc;
@end
