/* NikeSettingsController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: /System/Library/PreferenceBundles/VictoriaSettings.bundle/VictoriaSettings
 */

#import "MPMediaPickerControllerDelegate.h"
#import "SWSyncControllerDelegate.h"
#import "STBaseSettingsController.h"

@class UIAlertView, MPMediaPickerController, UIView, SWSyncController;

@interface NikeSettingsController : STBaseSettingsController <MPMediaPickerControllerDelegate, SWSyncControllerDelegate> {
	UIAlertView* _relinkConfirmAlert;
	MPMediaPickerController* _mediaPicker;
	UIView* _mediaPickerView;
	SWSyncController* _syncController;
	unsigned _syncBackgroundTaskIdentifier;
	BOOL _isSyncing;
}
-(id)isSDAEnabled;
-(void)setSDAEnabled:(id)enabled;
-(BOOL)isSDAUnlocked;
-(id)deviceDirectory;
-(void)syncControllerDidFinishSyncing:(id)syncController success:(BOOL)success loginURL:(id)url;
-(void)sendAllWorkoutsToNike:(id)nike;
-(void)resetCalibration:(id)calibration;
-(id)weight:(id)weight;
-(id)powerSongTitle:(id)title;
-(void)mediaPickerDidCancel:(id)mediaPicker;
-(void)mediaPicker:(id)picker didPickMediaItems:(id)items;
-(void)showPowerSongPicker:(id)picker;
-(void)setNikeEnabled:(id)enabled specifier:(id)specifier;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)_updateItems:(BOOL)items;
-(void)_updateSendToNikeButton;
-(void)_applicationDidBecomeActive:(id)_application;
-(id)specifiers;
-(void)dealloc;
-(id)init;
@end
