/* GKSettingsViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "GKDaemonProxyDataUpdateDelegate.h"
#import "AAUICredentialRecoveryPresentationDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, GKLocalPlayer, AAUICredentialRecoveryController, NSString;

@interface GKSettingsViewController : XXUnknownSuperclass <GKDaemonProxyDataUpdateDelegate, AAUICredentialRecoveryPresentationDelegate> {
	BOOL _shouldUseContacts;
	BOOL _shouldUseFacebook;
	int _settingsMode;
	NSString* _appleID;
	NSString* _defaultAppleID;
	NSString* _password;
	NSString* _nickname;
	NSString* _emailAddress;
	NSArray* _availableExternalServices;
	GKLocalPlayer* _localPlayer;
	NSArray* _specifiersSensitiveToConnectivity;
	AAUICredentialRecoveryController* _credentialRecoveryController;
}
@property(retain, nonatomic) AAUICredentialRecoveryController* credentialRecoveryController;
@property(readonly, assign, nonatomic) NSArray* specifiersSensitiveToConnectivity;
@property(retain, nonatomic) GKLocalPlayer* localPlayer;
@property(retain, nonatomic) NSArray* availableExternalServices;
@property(retain, nonatomic) NSString* emailAddress;
@property(retain, nonatomic) NSString* nickname;
@property(retain, nonatomic) NSString* password;
@property(readonly, assign, nonatomic) NSString* defaultAppleID;
@property(retain, nonatomic) NSString* appleID;
@property(assign, nonatomic) BOOL shouldUseFacebook;
@property(assign, nonatomic) BOOL shouldUseContacts;
@property(assign, nonatomic) BOOL allowNearbyMultiplayer;
@property(assign, nonatomic) BOOL allowGameInvites;
@property(assign, nonatomic) int settingsMode;
-(void)credentialRecoveryController:(id)controller finishedWithSuccess:(BOOL)success;
-(void)credentialRecoveryController:(id)controller didFailWithError:(id)error;
-(void)credentialRecoveryController:(id)controller needsPresentationOfViewController:(id)viewController;
-(void)editProfile:(id)profile;
-(void)iForgotTapped:(id)tapped;
-(void)showAccountOptions:(id)options;
-(void)createAccountButtonTapped:(id)tapped;
-(void)signinButtonTapped:(id)tapped;
-(void)updateSigninButtonSpecifier;
-(void)setValue:(id)value forSpecifier:(id)specifier;
-(void)textFieldValueDidChange:(id)textFieldValue;
-(void)textFieldDidEndEditing:(id)textField;
-(id)specifierForTextField:(id)textField;
-(BOOL)shouldAllowSignIn;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)externalServiceSpecifiers;
-(id)emailAddressFromSpecifier:(id)specifier;
-(id)createAccountButtonSpecifier;
-(id)passwordSpecifier;
-(id)appleIDSpecifier;
-(id)nicknameSpecifier;
-(id)signinButtonSpecifier;
-(id)loginSpecifiers;
-(id)specifiersForSignedOutMode;
-(id)specifiersForSignedInMode;
-(id)loadFreshSpecifiers;
-(void)finishFriendRecommendationsForService:(BOOL)service withError:(id)error;
-(id)specifiers;
-(void)finishAuthenticationWithResponse:(id)response;
-(void)finishAuthenticationWithError:(id)error;
-(void)showGreenBuddy;
-(void)refreshContentsForDataType:(unsigned)dataType userInfo:(id)info;
-(void)authenticatedPlayerDidChange:(id)authenticatedPlayer;
-(void)observeEnterForegroundNotification:(id)notification;
-(void)dealloc;
-(id)init;
@end
