/* ArtistsViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "FocusedTableViewController.h"
#import "iPodOut-Structs.h"

@class MPMediaQuery;

__attribute__((visibility("hidden")))
@interface ArtistsViewController : FocusedTableViewController {
	MPMediaQuery* artistsQuery;
	unsigned actionRowCount;
}
@property(assign, nonatomic) unsigned actionRowCount;
@property(retain, nonatomic) MPMediaQuery* artistsQuery;
-(void).cxx_destruct;
-(int)restoreWithPathComponent:(id)pathComponent;
-(void)writeCurrentPositionIntoNavigationPathComponent:(id)component;
-(int)rowWithIdentifier:(unsigned long long)identifier;
-(BOOL)enableQuickNav;
-(id)viewControllerForCurrentRow;
-(void)selectCurrentRowWithTransition:(int)transition;
-(void)selectAction:(BOOL)action transition:(int)transition;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(unsigned)minimumRowHeight;
-(id)statusBarTitle;
-(id)initWithArtistsQuery:(id)artistsQuery;
-(id)init;
@end
