/* FocusedTableViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "iPodOut-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "iPodOutViewController.h"
#import "FocusedTableContainerViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, UITableView, NSString, UIImage, UIImageView;

__attribute__((visibility("hidden")))
@interface FocusedTableViewController : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate, iPodOutViewController, FocusedTableContainerViewDelegate> {
	BOOL viewHasAppeared;
	BOOL centerOnNextAppear;
	unsigned currentRow;
	NSMutableArray* quickNavGroups;
	int ignoreNextButtonUp;
	unsigned visibleCellsCount;
}
@property(assign, nonatomic) unsigned visibleCellsCount;
@property(readonly, assign, nonatomic) int alignment;
@property(readonly, assign, nonatomic) unsigned minimumRowHeight;
@property(readonly, assign, nonatomic) float statusBarHeight;
@property(assign, nonatomic) BOOL viewHasAppeared;
@property(assign, nonatomic) int ignoreNextButtonUp;
@property(readonly, assign, nonatomic) UIImageView* quickNavOverlayView;
@property(assign, nonatomic) BOOL centerOnNextAppear;
@property(assign, nonatomic) BOOL showBackButton;
@property(retain, nonatomic) NSMutableArray* quickNavGroups;
@property(readonly, assign, nonatomic) BOOL enableQuickNav;
@property(readonly, assign, nonatomic) UIImage* statusBarImage;
@property(readonly, assign, nonatomic) NSString* statusBarSubtitle;
@property(readonly, assign, nonatomic) NSString* statusBarTitle;
@property(readonly, assign, nonatomic) UITableView* tableView;
@property(assign, nonatomic) unsigned currentRow;
-(void).cxx_destruct;
-(void)_restartNowPlayingTimer;
-(void)_selectRowAtIndexPath:(id)indexPath longPress:(BOOL)press;
-(void)quickNavDown;
-(void)quickNavUp;
-(void)scrollDown;
-(void)scrollUp;
-(void)_viewTapped:(id)tapped;
-(void)_putUpBackgroundView;
-(void)_safeScrollToRow:(int)row atScrollPosition:(int)scrollPosition;
-(unsigned)_indexOfTopVisibleRow;
-(void)_handleLongPress:(id)press;
-(void)selectAction:(BOOL)action transition:(int)transition;
-(void)selectAction:(BOOL)action;
-(void)counterClockwiseRotationAction:(BOOL)action;
-(void)clockwiseRotationAction:(BOOL)action;
-(void)rightAction:(BOOL)action;
-(void)leftAction:(BOOL)action;
-(void)downAction:(BOOL)action;
-(void)upAction:(BOOL)action;
-(void)populateQuickNavGroupsForCollectionsFromQuery:(id)query withOffset:(unsigned)offset;
-(void)populateQuickNavGroupsForItemsFromQuery:(id)query withOffset:(unsigned)offset;
-(void)exitQuickNavMode;
-(void)_showQuickNavOverlayWithShorthand:(id)shorthand;
-(void)_restartQuickNavTimer;
-(BOOL)inQuickNavMode;
-(id)nextQuickNavGroup;
-(id)previousQuickNavGroup;
-(void)_pushNowPlayingViewController;
-(void)_nowPlayingAppIsPlayingDidChange;
-(int)restoreWithPathComponent:(id)pathComponent;
-(void)writeCurrentPositionIntoNavigationPathComponent:(id)component;
-(unsigned)rowOfPathComponent:(id)pathComponent;
-(void)ensureCurrentRowIsSelectedAndVisible;
-(id)viewControllerForCurrentRow;
-(int)rowWithIdentifier:(unsigned long long)identifier;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end
