/* iPodOutApplication.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "iPodOut-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface iPodOutApplication : XXUnknownSuperclass {
	unsigned long long touchDelayTimeMS;
}
@property(assign, nonatomic) unsigned long long touchDelayTimeMS;
+(id)sharedAppDelegate;
-(void)userEventOccurred;
-(id)sharedDateFormatter;
-(id)sharedDecimalFormatter;
-(BOOL)applicationSuspend:(GSEventRef)suspend settings:(id)settings;
@end
