/* NowPlayingViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "iPodOutViewController.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NowPlayingViewController : XXUnknownSuperclass <iPodOutViewController> {
	BOOL longPressing;
	int seekState;
	unsigned long long expectedFirstTrackIdentifier;
}
@property(assign, nonatomic) unsigned long long expectedFirstTrackIdentifier;
@property(assign, nonatomic) BOOL longPressing;
@property(assign, nonatomic) int seekState;
+(BOOL)iPodIsNowPlayingApp;
-(id)viewControllerForCurrentRow;
-(int)restoreWithPathComponent:(id)pathComponent;
-(void)writeCurrentPositionIntoNavigationPathComponent:(id)component;
-(void)nowPlayingInfoDidChange;
-(BOOL)autoRepeatDisabled;
-(void)counterClockwiseRotationAction:(BOOL)action;
-(void)clockwiseRotationAction:(BOOL)action;
-(void)rightAction:(BOOL)action;
-(void)leftAction:(BOOL)action;
-(void)downAction:(BOOL)action;
-(void)upAction:(BOOL)action;
-(void)selectAction:(BOOL)action;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(void)dealloc;
-(id)initWithExistingPlayerAndPlay:(BOOL)existingPlayerAndPlay;
-(id)initWithStation:(id)station;
-(id)initWithGeniusMix:(id)geniusMix;
-(id)initWithQueryToShuffle:(id)shuffle;
-(id)initWithSongs:(id)songs;
-(id)initWithQuery:(id)query startingAtIndex:(unsigned)index;
-(id)init;
@end
