/* PodcastEpisodesViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "LeafViewController.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface PodcastEpisodesViewController : LeafViewController {
	NSString* statusBarTitle;
}
@property(copy, nonatomic) NSString* statusBarTitle;
-(void).cxx_destruct;
-(int)restoreWithPathComponent:(id)pathComponent;
-(void)writeCurrentPositionIntoNavigationPathComponent:(id)component;
-(unsigned)rowOfPathComponent:(id)pathComponent;
-(void)selectAction:(BOOL)action transition:(int)transition;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)initWithPodcastEpisodesQuery:(id)podcastEpisodesQuery;
@end
