/* SongsTableViewCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "iPodOutTableViewCell.h"

@class iPodOutLabel;

__attribute__((visibility("hidden")))
@interface SongsTableViewCell : iPodOutTableViewCell {
	iPodOutLabel* rowNumberLabel;
}
@property(retain, nonatomic) iPodOutLabel* rowNumberLabel;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
@end
