/* CalcKeypadViewDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Calculator-Structs.h"
#import "NSObject.h"


@protocol CalcKeypadViewDelegate <NSObject>
-(void)touchUpOnKeypad:(id)keypad tag:(int)tag;
-(void)touchCancelledOnKeypad:(id)keypad;
-(void)touchDownOnKeypad:(id)keypad tag:(int)tag frame:(CGRect)frame playSound:(BOOL)sound;
@end
