/* AboutController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Preferences-Structs.h"

@class PSSpecifier, NSString, NSTimer, NSLock, NSMutableDictionary;
@protocol NSObject;

__attribute__((visibility("hidden")))
@interface AboutController : XXUnknownSuperclass {
	NSMutableDictionary* _mediaDict;
	NSMutableDictionary* _accessorySpecifiers;
	PSSpecifier* _headsetSpecifier;
	PSSpecifier* _accessoryDividerSpecifier;
	NSString* _loading;
	NSTimer* _reloadTimer;
	BOOL _isGeneratingNotifications;
	BOOL _threadRunning;
	BOOL _cancel;
	BOOL _loaded;
	BOOL _accessory;
	BOOL _firstViewDidAppear;
	int _carrierCellState;
	id<NSObject> _photoVideoNotificationToken;
	NSLock* _lock;
	NSString* _serviceProviderNameForSPN;
}
-(void)_availableWirelessAccessoryDidUpdate:(id)_availableWirelessAccessory;
-(void)_accessoryDidUpdate:(id)_accessory;
-(void)dealloc;
-(void)viewWillDisappear:(BOOL)view;
-(void)willResignActive;
-(void)willBecomeActive;
-(void)viewDidAppear:(BOOL)view;
-(id)init;
-(void)simStatusChangedToReady;
-(void)mediaLibraryDidChange:(id)mediaLibrary;
-(void)enableMLUpdates:(BOOL)updates;
-(void)forceReloadMediaStats:(id)stats;
-(void)cleanupTimer;
-(void)newCarrierNotification;
-(id)specifiers;
-(id)deviceName:(id)name;
-(void)setDeviceName:(id)name specifier:(id)specifier;
-(void)willUnlock;
-(id)_photos:(id)photos;
-(id)_videos:(id)videos;
-(id)_songs:(id)songs;
-(id)countForKey:(id)key;
-(void)_loadMediaFinished:(id)finished;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)updateCarrierSpecifier:(id)specifier;
-(id)_MINString:(id)string;
-(id)_NAIString:(id)string;
-(id)_ERIString:(id)string;
-(id)_PRLString:(id)string;
-(id)_getCTMobileEquipmentInfo:(CFStringRef)info;
-(id)_carrierVersion:(id)version;
-(id)_macAddress;
-(id)_bluetoothMACAddress;
-(id)valueForSpecifier:(id)specifier;
-(id)_myNumber;
-(void)_addKey:(id)key value:(id)value array:(id)array isCopyable:(BOOL)copyable;
@end
