/* GeneralController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PSSpecifier, NSTimer, NSDictionary, NSArray, TVOutManager, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface GeneralController : XXUnknownSuperclass {
	NSArray* _autoLockValues;
	NSDictionary* _autoLockTitleDictionary;
	NSMutableDictionary* _localizedAutoLockTitleDictionary;
	NSTimer* _usageTimer;
	TVOutManager* _tvOutManager;
	PSSpecifier* _tvOutSpecifier;
	PSSpecifier* _siriSpecifier;
}
-(void)handleURL:(id)url;
-(void)didUnlock;
-(void)didAcceptEnteredPIN:(id)pin;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)_localizeAutoLockTitles;
-(void)enableEdge:(id)edge;
-(id)EDGEEnabled:(id)enabled;
-(id)init;
-(void)profileNotification:(id)notification;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)setLocksAndUnlocksWithCase:(id)aCase specifier:(id)specifier;
-(id)locksAndUnlocksWithCase:(id)aCase;
-(id)parentalControlsEnabled:(id)enabled;
-(id)passcodeLockEnabled:(id)enabled;
-(void)dealloc;
-(void)updateAssistantSpecifiers;
-(id)specifiers;
-(void)_setUseSwitchForOrientationLockWithSpecifier:(id)specifier;
-(void)setScreenLock:(id)lock specifier:(id)specifier;
-(id)screenLock:(id)lock;
-(void)handleTVOutChange;
-(void)updateAutoLockSpecifier;
@end
