/* UnderlineButton.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Preferences-Structs.h"


__attribute__((visibility("hidden")))
@interface UnderlineButton : XXUnknownSuperclass {
	float _linePadding;
}
@property(assign, nonatomic) float linePadding;
-(void)drawRect:(CGRect)rect;
@end
