/* XXUnknownSuperclass.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (MapPluginExtras)
+(id)_map_plugin_colorWithHexString:(id)hexString alpha:(float)alpha;
-(id)initWithHexString:(id)hexString alpha:(float)alpha;
@end

@interface XXUnknownSuperclass (MapPluginExtras)
-(void)_map_plugin_webThreadCallWebScriptMethod:(id)method withArguments:(id)arguments;
@end
