/* GKGamesCompareBasicDataSource.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class GKPlayer, NSString;

__attribute__((visibility("hidden")))
@interface GKGamesCompareBasicDataSource : XXUnknownSuperclass {
	BOOL _listChanged;
	GKPlayer* _player;
	NSString* _localPlayerSeed;
	NSString* _playerSeed;
}
@property(assign, nonatomic) BOOL listChanged;
@property(retain, nonatomic) NSString* playerSeed;
@property(retain, nonatomic) NSString* localPlayerSeed;
@property(retain, nonatomic) GKPlayer* player;
+(id)gamesCompareBasicDataSourceWithPlayer:(id)player;
-(void)loadDataWithCompletionHandlerAndError:(id)completionHandlerAndError;
-(void)dealloc;
-(id)initWithPlayer:(id)player;
@end
