/* GKLocalPlayerProfileHeaderView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "GameCentre-Structs.h"
#import "GKPlayerProfileHeaderView.h"


__attribute__((visibility("hidden")))
@interface GKLocalPlayerProfileHeaderView : GKPlayerProfileHeaderView {
}
+(Class)statusViewClass;
-(void)updatePlayerPhoto;
-(void)updatePlayerStatus;
-(void)updatePlayerName;
-(void)didUpdateModel;
-(id)metrics;
@end
