/* GKScoreDetailViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "GKFriendRequestComposeViewControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class GKTextBubbleControl, GKLeaderboard, GKScore, NSArray, NSLayoutConstraint, UIImageView, GKLabel, GKHorizontalBubbleControlsView;

__attribute__((visibility("hidden")))
@interface GKScoreDetailViewController : XXUnknownSuperclass <GKFriendRequestComposeViewControllerDelegate> {
	BOOL _didFloatInBubbles;
	BOOL _didTransition;
	UIImageView* _iconView;
	GKLabel* _titleLabel;
	GKLabel* _descriptionLabel;
	GKLabel* _earnedOnLabel;
	GKHorizontalBubbleControlsView* _bubblesView;
	GKTextBubbleControl* _shareBubble;
	GKTextBubbleControl* _challengeBubble;
	GKTextBubbleControl* _requestBubble;
	GKLabel* _infoLabel;
	GKLeaderboard* _leaderboard;
	GKScore* _score;
	NSArray* _portraitConstraints;
	NSArray* _landscapeConstraints;
	NSLayoutConstraint* _topConstraint;
}
@property(assign, nonatomic) BOOL didTransition;
@property(assign, nonatomic) BOOL didFloatInBubbles;
@property(retain, nonatomic) NSLayoutConstraint* topConstraint;
@property(retain, nonatomic) NSArray* landscapeConstraints;
@property(retain, nonatomic) NSArray* portraitConstraints;
@property(retain, nonatomic) GKScore* score;
@property(retain, nonatomic) GKLeaderboard* leaderboard;
@property(retain, nonatomic) GKLabel* infoLabel;
@property(retain, nonatomic) GKTextBubbleControl* requestBubble;
@property(retain, nonatomic) GKTextBubbleControl* challengeBubble;
@property(retain, nonatomic) GKTextBubbleControl* shareBubble;
@property(retain, nonatomic) GKHorizontalBubbleControlsView* bubblesView;
@property(retain, nonatomic) GKLabel* earnedOnLabel;
@property(retain, nonatomic) GKLabel* descriptionLabel;
@property(retain, nonatomic) GKLabel* titleLabel;
@property(retain, nonatomic) UIImageView* iconView;
+(id)scoreDetailWithScore:(id)score leaderboard:(id)leaderboard;
-(void)pushLeftBubble;
-(void)pushRightBubble;
-(void)didTouchRequestBubble;
-(void)friendRequestComposeViewControllerDidFinish:(id)friendRequestComposeViewController;
-(void)didTouchShareBubble;
-(void)didTouchChallengeBubble;
-(void)animateOutBubbleWithFocus:(int)focus completion:(id)completion;
-(void)hideBubbles;
-(void)setupForReappear;
-(void)floatInBubbles;
-(void)viewWillAppear:(BOOL)view;
-(void)configureForScoreAndLeaderboard;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidAppear:(BOOL)view;
-(void)loadView;
-(id)player;
-(float)tabBarHeight;
-(float)navHeight;
-(void)dealloc;
-(id)initWithScore:(id)score leaderboard:(id)leaderboard;
@end
