/* UIStateRestoring.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIStateRestoring <NSObject>
@optional
@property(readonly, assign, nonatomic) Class objectRestorationClass;
@property(readonly, assign, nonatomic) id<UIStateRestoring> restorationParent;
-(void)applicationFinishedRestoringState;
-(void)decodeRestorableStateWithCoder:(id)coder;
-(void)encodeRestorableStateWithCoder:(id)coder;
@end
