/* NoteCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NotesUITableViewCell.h"
#import "MobileNotes-Structs.h"

@class UILabel, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface NoteCell : NotesUITableViewCell {
	UILabel* _titleLabel;
	UILabel* _dateLabel;
	NSDictionary* _titleAttributes;
	NSDictionary* _titleSearchAttributes;
	CGRect _lastFrame;
	NSString* _summary;
	BOOL _containsCJK;
	BOOL _useAlternateTextColor;
	BOOL _useLetterpress;
	int _letterpressStyle;
	BOOL _labelSupportsFastLetterpress;
}
@property(assign) BOOL useAlternateTextColor;
-(void).cxx_destruct;
-(id)_automationValue;
-(id)_automationID;
-(void)layoutSubviews;
-(void)hideDate:(BOOL)date;
-(void)setContainsCJK:(BOOL)cjk;
-(void)setSummary:(id)summary;
-(void)setDate:(id)date;
-(void)highlightSearchTerms:(id)terms;
-(void)setTitle:(id)title;
-(void)dealloc;
-(id)textAttributesForSearch:(BOOL)search;
-(void)updateLetterpressRendering;
-(void)updateSystemTextSize:(id)size;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)_dateTextColor:(BOOL)color;
-(id)_titleTextColor:(BOOL)color;
@end
