/* NotesFindViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UISearchBarDelegate.h"
#import "UIWebFindOnPageHighlighterDelegate.h"
#import "NotesFindOnPageHighlighterDelegate.h"
#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NotesFindOnPageHighlighter;
@protocol NotesFindViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface NotesFindViewController : XXUnknownSuperclass <UISearchBarDelegate, UIWebFindOnPageHighlighterDelegate, NotesFindOnPageHighlighterDelegate> {
	id<NotesFindViewControllerDelegate> _findDelegate;
	NotesFindOnPageHighlighter* _highlighter;
}
-(void).cxx_destruct;
-(void)findOnPageHighlighterDidClearMatches:(id)findOnPageHighlighter;
-(void)findOnPageHighlighterDidHighlightMatch:(id)findOnPageHighlighter;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(void)updateUI;
-(void)doneButtonTapped;
-(void)nextPreviousControlValueChanged:(id)changed;
-(void)keyboardDidHide;
-(void)stopFind:(BOOL)find;
-(void)resetSearch;
-(void)setSearchTerm:(id)term;
-(void)setDelegate:(id)delegate;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)loadView;
-(void)dealloc;
-(id)initWithContentLayer:(id)contentLayer;
@end
