/* NotesActivityViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NotesDisplayController;

__attribute__((visibility("hidden")))
@interface NotesActivityViewController : XXUnknownSuperclass {
	NotesDisplayController* _displayController;
}
@property(retain, nonatomic) NotesDisplayController* displayController;
-(void).cxx_destruct;
-(void)_prepareActivity:(id)activity;
-(BOOL)_shouldShowSystemActivity:(id)activity;
@end
