/* _MusicMiniPlayerActionTableViewCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface _MusicMiniPlayerActionTableViewCell : XXUnknownSuperclass {
	UIImageView* _actionImageView;
	UIView* _separatorView;
}
@property(assign, nonatomic) BOOL showsSeparator;
@property(retain, nonatomic) UIImage* actionImage;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
