/* _MusicMiniPlayerTouchGestureRecognizer.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIGestureRecognizerDelegatePrivate.h"
#import "Music-Structs.h"


__attribute__((visibility("hidden")))
@interface _MusicMiniPlayerTouchGestureRecognizer : XXUnknownSuperclass <UIGestureRecognizerDelegatePrivate> {
	CGPoint _touchBeganLocation;
}
-(CGPoint)touchBeganLocationInView:(id)view;
-(BOOL)_gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)reset;
-(void)dealloc;
-(id)initWithTarget:(id)target action:(SEL)action;
@end
