/* MPHCollectionTrackTableViewCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MPHSongTableViewCell.h"

@class NSString, UIView, UILabel;

__attribute__((visibility("hidden")))
@interface MPHCollectionTrackTableViewCell : MPHSongTableViewCell {
	UILabel* _durationLabel;
	UIView* _separatorView;
	UILabel* _subtitleLabel;
	UILabel* _titleLabel;
	UIView* _topSeparatorView;
	UILabel* _trackNumberLabel;
	float _maximumDurationWidth;
}
@property(copy, nonatomic) NSString* trackNumberText;
@property(copy, nonatomic) NSString* title;
@property(copy, nonatomic) NSString* subtitle;
@property(assign, nonatomic) float maximumDurationWidth;
@property(copy, nonatomic) NSString* durationText;
-(void).cxx_destruct;
-(void)setPlaying:(BOOL)playing;
-(void)setDisplayAsDisabled:(BOOL)disabled;
-(void)layoutSubviews;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
