/* MPHNowPlayingViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MPPlaybackControlsDelegate.h"
#import "MPHNowPlayingPlaybackControlsViewDelegate.h"
#import "MPTransportControlsTarget.h"
#import "RUStationActionsViewControllerDelegate.h"
#import "RUTrackDownloadViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIModalItemDelegate.h"

@class UIView, UIViewController, MPAVItem, UIActionSheet, RUStationActionsViewController, RUTrackActionsModalItem, MPHLyricsView, RUTrackDownloadView, MPHNowPlayingPlaybackControlsView;

__attribute__((visibility("hidden")))
@interface MPHNowPlayingViewController : XXUnknownSuperclass <MPHNowPlayingPlaybackControlsViewDelegate, MPPlaybackControlsDelegate, MPTransportControlsTarget, RUStationActionsViewControllerDelegate, RUTrackDownloadViewDelegate, UIActionSheetDelegate, UIModalItemDelegate> {
	UIView* _contentView;
	UIViewController* _contentViewController;
	UIView* _infoButtonContainerView;
	MPAVItem* _item;
	MPHLyricsView* _lyricsView;
	MPHNowPlayingPlaybackControlsView* _playbackControlsView;
	UIActionSheet* _repeatActionSheet;
	RUStationActionsViewController* _stationActionsViewController;
	BOOL _supportsCoverFlow;
	RUTrackActionsModalItem* _trackActionsModalItem;
	RUTrackDownloadView* _trackDownloadView;
	int _wantsVideoLayerCount;
}
-(void).cxx_destruct;
-(void)_updateForCurrentItemAnimated:(BOOL)currentItemAnimated;
-(void)_updateContentView:(id)view forItem:(id)item;
-(void)_startGeniusPlaylistFromCurrentItem;
-(BOOL)_shouldShowTransitionFromItem:(id)item toItem:(id)item2 isForwards:(BOOL*)forwards;
-(void)_scaleAndSetModalItemArtworkImageToCurrentArtworkImage;
-(void)_popIfNecessary;
-(void)_endWantingVideoLayer;
-(id)_createContentViewForItem:(id)item contentViewController:(id*)controller;
-(void)_cleanupForDeallocationContentView:(id)deallocationContentView contentViewController:(id)controller;
-(void)_beginWantingVideoLayer;
-(void)_addStationFromItem:(id)item usingArtist:(BOOL)artist;
-(void)_removeAdViewNotification:(id)notification;
-(void)_playbackContentsDidChangeNotification:(id)_playbackContents;
-(void)_mediaLibraryDisplayValuesDidChangeNotification:(id)_mediaLibraryDisplayValues;
-(void)_itemDidChangeNotification:(id)_item;
-(void)_tapAction:(id)action;
-(void)_infoButtonAction:(id)action;
-(void)_flipsideAction:(id)action;
-(void)_backBarButtonAction:(id)action;
-(void)modalItem:(id)item willDismissWithButtonIndex:(int)buttonIndex;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)trackDownloadViewWillTransition:(id)trackDownloadView;
-(void)stationActionsViewControllerDidFinish:(id)stationActionsViewController;
-(void)stationActionsViewController:(id)controller addStationForArtist:(BOOL)artist;
-(void)playbackControls:(id)controls didTapRadioNewStationFromItem:(id)item usingArtist:(BOOL)artist;
-(BOOL)transportControls:(id)controls tappedButtonPart:(unsigned long long)part;
-(unsigned)shuffleTypeForPlaybackControls:(id)playbackControls;
-(unsigned)repeatTypeForPlaybackControls:(id)playbackControls;
-(BOOL)playbackControlsDidTapGeniusButton:(id)playbackControls;
-(BOOL)playbackControls:(id)controls changedShuffleType:(unsigned)type;
-(BOOL)playbackControls:(id)controls changedRepeatType:(unsigned)type;
-(BOOL)controlsOverlay:(id)overlay shouldUseDetailScrubberForItem:(id)item;
-(unsigned)controlsOverlay:(id)overlay playbackSpeedForItem:(id)item;
-(void)controlsOverlayDidClickPlaybackSpeedButton:(id)controlsOverlay;
-(BOOL)music_supportsMiniPlayer;
-(BOOL)MPH_supportsCoverFlow;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
