/* MusicGeniusMixQueueFeeder.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MusicQueryQueueFeeder.h"

@protocol MusicGeniusMixQueueFeederDataSource;

__attribute__((visibility("hidden")))
@interface MusicGeniusMixQueueFeeder : MusicQueryQueueFeeder {
	unsigned _currentPlaylistOffset;
	id<MusicGeniusMixQueueFeederDataSource> _dataSource;
}
@property(retain, nonatomic) id<MusicGeniusMixQueueFeederDataSource> dataSource;
-(void).cxx_destruct;
-(BOOL)_configureWithMix:(id)mix playbackContext:(id)context startPlayback:(BOOL)playback;
-(void)shuffleItemsWithAnchor:(unsigned*)anchor;
-(id)mediaItemAtIndex:(unsigned)index;
-(unsigned)indexOfMediaItem:(id)mediaItem;
-(id)query;
-(BOOL)reloadWithDataSource:(id)dataSource keepPlayingCurrentItemIfPossible:(BOOL)possible;
-(unsigned)shuffleType;
-(unsigned)realRepeatType;
-(BOOL)userCanChangeShuffleAndRepeatType;
-(id)localizedPositionInPlaylistString:(id)playlistString;
-(id)localizedAttributedPositionInPlaylistStringForItem:(id)item withRegularTextAttributes:(id)regularTextAttributes emphasizedTextAttributes:(id)attributes;
-(void)restoreAVControllerPlaybackQueue:(id)queue fromUnarchiver:(id)unarchiver;
-(void)archiveAVControllerPlaybackQueue:(id)queue toArchiver:(id)archiver;
-(id)pathAtIndex:(unsigned)index;
-(unsigned)numberOfPaths;
-(unsigned)itemCount;
@end
