/* MusicArtistCellConfiguration.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MusicCellConfiguration.h"


__attribute__((visibility("hidden")))
@interface MusicArtistCellConfiguration : MusicCellConfiguration {
}
+(id)_imageCache;
+(void)_appDefaultsDidChangeNotification:(id)_appDefaults;
+(id)unknownTitleText;
+(id)titleProperty;
+(id)tableViewCellBackgroundColor;
+(id)tableViewBackgroundColor;
+(id)representativeItemTitleProperty;
+(id)representativeItemPersistentIDProperty;
+(id)propertiesToFetch;
+(id)persistentIDProperty;
+(id)itemPersistentIDProperty;
+(int)groupingType;
+(id)collectionPropertiesToFetch;
+(id)artworkCacheIDProperty;
+(id)artistArtworkCacheIDProperty;
+(float)tableViewCellHeight;
+(Class)tableViewCellClass;
+(void)configureCell:(id)cell forViewController:(id)viewController withEntity:(id)entity atIndex:(unsigned)index;
@end
