/* MusicTabBarControllerDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UITabBarControllerDelegate.h"


@protocol MusicTabBarControllerDelegate <UITabBarControllerDelegate>
@optional
-(void)music_tabBarController:(id)controller didSelectViewController:(id)controller2;
@end
