/* UIModalItemDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol UIModalItemDelegate <NSObject>
@optional
-(BOOL)modalItemShouldEnableFirstOtherButton:(id)modalItem;
-(void)modalItem:(id)item didDismissWithButtonIndex:(int)buttonIndex;
-(void)modalItem:(id)item willDismissWithButtonIndex:(int)buttonIndex;
-(void)didPresentModalItem:(id)item;
-(void)willPresentModalItem:(id)item;
@end
