/* GKChallengeDetailViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, GKLabel, GKChallenge, UIImageView, NSLayoutConstraint, GKHorizontalBubbleControlsView, GKTextBubbleControl, GKPlayerWithSpeechBalloonView;

__attribute__((visibility("hidden")))
@interface GKChallengeDetailViewController : XXUnknownSuperclass {
	BOOL _didFloatInBubbles;
	BOOL _didTransition;
	GKChallenge* _challenge;
	UIImageView* _iconView;
	GKLabel* _goalLabel;
	GKLabel* _fromLabel;
	GKPlayerWithSpeechBalloonView* _playerWithMessageView;
	GKHorizontalBubbleControlsView* _bubblesView;
	GKTextBubbleControl* _declineBubble;
	GKTextBubbleControl* _playBubble;
	GKLabel* _infoLabel;
	NSArray* _portraitConstraints;
	NSArray* _landscapeConstraints;
	NSLayoutConstraint* _topConstraint;
}
@property(assign, nonatomic) BOOL didTransition;
@property(assign, nonatomic) BOOL didFloatInBubbles;
@property(retain, nonatomic) NSLayoutConstraint* topConstraint;
@property(retain, nonatomic) NSArray* landscapeConstraints;
@property(retain, nonatomic) NSArray* portraitConstraints;
@property(retain, nonatomic) GKLabel* infoLabel;
@property(retain, nonatomic) GKTextBubbleControl* playBubble;
@property(retain, nonatomic) GKTextBubbleControl* declineBubble;
@property(retain, nonatomic) GKHorizontalBubbleControlsView* bubblesView;
@property(retain, nonatomic) GKPlayerWithSpeechBalloonView* playerWithMessageView;
@property(retain, nonatomic) GKLabel* fromLabel;
@property(retain, nonatomic) GKLabel* goalLabel;
@property(retain, nonatomic) UIImageView* iconView;
@property(retain, nonatomic) GKChallenge* challenge;
+(id)challengeDetailWithChallenge:(id)challenge;
-(void)pushLeftBubble;
-(void)pushRightBubble:(id)bubble;
-(void)buyButtonPressed:(id)pressed;
-(void)didTouchPlayBubbleInstalled;
-(void)didTouchDeclineBubble;
-(void)animateOutBubbleWithFocus:(int)focus completion:(id)completion;
-(void)hideBubbles;
-(void)viewWillAppear:(BOOL)view;
-(void)configurePlayBubble;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidAppear:(BOOL)view;
-(void)loadView;
-(float)tabBarHeight;
-(float)navHeight;
-(void)dealloc;
-(id)initWithChallenge:(id)challenge;
@end
