/* GKComposeRecipientAtom.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "GKAtomView.h"

@class GKComposeRecipient;
@protocol GKComposeRecipientAtomDelegate;

__attribute__((visibility("hidden")))
@interface GKComposeRecipientAtom : GKAtomView {
	GKComposeRecipient* _recipient;
	id<GKComposeRecipientAtomDelegate> _delegate;
}
@property(assign, nonatomic) id<GKComposeRecipientAtomDelegate> delegate;
@property(readonly, assign, nonatomic) GKComposeRecipient* recipient;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)dealloc;
-(id)initWithRecipient:(id)recipient;
@end
