/* GKComposePlayerRecipient.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "GKComposeRecipient.h"

@class GKPlayer;

__attribute__((visibility("hidden")))
@interface GKComposePlayerRecipient : GKComposeRecipient {
	GKPlayer* _player;
}
@property(retain, nonatomic) GKPlayer* player;
+(id)recipientWithPlayer:(id)player;
-(id)label;
-(id)displayString;
-(unsigned)addressType;
-(id)address;
-(id)description;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)initWithPlayer:(id)player;
@end
