/* SBAlertItemsSettings.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAlertItemsSettings : XXUnknownSuperclass {
	BOOL _disableBBHandlers;
	int _testItemToken;
}
@property(assign, nonatomic) int testItemToken;
@property(assign, nonatomic) BOOL disableBBHandlers;
+(id)newTestItemForToken:(int)token;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end
