/* SBAlertWindowViewController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIViewController, UIScreen, NSMutableSet, SBAlert, UIView;

__attribute__((visibility("hidden")))
@interface SBAlertWindowViewController : XXUnknownSuperclass {
	UIScreen* _screen;
	UIView* _contentView;
	SBAlert* _activeAlert;
	UIViewController* _activeViewController;
	NSMutableSet* _childAlerts;
}
@property(retain, nonatomic) UIViewController* activeViewController;
@property(retain, nonatomic) SBAlert* activeAlert;
-(void)window:(id)window willAnimateFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame3;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(BOOL)wantsFullScreenLayout;
-(void)noteAlertWindow:(id)window didDisplayAlert:(id)alert;
-(BOOL)alertWindow:(id)window canAnimateInAlert:(id)alert;
-(id)stackedViewForAlert:(id)alert;
-(id)stackedAlertsIncludingActiveAlert:(BOOL)alert;
-(int)stackedAlertCount;
-(void)removeAlertController:(id)controller;
-(void)addAlertController:(id)controller;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
-(id)initWithScreen:(id)screen;
@end
