/* SBAlertManager.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMapTable, SBAlertWindow, UIScreen, NSMutableArray;
@protocol SBAlertManagerDelegate;

__attribute__((visibility("hidden")))
@interface SBAlertManager : XXUnknownSuperclass {
	UIScreen* _screen;
	SBAlertWindow* _alertWindow;
	SBAlertWindow* _deferredAlertWindow;
	NSMutableArray* _alerts;
	NSMapTable* _observers;
	BOOL _deactivatingAllAlerts;
	id<SBAlertManagerDelegate> _delegate;
	struct {
		unsigned delegateOverrideRequester : 1;
		unsigned delegateShouldEnableContextHostingForRequester : 1;
	} _delegateFlags;
}
@property(assign, nonatomic) id<SBAlertManagerDelegate> delegate;
-(void)alertIsReadyToBeRemovedFromView:(id)view;
-(void)alertIsReadyToBeDeactivated:(id)beDeactivated;
-(void)_makeAlertWindowOpaque:(BOOL)opaque;
-(void)_resetAlertWindowOpacity;
-(void)_removeFromView:(id)view;
-(void)_deactivate:(id)deactivate;
-(void)_activate:(id)activate;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(id)debugDescription;
-(id)description;
-(void)applicationFinishedAnimatingBeneathAlert;
-(void)applicationWillAnimateActivation;
-(int)orientation;
-(void)deactivateAlertsAfterLaunch;
-(void)setAlertsShouldDeactivateAfterLaunch;
-(void)deactivateAll;
-(void)deactivate:(id)deactivate;
-(void)activate:(id)activate;
-(id)allAlerts;
-(BOOL)containsAlert:(id)alert;
-(id)stackedAlertsIncludingActiveAlert:(BOOL)alert;
-(BOOL)hasStackedAlerts;
-(id)activeAlert;
-(id)window;
-(id)screen;
-(void)dealloc;
-(id)init;
-(id)initWithScreen:(id)screen;
@end
