/* SBAnimationCurveSettings.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBAnimationCurveSettings : XXUnknownSuperclass {
	unsigned _curve;
	CGPoint _controlPoint1;
	CGPoint _controlPoint2;
}
@property(assign, nonatomic) CGPoint controlPoint2;
@property(assign, nonatomic) CGPoint controlPoint1;
@property(assign, nonatomic) unsigned curve;
+(id)_rowsRelativeToKeyPath:(id)keyPath;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end
