/* SBAppSliderSettings.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class _UIScreenEdgePanRecognizerSettings, SBAnimationSettings;

__attribute__((visibility("hidden")))
@interface SBAppSliderSettings : XXUnknownSuperclass {
	int _simplicityOptions;
	SBAnimationSettings* _dosidoAnimationSettings;
	_UIScreenEdgePanRecognizerSettings* _gestureSettings;
}
@property(retain) _UIScreenEdgePanRecognizerSettings* gestureSettings;
@property(retain) SBAnimationSettings* dosidoAnimationSettings;
@property(assign) int simplicityOptions;
+(id)settingsControllerModule;
-(BOOL)shouldSimplifyForOptions:(int)options;
-(void)setDefaultValues;
@end
