/* SBAppParallaxSettings.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBParallaxSettings, SBWallpaperParallaxSettings;

__attribute__((visibility("hidden")))
@interface SBAppParallaxSettings : XXUnknownSuperclass {
	SBWallpaperParallaxSettings* _lockscreenWallpaperSettings;
	SBWallpaperParallaxSettings* _homescreenWallpaperSettings;
	SBParallaxSettings* _iconSettings;
	SBParallaxSettings* _iconBadgeSettings;
}
@property(retain) SBParallaxSettings* iconBadgeSettings;
@property(retain) SBParallaxSettings* iconSettings;
@property(retain) SBWallpaperParallaxSettings* homescreenWallpaperSettings;
@property(retain) SBWallpaperParallaxSettings* lockscreenWallpaperSettings;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end
