/* SBAwayInCallController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSTimer, NSString, TPLegacyLCDView, TUCall;

__attribute__((visibility("hidden")))
@interface SBAwayInCallController : XXUnknownSuperclass {
	TPLegacyLCDView* _lcdView;
	BOOL _shouldShowInCallInfo;
	BOOL _isShowingInCallInfo;
	NSTimer* _durationTimer;
	NSString* _localizedLabel;
	UIImage* _callerImage;
	BOOL _isFullScreen;
	TUCall* _displayedCall;
}
@property(retain, nonatomic) TUCall* displayedCall;
-(void)_setShowingInCallInfo:(BOOL)callInfo;
-(BOOL)isShowingInCallInfo;
-(void)setShouldShowInCallInfo:(BOOL)showInCallInfo;
-(void)reload;
-(void)updateDuration;
-(void)fetchCallInformation:(id*)information name:(id*)name label:(id*)label image:(id*)image isFullScreen:(BOOL*)screen wantsHighResolution:(BOOL)resolution;
-(BOOL)callerImageIsFullScreen;
-(id)callerImage;
-(void)dealloc;
-(id)initWithLCDView:(id)lcdview;
@end
