/* SBBackgroundFetchTask.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BKSProcessAssertion, NSString;

__attribute__((visibility("hidden")))
@interface SBBackgroundFetchTask : XXUnknownSuperclass {
	BKSProcessAssertion* _assertion;
	id _completionHandler;
	NSString* _bundleID;
	unsigned _trigger;
	int _sequenceNumber;
}
@property(readonly, assign) int sequenceNumber;
@property(readonly, assign) unsigned trigger;
@property(readonly, assign, nonatomic) NSString* bundleID;
@property(copy, nonatomic) id completionHandler;
@property(retain, nonatomic) BKSProcessAssertion* assertion;
-(id)description;
-(void)dealloc;
-(void)_fireCompletionHandlerWithResult:(unsigned)result;
-(void)finishWithResult:(unsigned)result;
-(id)initForApplication:(id)application trigger:(unsigned)trigger sequenceNumber:(int)number withCompletion:(id)completion;
@end
