/* SBBBWidgetSectionInfo.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBBBSectionInfo.h"

@class SBBBWidgetBulletinInfo;

__attribute__((visibility("hidden")))
@interface SBBBWidgetSectionInfo : SBBBSectionInfo {
	SBBBWidgetBulletinInfo* _widgetBulletinInfo;
}
@property(retain, nonatomic) SBBBWidgetBulletinInfo* widgetBulletinInfo;
-(BOOL)isWidgetSection;
-(id)identifier;
-(void)dealloc;
@end
