/* SBBulletinObserverViewController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BBObserverDelegate.h"
#import "SBBulletinViewControllerDelegate.h"
#import "SBNotificationCenterWidgetHost.h"
#import "SpringBoard-Structs.h"
#import "SBWidgetViewControllerHostDelegate.h"

@class BBObserver, NSMutableArray, SBBulletinViewController, NSMutableDictionary, NSArray;
@protocol SBBulletinActionHandler;

__attribute__((visibility("hidden")))
@interface SBBulletinObserverViewController : XXUnknownSuperclass <BBObserverDelegate, SBBulletinViewControllerDelegate, SBWidgetViewControllerHostDelegate, SBNotificationCenterWidgetHost> {
	BBObserver* _observer;
	id _delegate;
	id<SBWidgetViewControllerHostDelegate> _widgetDelegate;
	NSMutableArray* _requestQueue;
	NSMutableDictionary* _enabledSectionInfosByID;
	NSMutableArray* _visibleSectionIDs;
	NSMutableDictionary* _bulletinIDsByFeed;
	SBBulletinViewController* _bulletinViewController;
	int _sectionOrderRule;
	int _supportedCategory;
	NSArray* _sectionOrder;
	NSMutableArray* _makeshiftSectionOrder;
	struct {
		unsigned shouldPushUpdatesToView : 1;
		unsigned isRequestHandlingEnabled : 1;
		unsigned isServerConnected : 1;
		unsigned isViewVisible : 1;
	} _bulletinObserverViewControllerFlags;
}
@property(assign, nonatomic) id<SBWidgetViewControllerHostDelegate> widgetDelegate;
@property(assign, nonatomic, getter=isRequestHandlingEnabled) BOOL requestHandlingEnabled;
@property(retain, nonatomic) SBBulletinViewController* bulletinViewController;
@property(readonly, assign, nonatomic) int supportedCategory;
@property(assign, nonatomic) id<SBBulletinActionHandler> delegate;
+(id)allCategories;
-(void)hostDidDismiss;
-(void)hostWillDismiss;
-(void)hostDidPresent;
-(void)hostWillPresent;
-(void)_invokeBlockWithAllWidgets:(id)allWidgets;
-(void)widget:(id)widget didUpdatePreferredSize:(CGSize)size;
-(void)widget:(id)widget requestsPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context completion:(id)completion;
-(void)widget:(id)widget requestsLaunchOfURL:(id)url;
-(void)observer:(id)observer noteServerConnectionStateChanged:(BOOL)changed;
-(void)observer:(id)observer noteInvalidatedBulletinIDs:(id)ids;
-(CGSize)observer:(id)observer composedAttachmentSizeForType:(int)type thumbnailWidth:(float)width height:(float)height key:(id)key;
-(id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
-(id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)observer;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(void)observer:(id)observer updateSectionInfo:(id)info inCategory:(int)category;
-(void)observer:(id)observer updateSectionOrder:(id)order forCategory:(int)category;
-(void)observer:(id)observer updateSectionOrderRule:(int)rule;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer modifyBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)_clearQueues;
-(void)_enqueueInQueue:(id)queue orProcessRequest:(id)request;
-(BOOL)_canEnqueueRequestsInQueue:(id)queue;
-(void)_dequeueAndProcessItemsInQueues;
-(BOOL)_dequeueAndProcessNextItemInQueues;
-(BOOL)_dequeueAndProcessNextItemInQueue:(id)queue;
-(BOOL)_canProcessRequestsInQueue:(id)queue;
-(BOOL)_isServerConnected;
-(void)_updateSection:(id)section forCategory:(int)category;
-(void)_setSectionOrder:(id)order forCategory:(int)category;
-(void)_setSectionOrderRule:(int)rule;
-(void)_sortAndCommitReloadOfSectionsInCategory:(int)category;
-(void)_sortVisibleSectionsForCategory:(int)category;
-(void)clearSection:(id)section;
-(void)removeAndDisableSection:(id)section;
-(void)removeSection:(id)section;
-(void)addSection:(id)section inCategory:(int)category;
-(void)_addSection:(id)section toCategory:(int)category widget:(id)widget;
-(void)_setSection:(id)section enabled:(BOOL)enabled;
-(void)_loadSection:(id)section;
-(void)_insertSectionIfNecessary:(id)necessary commit:(BOOL)commit;
-(void)_updateMakeshiftSectionOrderIfNecessary:(id)necessary;
-(id)_bulletinAfterBulletin:(id)bulletin inSection:(id)section;
-(id)firstSection;
-(id)sectionAfterSection:(id)section;
-(id)sectionWithIdentifier:(id)identifier;
-(id)_enabledSectionWithIdentifier:(id)identifier;
-(unsigned)_indexOfSectionWithIdentifier:(id)identifier;
-(id)sectionIdentifierAtIndex:(unsigned)index;
-(unsigned)_numberOfVisibleSections;
-(unsigned)indexOfBulletin:(id)bulletin inSection:(id)section;
-(id)_bulletinWithIdentifier:(id)identifier inSection:(id)section;
-(id)bulletinAtIndex:(unsigned)index inSection:(id)section;
-(unsigned)_numberOfBulletinsInSection:(id)section;
-(void)replaceBulletin:(id)bulletin inSection:(id)section;
-(void)removeBulletin:(id)bulletin fromSection:(id)section;
-(void)addBulletin:(id)bulletin toSection:(id)section forFeed:(unsigned)feed;
-(void)_setSection:(id)section visible:(BOOL)visible;
-(BOOL)_isSectionVisible:(id)visible;
-(BOOL)_isBulletin:(id)bulletin associatedWithSection:(id)section;
-(void)_disassociateBulletin:(id)bulletin fromSection:(id)section;
-(id)_reassociateBulletin:(id)bulletin withSection:(id)section;
-(void)_associateBulletin:(id)bulletin withSection:(id)section forFeed:(unsigned)feed;
-(unsigned)_feedsForBulletinID:(id)bulletinID;
-(void)_removeBulletinIDFromAllFeeds:(id)allFeeds;
-(void)_addBulletinID:(id)anId toSetForFeeds:(unsigned)feeds;
-(void)_addBulletinID:(id)anId toSetForFeed:(unsigned)feed;
-(id)infoForSection:(id)section;
-(id)infoForWidgetSection:(id)widgetSection;
-(id)infoForBulletinSection:(id)bulletinSection;
-(id)infoForWidget:(id)widget inSection:(id)section;
-(id)infoForBulletin:(id)bulletin inSection:(id)section;
-(id)_widgetForSection:(id)section inCategory:(int)category;
-(int)widgetIdiomForCategory:(int)category;
-(void)pushUpdatesAgainForFeeds:(unsigned)feeds;
-(void)pushUpdatesAgainForSectionWithIdentifier:(id)identifier feeds:(unsigned)feeds;
-(void)updateSection:(id)section withInfo:(id)info;
-(void)commitMoveOfBulletin:(id)bulletin inSection:(id)section beforeBulletin:(id)bulletin3 inSection:(id)section4;
-(void)commitReplacementWithBulletin:(id)bulletin ofBulletin:(id)bulletin2 inSection:(id)section;
-(void)commitRemovalOfBulletin:(id)bulletin fromSection:(id)section;
-(void)commitInsertionOfBulletin:(id)bulletin beforeBulletin:(id)bulletin2 inSection:(id)section forFeed:(unsigned)feed;
-(void)commitReloadOfSections:(id)sections;
-(void)commitReplacementWithSection:(id)section ofSection:(id)section2;
-(void)commitMoveOfSection:(id)section beforeSection:(id)section2;
-(void)commitRemovalOfSection:(id)section;
-(void)commitInsertionOfSection:(id)section beforeSection:(id)section2;
-(BOOL)bulletinViewController:(id)controller didSelectBulletin:(id)bulletin inSection:(id)section;
-(BOOL)bulletinViewController:(id)controller shouldHighlightBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller replacementAnimationForBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller removalAnimationForBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller insertionAnimationForBulletin:(id)bulletin inSection:(id)section;
-(void)viewWillLayoutSubviews;
-(UIEdgeInsets)bulletinViewControllerContentInsetsForMode:(int)mode;
-(int)layoutMode;
-(id)_contentView;
-(void)viewDidLoad;
-(void)loadView;
-(void)_insertBulletinViewControllerView;
-(void)_setShouldPushUpdatesToView:(BOOL)_set;
-(BOOL)_shouldPushUpdatesToView;
-(id)surrenderBulletinViewController;
-(id)observer;
-(void)dealloc;
-(id)initWithObserverFeed:(unsigned)observerFeed;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
