/* SBBulletinViewControllerDelegate.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBBulletinViewControllerDelegate <NSObject>
@optional
-(BOOL)bulletinViewController:(id)controller didSelectBulletin:(id)bulletin inSection:(id)section;
-(BOOL)bulletinViewController:(id)controller shouldHighlightBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller replacementAnimationForBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller removalAnimationForBulletin:(id)bulletin inSection:(id)section;
-(int)bulletinViewController:(id)controller insertionAnimationForBulletin:(id)bulletin inSection:(id)section;
@end
