/* SBCCMediaControlsSectionController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBControlCenterSectionViewController.h"
#import "SpringBoard-Structs.h"

@class MPUSystemMediaControlsViewController;

__attribute__((visibility("hidden")))
@interface SBCCMediaControlsSectionController : SBControlCenterSectionViewController {
	MPUSystemMediaControlsViewController* _systemMediaViewController;
}
-(void)viewDidLoad;
-(CGSize)contentSizeForOrientation:(int)orientation;
-(id)sectionIdentifier;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
