/* SBCenterIconZoomAnimator.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListLayoutDelegate.h"
#import "SBIconZoomAnimator.h"

@class SBCenterZoomSettings, UIView;

__attribute__((visibility("hidden")))
@interface SBCenterIconZoomAnimator : SBIconZoomAnimator <SBIconListLayoutDelegate> {
	UIView* _zoomView;
	float _iconZoomedZ;
	float _centerRow;
	float _centerCol;
	CGPoint _cameraPosition;
}
@property(readonly, assign, nonatomic) CGPoint cameraPosition;
@property(readonly, assign, nonatomic) UIView* zoomView;
@property(retain, nonatomic) SBCenterZoomSettings* zoomSettings;
-(void)_calculateCentersAndCameraPosition;
-(id)_animationFactoryForDock;
-(id)_animationFactoryForIcon:(id)icon;
-(void)_positionView:(id)view forIcon:(id)icon;
-(void)iconListViewLayoutInvalidated:(id)invalidated;
-(void)iconListView:(id)view wouldHaveMovedIcon:(id)icon;
-(double)_iconZoomDelay;
-(void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupZoom;
-(void)_setZoomFraction:(float)fraction;
-(void)_prepareZoom;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController;
@end
