/* SBCompassRecalibrationController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBCompassRecalibrationController : XXUnknownSuperclass {
	NSMutableArray* _assertionPorts;
}
+(id)sharedInstance;
-(void)_clientInvalidated:(CFMachPortRef)invalidated;
-(void)clientRequestedCompassHUD:(unsigned)hud;
-(void)removeHUD;
-(void)showHUD;
-(BOOL)isCompassCalibrationHUDVisible;
-(void)dealloc;
@end
