/* SBFolderIconZoomAnimator.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBScaleIconZoomAnimator.h"

@class _SBInnerFolderIconZoomAnimator, SBFolderIcon, SBFolderIconView, SBFolderZoomSettings, SBFloatyFolderView, SBFolderController;

__attribute__((visibility("hidden")))
@interface SBFolderIconZoomAnimator : SBScaleIconZoomAnimator {
	SBFolderController* _innerFolderController;
	SBFloatyFolderView* _innerFolderView;
	_SBInnerFolderIconZoomAnimator* _innerZoomAnimator;
}
@property(readonly, assign, nonatomic) SBFolderIconView* targetIconView;
@property(readonly, assign, nonatomic) SBFolderIcon* targetIcon;
@property(retain, nonatomic) SBFolderZoomSettings* zoomSettings;
-(CGRect)_zoomedFrame;
-(void)_animateToZoomFraction:(float)zoomFraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupZoom;
-(void)_setZoomFraction:(float)fraction;
-(void)_prepareZoom;
-(void)dealloc;
-(id)initWithOuterController:(id)outerController innerController:(id)controller folderIcon:(id)icon;
@end
