/* SBLockScreenModalAlertView.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIAlertView;

__attribute__((visibility("hidden")))
@interface SBLockScreenModalAlertView : XXUnknownSuperclass {
	UIAlertView* _alertView;
}
-(void)layoutSubviews;
-(void)removeAlertView;
-(BOOL)replaceAlertView:(id)view withAlertView:(id)alertView;
-(void)showAlertView:(id)view;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
