/* SBLockScreenNotificationBannerItem.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBDefaultBannerViewSource.h"
#import "SBUIQuietModePlayability.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAwayListItem;
@protocol SBUnlockActionHandler, SBLockScreenNotificationBannerItemDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenNotificationBannerItem : XXUnknownSuperclass <SBDefaultBannerViewSource, SBUIQuietModePlayability> {
	SBAwayListItem* _listItem;
	id<SBUnlockActionHandler> _unlockActionHandler;
	id<SBLockScreenNotificationBannerItemDelegate> _delegate;
}
@property(assign, nonatomic) id<SBLockScreenNotificationBannerItemDelegate> delegate;
@property(retain, nonatomic) id<SBUnlockActionHandler> unlockActionHandler;
@property(readonly, assign, nonatomic) SBAwayListItem* listItem;
-(id)unlockActionContext;
-(BOOL)overridesQuietMode;
-(BOOL)isCritical;
-(BOOL)inertWhenLocked;
-(BOOL)isVIP;
-(id)attachmentImage;
-(id)attachmentText;
-(id)iconImage;
-(id)sourceDate;
-(id)message;
-(id)title;
-(id)sortDate;
-(BOOL)canShowWhileLocked;
-(id)action;
-(void)dealloc;
-(id)initWithListItem:(id)listItem;
@end
