/* SBLockScreenTemperatureWarningViewController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBLockOverlayViewController.h"

@class NSString, SBLockScreenTemperatureWarningView;

__attribute__((visibility("hidden")))
@interface SBLockScreenTemperatureWarningViewController : XXUnknownSuperclass <SBLockOverlayViewController> {
	SBLockScreenTemperatureWarningView* _warningView;
}
@property(readonly, assign, nonatomic) NSString* slideToUnlockText;
-(id)overlayView;
-(void)loadView;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
