/* SBLockScreenBatteryChargingViewController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBLockScreenBatteryChargingView, NSTimer;
@protocol SBLockScreenBatteryChargingViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBLockScreenBatteryChargingViewController : XXUnknownSuperclass {
	SBLockScreenBatteryChargingView* _chargingView;
	NSTimer* _visibilityTimer;
	id<SBLockScreenBatteryChargingViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBLockScreenBatteryChargingViewControllerDelegate> delegate;
-(void)_visibilityTimerFired:(id)fired;
-(void)updateChargingStatusWithBatteryVisible:(BOOL)batteryVisible;
-(BOOL)batteryVisible;
-(void)_clearVisibilityTimer;
-(void)prepareForDismissal;
-(void)loadView;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
