/* SBNewsstandApplicationIcon.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBUserInstalledApplicationIcon.h"

@class SBNewsstandApplication;

__attribute__((visibility("hidden")))
@interface SBNewsstandApplicationIcon : SBUserInstalledApplicationIcon {
	SBNewsstandApplication* _fakeApp;
}
@property(retain, nonatomic) SBNewsstandApplication* fakeApp;
-(id)getGenericIconImage:(int)image;
-(BOOL)iconAppearsInNewsstand;
-(BOOL)isNewsstandApplicationIcon;
-(int)iconFormatForLocation:(int)location;
-(void)launch:(int)launch;
-(BOOL)launchEnabled;
-(id)application;
-(BOOL)shouldWarmUp;
-(void)dealloc;
-(id)initWithApplication:(id)application;
-(Class)iconImageViewClassForLocation:(int)location;
-(Class)iconViewClassForLocation:(int)location;
@end
