/* SBPowerDownView.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBPowerDownViewInterface.h"
#import "SpringBoard-Structs.h"
#import "SBAlertView.h"

@class SBGlintyStringView, NSTimer, UIPanGestureRecognizer, UILabel, _UIBackdropView, SBFakeStatusBarView, UIView;
@protocol SBPowerDownViewDelegate;

__attribute__((visibility("hidden")))
@interface SBPowerDownView : SBAlertView <SBPowerDownViewInterface> {
	NSTimer* _autoDismissTimer;
	id<SBPowerDownViewDelegate> _delegate;
	SBFakeStatusBarView* _fakeStatusBarView;
	UIView* _dynamicDarkeningAboveTopBar;
	UIView* _dynamicDarkeningBelowBottomBar;
	UIView* _darkeningUnderlay;
	UIView* _topContainer;
	UIView* _topBar;
	SBGlintyStringView* _topBarLabel;
	_UIBackdropView* _topBarBackground;
	UIView* _bottomContainer;
	UIView* _bottomBar;
	UILabel* _bottomBarLabel;
	_UIBackdropView* _bottomBarBackground;
	BOOL _addedFakeStatusBar;
	UIPanGestureRecognizer* _slideGestureRecognizer;
	CGPoint _slideGestureInitialPoint;
}
@property(assign, nonatomic) id<SBPowerDownViewDelegate> delegate;
-(void)_animatePowerDown;
-(void)_slideCompleted:(BOOL)completed;
-(void)_notifyDelegateCancelled;
-(void)_notifyDelegatePowerDown;
-(void)_resetAutoDismissTimer;
-(void)_cancelAutoDismissTimer;
-(id)_newDarkeningView:(CGRect)view;
-(CGRect)_frameForInnerDarkening;
-(void)_removeFakeStatusBarIfNecessary;
-(void)_addFakeStatusBarIfNecessary;
-(void)_slideGestureRecognizer:(id)recognizer;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isSupportedInterfaceOrientation:(int)orientation;
-(void)animateOut;
-(void)animateIn;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
