/* SBRootSettings.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBControlCenterSettings, SBFadeAnimationSettings, SBFolderSettings, SBAppParallaxSettings, SBAlertItemsSettings, SBLockScreenSettings, SBAppSliderSettings, SBLockScreenTestPluginSettings, SBNotificationCenterSettings, SBCarDisplaySettings, SBDockSettings, SBRootZoomSettings, SBCloseBoxSettings;

__attribute__((visibility("hidden")))
@interface SBRootSettings : XXUnknownSuperclass {
	BOOL _preventLockover;
	BOOL _slowSpringAnimations;
	SBAppParallaxSettings* _parallaxSettings;
	SBDockSettings* _dockSettings;
	SBFolderSettings* _folderSettings;
	SBRootZoomSettings* _rootZoomSettings;
	SBControlCenterSettings* _controlCenterSettings;
	SBAppSliderSettings* _appSliderSettings;
	SBLockScreenSettings* _lockScreenSettings;
	SBCarDisplaySettings* _carDisplaySettings;
	SBLockScreenTestPluginSettings* _lockScreenTestPluginSettings;
	SBCloseBoxSettings* _closeBoxSettings;
	SBFadeAnimationSettings* _fadeAnimationSettings;
	SBAlertItemsSettings* _alertItemsSettings;
	SBNotificationCenterSettings* _notificationCenterSettings;
}
@property(assign) BOOL slowSpringAnimations;
@property(assign) BOOL preventLockover;
@property(retain) SBNotificationCenterSettings* notificationCenterSettings;
@property(retain) SBAlertItemsSettings* alertItemsSettings;
@property(retain) SBFadeAnimationSettings* fadeAnimationSettings;
@property(retain) SBCloseBoxSettings* closeBoxSettings;
@property(retain) SBLockScreenTestPluginSettings* lockScreenTestPluginSettings;
@property(retain) SBCarDisplaySettings* carDisplaySettings;
@property(retain) SBLockScreenSettings* lockScreenSettings;
@property(retain) SBAppSliderSettings* appSliderSettings;
@property(retain) SBControlCenterSettings* controlCenterSettings;
@property(retain) SBRootZoomSettings* rootZoomSettings;
@property(retain) SBFolderSettings* folderSettings;
@property(retain) SBDockSettings* dockSettings;
@property(retain) SBAppParallaxSettings* parallaxSettings;
+(id)settingsControllerModule;
@end
