/* SBShimmerLabel.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@protocol SBShimmerLabelDelegate;

__attribute__((visibility("hidden")))
@interface SBShimmerLabel : XXUnknownSuperclass {
	BOOL _animationRepeats;
	id<SBShimmerLabelDelegate> _delegate;
	BOOL _isAnimating;
}
@property(assign) BOOL isAnimating;
@property(assign, nonatomic) id<SBShimmerLabelDelegate> delegate;
-(CGSize)_maskSize;
-(id)_maskLayer;
-(CGPoint)_maskEndingPosition;
-(CGPoint)_maskStartingPosition;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)animationDidStart:(id)animation;
-(id)_maskAnimation;
-(void)setAnimationRepeats:(BOOL)repeats;
-(void)startAnimating;
-(void)stopAnimating;
-(id)initWithFrame:(CGRect)frame;
@end
