/* SBStarkImpersonatedAppToAppWorkspaceTransaction.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStarkAppToAppWorkspaceTransaction.h"

@class SBAlert;

__attribute__((visibility("hidden")))
@interface SBStarkImpersonatedAppToAppWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction {
	SBAlert* _deactivatingAlert;
	BOOL _animatedAppActivation;
}
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(void)_deactivateAlertIfPossible;
-(void)_handleFailureToLaunch;
-(BOOL)selfStarkAlertDidDeactivate:(id)selfStarkAlert;
-(BOOL)selfStarkAlertWillDeactivate:(id)selfStarkAlert;
-(BOOL)selfApplicationExited:(id)exited;
-(BOOL)selfApplicationLaunchDidFail:(id)selfApplicationLaunch;
-(id)_newAnimationFromLauncherToApp;
-(id)_newAnimationFromAppToLauncher;
-(id)_newAnimationFromAppToApp;
-(void)_transactionComplete;
-(int)_setupMilestonesFrom:(id)from to:(id)to;
-(void)_doCommit;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller from:(id)from to:(id)to;
@end
