/* SBStarkLauncherLayoutAttributes.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBStarkLauncherLayoutAttributes : XXUnknownSuperclass {
	BOOL _lastIcon;
}
@property(assign, nonatomic, getter=isLastIcon) BOOL lastIcon;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(id)copyWithZone:(NSZone*)zone;
@end
