/* SBStarkBannerTarget.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIBannerTarget.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBUIBannerContext, NSHashTable, SBUISound, NSMutableArray;
@protocol SBStarkBannerTargetObserver;

__attribute__((visibility("hidden")))
@interface SBStarkBannerTarget : XXUnknownSuperclass <SBUIBannerTarget> {
	id<SBStarkBannerTargetObserver> _observer;
	NSHashTable* _sources;
	BOOL _invalidated;
	NSMutableArray* _pendedContexts;
	SBUIBannerContext* _currentContext;
	SBUISound* _currentSound;
	int _displayAssertions;
	BOOL _suspended;
	BOOL _suspendedForAssistant;
}
@property(readonly, assign, nonatomic) int bannerTargetIdiom;
@property(readonly, assign, nonatomic) SBUIBannerContext* currentContext;
@property(assign, nonatomic, getter=isSuspendedForAssistant) BOOL suspendedForAssistant;
@property(assign, nonatomic, getter=isSuspended) BOOL suspended;
@property(assign, nonatomic, getter=isPausedForUserInteraction) BOOL pausedForUserInteraction;
@property(assign, nonatomic) id<SBStarkBannerTargetObserver> observer;
-(void)dismissCurrentBannerContextForSource:(id)source;
-(id)currentBannerContextForSource:(id)source;
-(void)signalSource:(id)source;
-(void)unregisterSource:(id)source;
-(void)registerSource:(id)source;
-(void)_killIntervalElapsed:(id)elapsed;
-(void)_dismissIntervalElapsed:(id)elapsed;
-(void)_replaceIntervalElapsed:(id)elapsed;
-(void)_dismissContext:(id)context withOptions:(int)options dismissReason:(int)reason;
-(void)_dequeueWithOptions:(int)options dismissReason:(int)reason;
-(BOOL)_canDequeueWithOptions:(int)options;
-(BOOL)_canDismissWithOptions:(int)options;
-(void)invalidate;
-(void)noteContextCanceled:(id)canceled;
-(void)noteContext:(id)context subActionSelected:(unsigned)selected;
-(void)noteContextSelected:(id)selected;
-(void)dealloc;
-(id)init;
@end
