/* SBStarkStatusBarStateProvider.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBStatusBarStateProvider.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBStarkStatusBarStateProvider : SBStatusBarStateProvider {
}
+(BOOL)_itemIsIgnored:(int)ignored;
-(void)_composePostDataFromAggregatorData:(XXStruct_qJXVGC*)aggregatorData;
-(BOOL)_shouldPostForVisitedItem:(int)visitedItem withUpdates:(BOOL)updates toAggregatorData:(const XXStruct_qJXVGC*)aggregatorData;
@end
