/* SBStarkWorkspaceTransaction.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWorkspaceTransaction.h"
#import "SBAlertManagerObserver.h"

@class SBAlertManager, SBStarkScreenController;

__attribute__((visibility("hidden")))
@interface SBStarkWorkspaceTransaction : SBWorkspaceTransaction <SBAlertManagerObserver> {
	SBStarkScreenController* _starkScreenController;
	SBAlertManager* _starkScreenAlertManager;
	SBAlertManager* _mainScreenAlertManager;
}
@property(readonly, assign, nonatomic) SBAlertManager* starkScreenAlertManager;
@property(readonly, assign, nonatomic) SBStarkScreenController* starkScreenController;
@property(readonly, assign, nonatomic) SBAlertManager* mainScreenAlertManager;
-(void)alertManager:(id)manager didDeactivateAlert:(id)alert top:(BOOL)top;
-(void)alertManager:(id)manager willDeactivateAlert:(id)alert top:(BOOL)top;
-(void)alertManager:(id)manager didActivateAlert:(id)alert overAlerts:(id)alerts;
-(void)alertManager:(id)manager willActivateAlert:(id)alert overAlerts:(id)alerts;
-(BOOL)selfStarkAlertDidDeactivate:(id)selfStarkAlert;
-(BOOL)selfStarkAlertWillDeactivate:(id)selfStarkAlert;
-(BOOL)selfStarkAlertDidActivate:(id)selfStarkAlert overAlerts:(id)alerts;
-(BOOL)selfStarkAlertWillActivate:(id)selfStarkAlert overAlerts:(id)alerts;
-(void)dealloc;
-(id)initWithWorkspace:(id)workspace mainScreenAlertManager:(id)manager starkScreenController:(id)controller;
@end
