/* SBStarkFakeIconOperationController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SBStarkFakeIconOperationController : XXUnknownSuperclass {
	NSMutableDictionary* _launchOperationForDisplayIDMap;
}
-(void)addLaunchOperation:(id)operation withDisplayID:(id)displayID;
-(BOOL)performOperationForFakeIconWithDisplayID:(id)displayID;
-(void)dealloc;
-(id)init;
@end
