/* SBStarkKnobLauncherCell.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBIconObserver.h"
#import "SpringBoard-Structs.h"

@class UIView, SBIcon;
@protocol SBStarkKnobLauncherCellDelegate, SBIconAccessoryView;

__attribute__((visibility("hidden")))
@interface SBStarkKnobLauncherCell : XXUnknownSuperclass <SBIconObserver> {
	SBIcon* _icon;
	UIView<SBIconAccessoryView>* _accessoryView;
	BOOL _showsDisclosureIndicator;
	id<SBStarkKnobLauncherCellDelegate> _delegate;
}
@property(assign, nonatomic) id<SBStarkKnobLauncherCellDelegate> delegate;
@property(assign, nonatomic) BOOL showsDisclosureIndicator;
@property(retain, nonatomic) SBIcon* icon;
-(void)iconAccessoriesDidUpdate:(id)iconAccessories;
-(void)iconImageDidUpdate:(id)iconImage;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)prepareForReuse;
-(void)layoutSubviews;
-(CGRect)_accessoryFrameInBounds:(CGRect)bounds;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
