/* SBUIStarkStaticAnimationController.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkScreenAnimationController.h"

@class UIView, SBApplication;

__attribute__((visibility("hidden")))
@interface SBUIStarkStaticAnimationController : SBUIStarkScreenAnimationController {
	BOOL _relaunchExpected;
	BOOL _awaitingKeybagRefetch;
	BOOL _appWasActivating;
	UIView* _staticAppView;
}
@property(readonly, assign, nonatomic) SBApplication* app;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(BOOL)_shouldDismissBanner;
-(void)_prepareAnimation;
-(BOOL)_animationShouldStart;
-(BOOL)_willAnimate;
-(void)dealloc;
-(id)initWithApp:(id)app starkScreenController:(id)controller;
@end
