/* SBUIAnimationAlertToAppZoomIn.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class UIView, SBAlert;

__attribute__((visibility("hidden")))
@interface SBUIAnimationAlertToAppZoomIn : SBUIMainScreenAnimationController {
	SBAlert* _fromAlert;
	UIView* _viewToAnimate;
	UIView* _contextHostView;
	int _launchingOrientation;
	BOOL _needsFakeStatusBar;
	BOOL _requiresHostView;
	BOOL _activateBeforeHosting;
	BOOL _fromAssistant;
	BOOL _finishedZooming;
	float _previousStatusBarWindowLevel;
}
-(void)_setupFakeStatusBarIfNecessary;
-(void)_maybeReportAnimationFinished;
-(void)_finishedZooming;
-(BOOL)_isApplicationLaunchFinished;
-(void)_applicationDependencyStateChanged;
-(void)_cleanupAnimation;
-(void)_doAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(id)_animationProgressDependency;
-(BOOL)_animationShouldStart;
-(void)_setHidden:(BOOL)hidden;
-(BOOL)_shouldDismissBanner;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp fromAlert:(id)alert;
-(id)_getTransitionWindow;
@end
