/* SBUIAnimationZoomUpAppFromPhone.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIAnimationZoomUpApp.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromPhone : SBUIAnimationZoomUpApp {
}
-(void)_cleanupAnimation;
-(void)_prepareAnimation;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(XXStruct_UhFvxB)fakeStatusBarInfoWithStartStyle:(int)startStyle startOrientation:(int)orientation;
-(void)_cleanupPhonesContextHostView;
-(void)dealloc;
@end
