/* SBUIAnimationFadeLockscreenToAlert.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIMainScreenAnimationController.h"

@class UIView, SBAlertManager, SBLockScreenViewController;

__attribute__((visibility("hidden")))
@interface SBUIAnimationFadeLockscreenToAlert : SBUIMainScreenAnimationController {
	SBLockScreenViewController* _lockScreenViewController;
	SBAlertManager* _alertManager;
	UIView* _realViewToAnimate;
	BOOL _animatingWithZoom;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithLockScreenController:(id)lockScreenController alertManager:(id)manager;
@end
