/* SBUIStarkAnimationSlideDownApp.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBUIStarkScreenAnimationController.h"

@class UIView, SBAlert;

__attribute__((visibility("hidden")))
@interface SBUIStarkAnimationSlideDownApp : SBUIStarkScreenAnimationController {
	UIView* _viewToAnimate;
	UIView* _activatingContextHostView;
	UIView* _deactivatingContextHostView;
	UIView* _deactivatingDimmingView;
	SBAlert* _alertImpersonator;
}
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithActivatingApp:(id)activatingApp alertImpersonator:(id)impersonator deactivatingApp:(id)app starkScreenController:(id)controller;
@end
