/* SBWindowContextHostInfo.h Was Dumped By @greensnow_tweak on Saturday, 15 June 2013 at 10:00:01 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SBWindowContextManagerObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBWindowContextHostWrapperView, SBWindowContextManager, UIScreen, NSDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBWindowContextHostInfo : XXUnknownSuperclass <SBWindowContextManagerObserver> {
	SBWindowContextManager* _contextManager;
	UIScreen* _screen;
	SBWindowContextHostWrapperView* _wrapperView;
	NSMutableSet* _hiddenContexts;
	NSDictionary* _realContextHostViewChangedProperties;
	NSDictionary* _realContextHostViewOriginalProperties;
}
@property(retain, nonatomic) NSDictionary* realContextHostViewOriginalProperties;
@property(retain, nonatomic) NSDictionary* realContextHostViewChangedProperties;
@property(readonly, assign, nonatomic) NSMutableSet* hiddenContexts;
@property(readonly, assign, nonatomic) SBWindowContextHostWrapperView* wrapperView;
-(void)windowContextManager:(id)manager didRepositionContext:(id)context from:(unsigned)from to:(unsigned)to forScreen:(id)screen;
-(void)dealloc;
-(id)initWithContextManager:(id)contextManager hostManager:(id)manager screen:(id)screen jailBehavior:(int)behavior;
@end
