/* CKTranscriptComposeDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol CKTranscriptComposeDelegate <NSObject>
-(void)transcriptController:(id)controller didSelectNewConversation:(id)conversation;
-(BOOL)supportsAttachments;
-(void)showNewMessageCompositionForMessageParts:(id)messageParts;
-(void)showForwardedMessageParts:(id)parts;
-(void)transcriptController:(id)controller didSendMessageInConversation:(id)conversation;
-(void)transcriptController:(id)controller willSendComposition:(id)composition inConversation:(id)conversation;
-(void)didCancelComposition:(id)composition;
@optional
-(BOOL)canEditRecipients;
@end
