/* SMSApplication.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileSMS-Structs.h"
#import "CNFRegWizardControllerDelegate.h"
#import "IMSystemMonitorListener.h"
#import "UIApplicationDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, BKSProcessAssertion, TLAlert, UIWindow, CKMessagesController, CNFRegWizardController, NSString;

__attribute__((visibility("hidden")))
@interface SMSApplication : XXUnknownSuperclass <CNFRegWizardControllerDelegate, IMSystemMonitorListener, UIApplicationDelegate> {
	BOOL _waitToSendFinishLaunching;
	BOOL _isLocked;
	BOOL _isSuspended;
	BOOL _hasEmail;
	UIWindow* _window;
	CKMessagesController* _messagesController;
	int _delaySuspendCount;
	unsigned _backgroundTask;
	CNFRegWizardController* _madridRegistrationController;
	NSString* _defaultPng;
	int _suspendTimeStatusBarStyle;
	NSURL* _deferredLoadURL;
	BKSProcessAssertion* _backgroundAssertion;
	TLAlert* _alert;
}
@property(retain, nonatomic) UIWindow* window;
@property(retain, nonatomic) CKMessagesController* messagesController;
@property(retain, nonatomic) NSURL* deferredLoadURL;
-(void)_handleDaemonDisconnected:(id)disconnected;
-(void)_handleDaemonConnected:(id)connected;
-(void)_handleAccountsChanged:(id)changed;
-(BOOL)_shouldShowMadridRegistrationView;
-(void)firstRunControllerDidFinish:(id)firstRunController finished:(BOOL)finished;
-(void)_updateMadridRegistrationViewAnimated:(BOOL)animated;
-(void)_destroyMadridRegistrationView;
-(void)_createMadridRegistrationViewIfNecessary;
-(void)_showMadridRegistrationViewIfNecessary;
-(void)__showMadridRegistrationViewIfNecessary;
-(void)_handleTypingIndicatorChanged:(id)changed;
-(void)_handleUnreadCountChanged:(id)changed;
-(void)_updateDefaultPNGSuspended;
-(id)_defaultPNGOverrideInitial;
-(BOOL)_isShowingNewComposition;
-(void)applicationDidEndResumeAnimation;
-(void)_scheduleDeferredSetup;
-(void)significantTimeChange;
-(BOOL)applicationSuspend:(GSEventRef)suspend settings:(id)settings;
-(void)systemApplicationDidResumeForEventsOnly;
-(void)systemApplicationDidSuspendForEventsOnly;
-(void)systemApplicationDidResume;
-(void)systemApplicationDidSuspend;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationDidResumeFromUnderLock;
-(void)_prepareForResume:(BOOL)resume;
-(void)_prepareForSuspend;
-(BOOL)openURL:(id)url;
-(void)reportAppLaunchFinished;
-(void)setWaitToSendFinishLaunching:(BOOL)sendFinishLaunching;
-(void)applicationOpenURL:(id)url;
-(BOOL)isLocked;
-(BOOL)isHandlingURL;
-(void)_storeState;
-(BOOL)_restoreState;
-(void)_migrateLegacySettingsIfNecessary;
-(void)handleURL:(id)url;
-(void)_loadURLMessageGUID:(id)guid;
-(void)_receivedMessage:(id)message;
-(void)_resetIdleTimer;
-(void)_playMessageReceivedForMessage:(id)message;
-(void)stopPlayingLastAlertTone;
-(void)_updateNetworkFlags;
-(void)dealloc;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(id)init;
-(id)defaultPng;
-(void)setDefaultPng:(id)png;
-(void)_clearFailureBadge;
-(void)_mediaDidFinishSaving;
-(void)_mediaDidStartSaving;
-(void)didChangeOrientation:(id)orientation;
-(void)startScrollConversationsTest:(id)test;
-(void)startRotationTest:(id)test;
-(void)startScrollTranscriptTest:(id)test;
-(void)startShowMessagesTest:(id)test;
-(void)showNextMessage;
-(void)didShowTranscriptList;
-(void)didShowAMessage;
-(void)scrollTranscript;
-(void)showKeyboard;
-(void)showTranscriptListNotAnimated;
-(void)showTranscriptList;
-(void)failedTest:(id)test;
-(void)finishedTest:(id)test extraResults:(id)results;
-(BOOL)runTest:(id)test options:(id)options;
@end
