/* AddressBookAddress.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "HistoryItem.h"
#import "PersistentAddressBookAddress.h"

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface AddressBookAddress : PersistentAddressBookAddress <HistoryItem> {
	void* _uncommittedRecord;
	void* _addressBook;
	NSString* _lastValidatedAddress;
}
@property(readonly, assign, nonatomic) BOOL hasStreetAddress;
@property(readonly, assign, nonatomic) BOOL isValid;
@property(copy, nonatomic) NSString* lastValidatedAddress;
@property(readonly, assign, nonatomic) NSDictionary* addressDictionary;
@property(readonly, assign, nonatomic) NSString* phoneticName;
@property(readonly, assign, nonatomic) NSString* compositeName;
@property(readonly, assign, nonatomic) NSString* singleLineAddressWithHomeCountry;
@property(readonly, assign, nonatomic) NSString* singleLineAddress;
+(id)meCardHomeAddress;
+(void)refreshAddressBookIfNeeded:(void*)needed;
+(void)_resetSharedAddressBookNeedsRefresh;
+(void)setSafeAddressBookCanBeRefreshed:(BOOL)refreshed;
+(BOOL)safeAddressBookCanBeRefreshed;
+(void*)safeAddressBookRef;
-(void)_checkValid;
-(void*)_record;
-(int)type;
-(unsigned)hash;
-(void)dealloc;
-(id)_initWithUncommittedRecord:(void*)uncommittedRecord addressID:(int)anId addressBook:(void*)book;
-(id)initWithRecordID:(int)recordID addressID:(int)anId addressBook:(void*)book;
-(id)initWithRecordID:(int)recordID addressID:(int)anId;
-(id)initWithData:(id)data;
-(id)init;
@end
