/* AnimatedOverlayView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UITextField;

__attribute__((visibility("hidden")))
@interface AnimatedOverlayView : XXUnknownSuperclass {
	UITextField* _associatedTextField;
	UIView* _clippingView;
	UITextField* _textField;
	BOOL _isAnimating;
}
@property(assign, nonatomic) BOOL isAnimating;
@property(retain, nonatomic) UITextField* textField;
@property(retain, nonatomic) UIView* clippingView;
@property(retain, nonatomic) UITextField* associatedTextField;
-(void)orientationWillChangeToInterfaceOrientation:(int)orientation;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame associatedTextField:(id)field;
@end
