/* BoldSearchCompletionGlyphViewLayout.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SearchCompletionGlyphViewLayout.h"
#import "Maps-Structs.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface BoldSearchCompletionGlyphViewLayout : SearchCompletionGlyphViewLayout {
	NSArray* _titleBoldRanges;
	NSArray* _subtitleBoldRanges;
}
@property(copy, nonatomic) NSArray* subtitleBoldRanges;
@property(copy, nonatomic) NSArray* titleBoldRanges;
-(id)boldSubtitleLabelTextAttributes;
-(id)boldTitleLabelTextAttributes;
-(void)layout;
-(void)dealloc;
@end
