/* BookmarksViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BookmarkViewControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "CollectionsTableViewController.h"

@class UIBarButtonItem, NSIndexPath, EditBookmarkViewController;
@protocol CollectionsViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface BookmarksViewController : CollectionsTableViewController <UINavigationControllerDelegate, BookmarkViewControllerDelegate> {
	EditBookmarkViewController* _editController;
	UIBarButtonItem* _doneButtonItem;
	BOOL _isChangeSource;
	int _searchType;
	BOOL _isEditingBookmark;
	id<CollectionsViewControllerDelegate> _collectionsViewControllerDelegate;
	NSIndexPath* _editIndexPath;
}
@property(retain, nonatomic) NSIndexPath* editIndexPath;
@property(retain, nonatomic) UIBarButtonItem* doneButtonItem;
@property(assign, nonatomic) int searchType;
@property(assign, nonatomic) id<CollectionsViewControllerDelegate> collectionsViewControllerDelegate;
+(id)title;
+(id)dataSourceChangedNotification;
-(void)dealloc;
-(void)view:(id)view willDisappear:(BOOL)disappear;
-(void)view:(id)view didDisappear:(BOOL)disappear;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(id)tableView:(id)view targetIndexPathForMoveFromRowAtIndexPath:(id)indexPath toProposedIndexPath:(id)proposedIndexPath;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(BOOL)_canEditIndexPath:(id)path inTableView:(id)tableView;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)_handleSelectRow:(id)row;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)updateBookmarkWithEditController:(id)editController;
-(id)editControllerWithBookmark:(id)bookmark;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)_moveBookmarkAtIndex:(unsigned)index toIndex:(unsigned)index2;
-(void)_replaceBookmark:(id)bookmark withBookmark:(id)bookmark2;
-(void)_removeBookmarkAtIndex:(unsigned)index;
-(void)_addBookmark:(id)bookmark;
-(void)_updateEditButtonEnabled;
-(void)dataSourceChanged:(id)changed;
-(id)initWithStyle:(int)style;
@end
