/* EnvironmentsViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface EnvironmentsViewController : XXUnknownSuperclass {
	NSArray* _defaultEnvironmentInfos;
	NSArray* _environmentInfos;
}
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)errorButtonTapped:(id)tapped withEvent:(id)event;
-(id)_environmentForIndexPath:(id)indexPath;
-(void)_reloadEnvironments;
-(void)viewWillAppear:(BOOL)view;
-(void)_done:(id)done;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end
