/* EnvironmentInfoViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class EnvironmentInfo, NSArray;

__attribute__((visibility("hidden")))
@interface EnvironmentInfoViewController : XXUnknownSuperclass {
	EnvironmentInfo* _environment;
	NSArray* _urlStrings;
}
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)_urlStringForIndexPath:(id)indexPath isFromManifest:(BOOL*)manifest;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)dealloc;
-(id)initWithStyle:(int)style environment:(id)environment;
@end
