/* History.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MapsSyncedClient.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, MapsSyncManager, NSMutableArray, NSLock, NSString;

__attribute__((visibility("hidden")))
@interface History : XXUnknownSuperclass <MapsSyncedClient> {
	MapsSyncManager* _syncManager;
	NSMutableArray* _history;
	NSMutableArray* _allHistory;
	NSMutableArray* _syncedHistory;
	NSLock* _historyLock;
	NSLock* _syncLock;
}
@property(readonly, assign, nonatomic) BOOL syncShouldUseCustomStore;
@property(readonly, assign, nonatomic) BOOL syncShouldUseItemPositions;
@property(readonly, assign, nonatomic) BOOL syncInvertedOrdering;
@property(readonly, assign, nonatomic) BOOL syncSupportsKVO;
@property(readonly, assign, nonatomic) NSArray* syncedItems;
@property(readonly, assign, nonatomic) NSString* syncIdentifier;
@property(readonly, assign, nonatomic) NSArray* allHistory;
@property(readonly, assign, nonatomic) unsigned orderedHistoryCount;
@property(readonly, assign, nonatomic) NSArray* orderedHistory;
+(id)sharedHistory;
-(void)updateSyncedItemAtIndexes:(id)indexes;
-(void)removeSyncedItemsAtIndexes:(id)indexes;
-(void)insertSyncedItems:(id)items atIndexes:(id)indexes;
-(id)newSyncedItemForSyncData:(id)syncData;
-(void)updateAddressForSearchResult:(id)searchResult;
-(void)removeAllItems;
-(void)addHistoryItem:(id)item;
-(void)dealloc;
-(id)init;
-(void)_removeInvalidItems;
-(void)_madeChanges;
-(void)_saveHistory;
-(void)_updateHistory;
@end
