/* InfoCardCheckInWriteTipCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSAttributedString;
@protocol InfoCardCheckInWriteTipCellDelegate;

__attribute__((visibility("hidden")))
@interface InfoCardCheckInWriteTipCell : XXUnknownSuperclass {
	UILabel* _checkInLabel;
	UILabel* _writeTipLabel;
	NSAttributedString* _checkInTitle;
	NSAttributedString* _writeTipTitle;
	id<InfoCardCheckInWriteTipCellDelegate> _delegate;
}
@property(assign, nonatomic) id<InfoCardCheckInWriteTipCellDelegate> delegate;
@property(retain, nonatomic) NSAttributedString* writeTipTitle;
@property(retain, nonatomic) NSAttributedString* checkInTitle;
+(id)reuseIdentifier;
+(BOOL)requiresConstraintBasedLayout;
-(void)cellTapped:(id)tapped;
-(void)updateConstraints;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
