/* MapsChromeModeController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class ChromeViewController;

@protocol MapsChromeModeController <NSObject>
@property(assign, nonatomic) ChromeViewController* chromeViewController;
-(void)resignCurrentModeAnimated:(BOOL)animated toMode:(id)mode;
-(void)becomeCurrentModeWithViews:(id)views animated:(BOOL)animated state:(id)state fromMode:(id)mode;
@optional
-(void)animateBarsToCurrentStateWithAnimation:(id)animation;
-(BOOL)needsAudioControl;
-(void)didRemoveFromChromeViewController;
-(void)willRemoveFromChromeViewController;
-(void)willChangeToMapDisplayStyle:(int)mapDisplayStyle forChangeToLightLevel:(int)lightLevel animation:(id)animation;
-(void)layoutForUnobscuredBoundsChange;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)popsWhenSuppressed;
-(id)viewState;
@end
