/* MNCoreMotionContextProvider.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MNMotionContextProvider.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CMActivityManager;
@protocol MNMotionContextProviderDelegate;

__attribute__((visibility("hidden")))
@interface MNCoreMotionContextProvider : XXUnknownSuperclass <MNMotionContextProvider> {
	CMActivityManager* _activityManager;
	id<MNMotionContextProviderDelegate> _delegate;
}
@property(assign, nonatomic) id<MNMotionContextProviderDelegate> motionDelegate;
-(void)stopMotionUpdates;
-(void)startMotionUpdates;
-(void)dealloc;
@end
