/* MNDestinationAnnotation.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MKAnnotation.h"
#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface MNDestinationAnnotation : XXUnknownSuperclass <MKAnnotation> {
	XXStruct_gLbvpC _coordinate;
}
@property(readonly, assign, nonatomic) NSString* subtitle;
@property(readonly, assign, nonatomic) NSString* title;
@property(assign, nonatomic) XXStruct_gLbvpC coordinate;
@end
