/* MNJunction.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface MNJunction : XXUnknownSuperclass {
	XXStruct_DtYHXC* _elements;
	unsigned long _count;
	int _type;
	CGPoint* _snapped[8];
}
@property(readonly, assign, nonatomic) int type;
-(void)getRoundaboutArrowPath:(id*)path intersectionBackgroundPath:(id*)path2 strokePath:(id*)path3 withSize:(CGSize)size metrics:(XXStruct_psi9$D)metrics drivingSide:(int)side;
-(id)roundaboutArrowWithSize:(CGSize)size metrics:(XXStruct_psi9$D)metrics outerRadius:(float)radius endAngle:(float)angle pivot:(CGPoint*)pivot;
-(void)getArrowPath:(id*)path arrowStrokePath:(id*)path2 pivot:(CGPoint*)pivot withSize:(CGSize)size metrics:(XXStruct_psi9$D)metrics;
-(void)getArrowPath:(id*)path arrowStrokePath:(id*)path2 intersectionBackgroundPath:(id*)path3 strokePath:(id*)path4 withSize:(CGSize)size metrics:(XXStruct_psi9$D)metrics drivingSide:(int)side;
-(void)dealloc;
-(id)initWithType:(int)type maneuver:(int)maneuver drivingSide:(int)side elements:(XXStruct_DtYHXC*)elements count:(unsigned long)count;
@end
