/* MNLocation.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class VKAttributedRouteMatch, CLLocation, VKMapMatch, NSString;

__attribute__((visibility("hidden")))
@interface MNLocation : XXUnknownSuperclass {
	int _state;
	VKAttributedRouteMatch* _routeMatch;
	VKMapMatch* _roadMatch;
	CLLocation* _rawLocation;
	NSString* _routeMatchRoadName;
	long long _shieldType;
	NSString* _shieldText;
	BOOL _locationUnreliable;
}
@property(readonly, assign, nonatomic) BOOL isProjected;
@property(assign, nonatomic) BOOL locationUnreliable;
@property(readonly, assign, nonatomic) NSString* shieldText;
@property(readonly, assign, nonatomic) long long shieldType;
@property(readonly, assign, nonatomic) double routeAccuracy;
@property(readonly, assign, nonatomic) CLLocation* rawLocation;
@property(readonly, assign, nonatomic) VKMapMatch* roadMatch;
@property(retain, nonatomic) VKAttributedRouteMatch* routeMatch;
@property(readonly, assign, nonatomic) BOOL hadRouteToCompare;
@property(readonly, assign, nonatomic) NSString* roadName;
@property(readonly, assign, nonatomic) int state;
+(id)locationWithRawLocation:(id)rawLocation roadMatch:(id)match useMatchLocation:(BOOL)location;
+(id)locationWithRawLocation:(id)rawLocation routeMatch:(id)match roadName:(id)name shieldType:(long long)type shieldText:(id)text useMatchLocation:(BOOL)location;
+(id)locationWithRawLocation:(id)rawLocation coordinate:(XXStruct_gLbvpC)coordinate course:(double)course;
+(id)locationWithRawLocation:(id)rawLocation;
-(BOOL)hasValidCourse;
-(BOOL)isStale;
-(id)description;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithRawLocation:(id)rawLocation roadMatch:(id)match useMatchLocation:(BOOL)location;
-(id)initWithRawLocation:(id)rawLocation routeMatch:(id)match roadName:(id)name shieldType:(long long)type shieldText:(id)text useMatchLocation:(BOOL)location;
-(id)initWithRawLocation:(id)rawLocation coordinate:(XXStruct_gLbvpC)coordinate course:(double)course;
@end
