/* MNMotionContext.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MNMotionContextProviderDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol MNMotionContextProvider;

__attribute__((visibility("hidden")))
@interface MNMotionContext : XXUnknownSuperclass <MNMotionContextProviderDelegate> {
	id<MNMotionContextProvider> _provider;
	int _motionType;
	int _confidence;
}
@property(readonly, assign, nonatomic) BOOL isDriving;
@property(readonly, assign, nonatomic) BOOL isRunning;
@property(readonly, assign, nonatomic) BOOL isWalking;
@property(readonly, assign, nonatomic) BOOL isMoving;
@property(readonly, assign, nonatomic) int confidence;
@property(readonly, assign, nonatomic) int motionType;
-(id)description;
-(void)motionContextProvider:(id)provider didUpdateMotion:(int)motion confidence:(int)confidence;
-(void)stopMotionUpdates;
-(void)startMotionUpdatesWithProvider:(id)provider;
-(void)dealloc;
@end
