/* MNSimpleSignView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, MNGuidanceManeuverView, UIImageView, MNSignStyle;

__attribute__((visibility("hidden")))
@interface MNSimpleSignView : XXUnknownSuperclass {
	UIImageView* _backgroundView;
	MNGuidanceManeuverView* _maneuverView;
	UIEdgeInsets _maneuverViewEdgeInsets;
	UIImageView* _shieldView;
	MNSignStyle* _style;
}
@property(retain, nonatomic) MNSignStyle* style;
@property(retain, nonatomic) UIImage* shieldImage;
@property(readonly, assign, nonatomic) MNGuidanceManeuverView* maneuverView;
@property(assign, nonatomic) UIEdgeInsets maneuverViewEdgeInsets;
-(id)shieldImageView;
-(void)updateStyleForTheme;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
