/* MNWalkMapMatcher.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MNMapMatcher.h"


__attribute__((visibility("hidden")))
@interface MNWalkMapMatcher : MNMapMatcher {
}
-(id)matchLocation:(id)location alongRoute:(id)route onDate:(id)date activeTransportType:(int)type;
-(int)transportType;
@end
