/* MUPlaceCardPhotosController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "_PlaceCardPhotoCollectionViewCellDelegate.h"

@class GEOBusiness, SearchResult;
@protocol MUPlaceCardPhotosControllerDelegate;

__attribute__((visibility("hidden")))
@interface MUPlaceCardPhotosController : XXUnknownSuperclass <_PlaceCardPhotoCollectionViewCellDelegate> {
	SearchResult* _searchResult;
	BOOL _showAddPhotoButton;
	BOOL _showMorePhotosButton;
	BOOL _showAttributionButtons;
	id<MUPlaceCardPhotosControllerDelegate> _photosControllerDelegate;
	GEOBusiness* _business;
}
@property(retain, nonatomic) GEOBusiness* business;
@property(assign, nonatomic) BOOL showAddPhotoButton;
@property(assign, nonatomic) BOOL showMorePhotosButton;
@property(assign, nonatomic) BOOL showAttributionButtons;
@property(assign, nonatomic) id<MUPlaceCardPhotosControllerDelegate> photosControllerDelegate;
@property(retain, nonatomic) SearchResult* searchResult;
-(float)_heightForGridView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)_morePhotos;
-(void)_addPhoto;
-(void)photoCollectionViewCell:(id)cell didSelectPhotoWithInfo:(id)info;
-(unsigned)supportedInterfaceOrientations;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
@end
