/* PerformanceDebugController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "AuxiliaryDebugViewController.h"

@class NSMutableArray;
@protocol DebugViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface PerformanceDebugController : AuxiliaryDebugViewController {
	NSMutableArray* _tests;
	id<DebugViewControllerDelegate> _delegate;
}
+(id)navigationDestinationTitle;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)title;
-(void)dealloc;
-(id)init;
@end
