/* RAPSearchIncorrectMapMovementLocationPickerCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextFieldDelegate.h"

@class UITextField;

__attribute__((visibility("hidden")))
@interface RAPSearchIncorrectMapMovementLocationPickerCell : XXUnknownSuperclass <UITextFieldDelegate> {
	UITextField* _textField;
	BOOL _needsFirstResponderState;
	id _didChangeText;
}
@property(copy, nonatomic) id didChangeText;
@property(readonly, assign, nonatomic) UITextField* textField;
-(void)layoutSubviews;
-(void)setNeedsFirstResponderState;
-(void)didMoveToWindow;
-(void)_textFieldDidChangeValue;
-(void)dealloc;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
@end
