/* ReportAProblemSatelliteViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "ReportAProblemReporter.h"
#import "Maps-Structs.h"

@class ReportAProblemNavigationController, UITextView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ReportAProblemSatelliteViewController : XXUnknownSuperclass <ReportAProblemReporter> {
	UITextView* _textView;
	NSMutableArray* _problemItems;
}
@property(readonly, assign, nonatomic) ReportAProblemNavigationController* navigationController;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)populateRPProblem:(id)problem;
-(void)populateProblem:(id)problem;
-(void)cancel:(id)cancel;
-(void)send:(id)send;
-(id)_selectedItem;
-(void)dealloc;
-(void)updateEnabledState;
-(BOOL)canReportProblem;
-(void)viewWillAppear:(BOOL)view;
-(CGSize)contentSizeForViewInPopover;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end
