/* ReportAProblemTopTableViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "ReportAProblemReporter.h"
#import "ReportAProblemAdditionalContext.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "Maps-Structs.h"

@class ReportAProblemCommentsViewController, ReportAProblemDirectionsViewController, GEODirectionsProblem, GEORPDirectionsProblem, ReportAProblemNavigationController, ReportAProblemLocationPickerViewController, NSMutableArray, ReportAProblemSatelliteViewController, ReportAProblemAddressEditorViewController, ReportAProblemLabelEditorViewController, ReportAProblemTrafficViewController, ReportAProblemDirectionsDetailsViewController, RAPSearchClassicViewController, ReportAProblemSearchResultsViewController;

__attribute__((visibility("hidden")))
@interface ReportAProblemTopTableViewController : XXUnknownSuperclass <ReportAProblemReporter, ReportAProblemAdditionalContext> {
	NSMutableArray* _problemItems;
	ReportAProblemSearchResultsViewController* _searchResultsViewController;
	RAPSearchClassicViewController* _searchClassicViewController;
	ReportAProblemCommentsViewController* _commentsViewController;
	ReportAProblemLocationPickerViewController* _locationPickerViewController;
	ReportAProblemAddressEditorViewController* _addressViewController;
	ReportAProblemDirectionsViewController* _simplerDirectionsViewController;
	ReportAProblemDirectionsDetailsViewController* _directionsViewController;
	ReportAProblemSatelliteViewController* _satelliteViewController;
	ReportAProblemLabelEditorViewController* _labelEditorViewController;
	ReportAProblemTrafficViewController* _trafficViewController;
	BOOL _problemRequiresAdditionalContext;
	id _directionsHistoryItem;
	GEODirectionsProblem* _directionsProblemReport;
	GEORPDirectionsProblem* _directionsProblemRPReport;
}
@property(readonly, assign, nonatomic) ReportAProblemNavigationController* navigationController;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)populateRPProblem:(id)problem;
-(void)populateProblem:(id)problem;
-(void)updateEnabledState;
-(BOOL)canReportProblem;
-(void)next:(id)next;
-(id)_selectedItem;
-(void)cancel:(id)cancel;
-(unsigned)supportedInterfaceOrientations;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(CGSize)contentSizeForViewInPopover;
-(BOOL)problemRequiresAdditionalContext;
-(void)viewDidLoad;
-(id)initWithStyle:(int)style;
@end
