/* SearchResultCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import "SnapshotResponderProtocol.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class MKMapSnapshot, MKMapSnapshotter, UIImage, UIColor, SearchResult;

__attribute__((visibility("hidden")))
@interface SearchResultCell : XXUnknownSuperclass <SnapshotResponderProtocol> {
	SearchResult* _searchResult;
	CGRect _frame;
	int _page;
	int _order;
	BOOL _hasSnapshot;
	MKMapSnapshot* _snapshot;
	MKMapSnapshotter* _snapshotter;
	UIColor* _blueTextColor;
	UIColor* _calloutTextColor;
}
@property(readonly, assign, nonatomic) BOOL hasSnapshot;
@property(readonly, assign, nonatomic) UIImage* snapshotImage;
@property(assign, nonatomic) int order;
@property(assign, nonatomic) float y;
@property(assign, nonatomic) int page;
@property(assign, nonatomic) CGRect frame;
@property(retain, nonatomic) SearchResult* searchResult;
+(id)cellWithSearchResult:(id)searchResult order:(int)order;
-(CGPoint)transformedPoint:(CGAffineTransform)point;
-(void)dealloc;
-(void)releaseSnapshotCreator;
-(id)snapshotBlock;
-(void)drawInRect:(CGRect)rect;
-(float)_textLayoutHeight;
-(void)_drawPinInRect:(CGRect)rect zoomLevel:(float)level;
-(id)initWithSearchResult:(id)searchResult order:(int)order;
@end
