/* StarkButton.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage;

__attribute__((visibility("hidden")))
@interface StarkButton : XXUnknownSuperclass {
	float _screenScale;
	BOOL _usesMinimumWidth;
	int _starkButtonCompositingStyle;
	int _starkButtonHighlightStyle;
	int _starkButtonSize;
	UIImage* _unmodifiedRegularStateImage;
	int _displayedLightLevel;
	int _starkTextWeight;
}
@property(retain, nonatomic) UIImage* unmodifiedRegularStateImage;
@property(assign, nonatomic) int starkTextWeight;
@property(assign, nonatomic) int displayedLightLevel;
@property(assign, nonatomic) int starkButtonSize;
@property(assign, nonatomic) int starkButtonHighlightStyle;
@property(assign, nonatomic) int starkButtonCompositingStyle;
@property(assign, nonatomic) BOOL usesMinimumWidth;
-(void)layoutSubviews;
-(void)_updateAttributedTitles;
-(void)_updateBackgroundColor;
-(void)setHighlighted:(BOOL)highlighted;
-(CGSize)sizeThatFits:(CGSize)fits;
-(CGSize)intrinsicContentSize;
-(void)setTitle:(id)title forState:(unsigned)state;
-(void)_updateImagesFromUnmodifiedRegularImage;
-(void)setImage:(id)image forState:(unsigned)state;
-(id)attributedStringForTitle:(id)title state:(unsigned)state;
-(id)_currentStyleAttributesForState:(unsigned)state;
-(id)initWithFrame:(CGRect)frame;
@end
