/* StarkSingleLikelyRouteViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class StarkSingleLikelyRouteView, StarkLikelyRoute;

__attribute__((visibility("hidden")))
@interface StarkSingleLikelyRouteViewController : XXUnknownSuperclass {
	id _startNavigationTarget;
	SEL _startNavigationAction;
	BOOL _willAnimateIn;
}
@property(readonly, assign, nonatomic) StarkSingleLikelyRouteView* likelyRouteView;
@property(assign, nonatomic) int interactionModel;
@property(retain, nonatomic) StarkLikelyRoute* route;
@property(assign, nonatomic) BOOL willAnimateIn;
-(id)animateOutByRelinquishingWorldViewWithAnimation:(id)animation;
-(void)animateIn:(id)anIn byAdoptingWorldView:(id)view;
-(void)_startNavigation;
-(void)setStartNavigationTarget:(id)target action:(SEL)action;
-(void)removeCloseButtonTarget:(id)target action:(SEL)action;
-(void)addCloseButtonTarget:(id)target action:(SEL)action;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
@end
