/* StarkLauncherViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class StarkChromeViewController;
@protocol CancellableTask;

__attribute__((visibility("hidden")))
@interface StarkLauncherViewController : XXUnknownSuperclass {
	StarkChromeViewController* _chromeViewController;
	BOOL _displayed;
	id<CancellableTask> _viewControllerAcquisitionTask;
}
@property(retain, nonatomic) id<CancellableTask> viewControllerAcquisitionTask;
-(void)setViewportFrame:(CGRect)frame;
-(void)viewDidDisappear:(BOOL)view;
-(void)_removeStarkChrome;
-(void)_acquireStarkChrome:(id)chrome;
-(void)_reacquireViewControllerIfNeeded;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLayoutSubviews;
-(void)loadView;
-(void)dealloc;
-(id)init;
@end
