/* StarkPredictedLocation.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "StarkSuggestionProvider.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface StarkPredictedLocation : XXUnknownSuperclass <StarkSuggestionProvider> {
}
-(void)updateForLocation:(id)location timePeriod:(id)period distanceThreshold:(double)threshold handler:(id)handler;
@end
