/* StarkLikelyRouteUpdater.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MKETAUpdaterDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class VKAttributedRoute, StarkLikelyRoute, MKETAUpdater;
@protocol StarkLikelyRouteUpdaterDelegate;

__attribute__((visibility("hidden")))
@interface StarkLikelyRouteUpdater : XXUnknownSuperclass <MKETAUpdaterDelegate> {
	id<StarkLikelyRouteUpdaterDelegate> _delegate;
	StarkLikelyRoute* _likelyRoute;
	VKAttributedRoute* _attributedRoute;
	MKETAUpdater* _etaUpdater;
}
@property(readonly, assign, nonatomic) StarkLikelyRoute* likelyRoute;
@property(assign, nonatomic) id<StarkLikelyRouteUpdaterDelegate> delegate;
-(void)_handleBadRoute;
-(id)_routeMatch:(id)match;
-(void)_updateWithNewLikelyRoute:(id)newLikelyRoute;
-(void)etaUpdaterReceivedInvalidRoute:(id)route newRoute:(id)route2 incidentsOnNewRoute:(id)route3;
-(void)etaUpdaterUpdatedETA:(id)eta;
-(void)updateLocation:(id)location;
-(void)dealloc;
-(id)initWithLikelyRoute:(id)likelyRoute;
@end
