/* XXUnknownSuperclass.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Maps-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, AnimatedOverlayView, UIViewController, NSString;

@interface XXUnknownSuperclass (UIKitExtras)
+(id)_maps_keyColor;
+(id)infoCardBackgroundColor;
+(id)directionsCellHighlightedBackgroundColor;
+(id)textShadowColor;
@end

@interface XXUnknownSuperclass (UIKitExtras)
@property(readonly, assign, nonatomic) NSString* hwMachine;
@end

@interface XXUnknownSuperclass (UIKitExtras)
+(id)shadowedTextLabelWithText:(id)text font:(id)font;
+(id)newStandardTextLabelWithFont:(id)font;
@end

@interface XXUnknownSuperclass (UIKitExtras)
-(void)showRightViewForEditing;
-(void)removeRightViews;
@end

@interface XXUnknownSuperclass (UIKitExtras)
@property(readonly, assign, nonatomic) UIViewController* rootViewController;
@end

@interface XXUnknownSuperclass (TextAlignment)
+(int)currentTextAlignment;
@end

@interface XXUnknownSuperclass (AsynchronousImageLoading)
+(void)loadImageWithURL:(id)url completion:(id)completion;
@end

@interface XXUnknownSuperclass (UIKitExtras)
-(BOOL)isCalloutExpanded;
@end

@interface XXUnknownSuperclass (Shuffling)
-(void)shuffle;
@end

@interface XXUnknownSuperclass (UIKitExtras)
+(BOOL)_maps_shouldAdoptImplicitAnimationParameters;
-(void)_maps_dockView:(id)view toRightSideOfRect:(CGRect)rect width:(float)width;
-(void)_maps_dockView:(id)view toLeftSideOfRect:(CGRect)rect width:(float)width;
-(void)_maps_centerView:(id)view size:(CGSize)size atY:(float)y;
-(void)_maps_centerView:(id)view size:(CGSize)size inRect:(CGRect)rect;
-(void)_maps_centerView:(id)view fit:(BOOL)fit constrain:(BOOL)constrain inRect:(CGRect)rect;
-(void)_maps_centerView:(id)view fit:(BOOL)fit inRect:(CGRect)rect;
-(void)_maps_constrainSubview:(id)subview toValue:(float)value attribute:(int)attribute;
-(void)_maps_constrainSubview:(id)subview sameAsView:(id)view attribute:(int)attribute;
-(void)_maps_highlight;
-(void)_maps_highlightWithColor:(id)color;
-(void)_maps_recursivelyLayoutSubviewsImmediately;
-(void)_maps_recursivelySetAllowsGroupOpacity:(BOOL)opacity;
@end

@interface XXUnknownSuperclass (UIKitExtras)
+(void)_maps_evictCachedImagesAtMemoryWarning;
+(id)_maps_URLForImageNamed:(id)imageNamed integralScale:(int)scale;
+(id)_maps_URLForImageNamed:(id)imageNamed scale:(float)scale;
+(id)_maps_imageNamed:(id)named scale:(float)scale;
+(id)_maps_imageNamed:(id)named forScreen:(id)screen;
@end

@interface XXUnknownSuperclass (UIKitExtras)
-(BOOL)mapsIsStark;
@end

@interface XXUnknownSuperclass (UIKitExtras)
-(void)_maps_setImageNamed:(id)named forState:(unsigned)state;
-(void)_maps_setBackgroundImageNamed:(id)named forState:(unsigned)state;
@end

@interface XXUnknownSuperclass (UIKitExtras)
-(void)_maps_setImageNamed:(id)named;
@end

@interface XXUnknownSuperclass (UIKitExtras)
-(BOOL)_maps_isScrollEvent;
@end

@interface XXUnknownSuperclass (Animations)
@property(assign, nonatomic, setter=_setSuppressNextScrollAnimation:) BOOL _suppressNextScrollAnimation;
@property(assign, nonatomic, getter=_isScrollingToEditMode, setter=_setScrollingToEditMode:) BOOL _scrollingToEditMode;
@property(readonly, assign, nonatomic) float _unavailableWidthForFieldEditor;
@property(readonly, assign, nonatomic) AnimatedOverlayView* _overlay;
-(void)_updateClippingViewFrame;
-(void)_setIsPerformingHorizontalScroll:(BOOL)scroll window:(id)window;
-(void)_animationDidFinish:(BOOL)_animation window:(id)window;
-(void)_performHorizontalScrollFromEditModeWithLeftEdgeOfText:(float)text;
-(void)_performHorizontalScrollToEditMode;
-(void)_maps_showCaret;
-(void)_maps_hideCaret;
@end

@interface XXUnknownSuperclass (SearchResultsAdditions)
-(XXStruct_gLbvpC)pinDroppingCoordinate;
-(BOOL)_pinPositionAvailableAtPoint:(CGPoint)point;
-(void)setSelectedSearchResult:(id)result;
-(id)selectedSearchResult;
-(void)goToSearchResults:(id)searchResults mapRegion:(id)region requireMapMovement:(BOOL)movement animation:(int)animation;
-(void)goToSearchResults:(id)searchResults mapRegion:(id)region requireMapMovement:(BOOL)movement;
-(BOOL)isCoordinateVisible:(XXStruct_gLbvpC)visible;
-(id)mapRegionContainingSearchResults:(id)results;
-(XXStruct_Yvvv9D)mapRectThatFits:(XXStruct_Yvvv9D)fits minMetersPerPoint:(double)point;
@end

@interface XXUnknownSuperclass (Persistence)
-(BOOL)_writeBinaryPlist:(id)plist error:(id*)error;
@end

@interface XXUnknownSuperclass (Voltaire)
-(void)addMapViewInfo:(id)info;
-(id)initRoutingSearchRequest;
-(id)initDisplayableSearchRequest;
-(id)initDisplayableSearchRequest:(BOOL)request;
-(id)initCompletionsSearchRequest;
-(id)initBasicSearchRequest:(BOOL)request;
@end

@interface XXUnknownSuperclass (Maps)
-(void)copyReusableFieldsTo:(id)to;
@end

@interface XXUnknownSuperclass (Maps)
-(id)initBasicForwardGeocodeRequestWithAddressDictionary:(id)addressDictionary;
-(id)initBasicForwardGeocodeRequestWithAddressString:(id)addressString;
@end

@interface XXUnknownSuperclass (MNExtras)
-(BOOL)maneuverIsTakeNthExitAtRoundabout;
-(BOOL)maneuverIsHighwayExit;
-(id)phoneticInstructionsWithFormat;
-(id)phoneticInstructions;
-(BOOL)isEndOfNavigation;
-(BOOL)isArrival;
-(double)speed;
@end

@interface XXUnknownSuperclass (MNExtras)
@property(readonly, assign) XXStruct_gLbvpC* points_cl;
-(unsigned)expectedTimeFromMatch:(id)match;
-(int)drivingSideForStep:(id)step;
-(id)manueverStepForPointIndex:(unsigned)pointIndex;
-(id)nextStep:(unsigned)step;
-(XXStruct_gLbvpC)firstCoordinateForStep:(id)step;
@end

@interface XXUnknownSuperclass (MNExtras)
-(id)initWithAddressSearchResult:(id)addressSearchResult mapViewSearchInfo:(id)info;
-(id)initWithQuery:(id)query mapViewSearchInfo:(id)info;
-(void)_updateWithMapViewInfo:(id)mapViewInfo;
-(id)initWithGEOAddress:(id)geoaddress;
-(id)initWithLatitude:(double)latitude longitude:(double)longitude;
-(id)initWithBusinessID:(unsigned long long)businessID;
-(id)initWithLocation:(id)location;
-(id)initWithAddressString:(id)addressString atCoordinate:(XXStruct_gLbvpC)coordinate;
@end

@interface XXUnknownSuperclass (MNExtras)
-(void)applyFlagsForNavigation;
@end

@interface XXUnknownSuperclass (MNExtras)
-(id)singleLineAddress;
@end

@interface XXUnknownSuperclass (MNExtras)
-(id)mapRegionForArrivalDetection;
-(id)initWithPlaceSearchRequest:(id)placeSearchRequest;
@end

@interface XXUnknownSuperclass (MNExtras)
-(id)initWithSearchResult:(id)searchResult mapViewSearchInfo:(id)info fallbackString:(id)string suggestionsPrefix:(id)prefix;
-(id)initWithCLLocation:(id)cllocation;
-(id)_initWithQuery:(id)query mapViewSearchInfo:(id)info;
-(id)_initWithAddressSearchResult:(id)addressSearchResult mapViewSearchInfo:(id)info;
-(id)_initWithCoordinateSearchResult:(id)coordinateSearchResult hasFallbackString:(BOOL)string;
-(id)_initWithLatitude:(double)latitude longitude:(double)longitude needsGeocoding:(BOOL)geocoding;
-(id)_initWithPlaceSearchRequest:(id)placeSearchRequest;
@end

@interface XXUnknownSuperclass (MNExtras)
+(id)stringWithTimeInterval:(double)timeInterval;
+(id)stringWithTimeIntervalAccurate:(double)timeIntervalAccurate;
+(id)stringWithAltitudeUnits;
+(id)stringWithAltitude:(double)altitude accuracy:(double)accuracy;
+(id)stringWithDirection:(double)direction abbreviated:(BOOL)abbreviated;
+(id)stringWithSpeedUnits;
+(id)stringWithSpeed:(double)speed;
+(id)stringWithRemainingTime:(double)remainingTime distance:(double)distance;
+(id)stringWithRemainingTime:(double)remainingTime allowShortForm:(BOOL)form;
+(id)_maps_shortStringWithRemainingTime:(double)remainingTime;
+(id)stringWithDistance:(double)distance useMetric:(BOOL)metric useYardsForShortDistances:(BOOL)shortDistances extraDetail:(BOOL)detail;
+(id)voiceOverStringWithRemainingTime:(double)remainingTime distance:(double)distance;
+(id)voiceOverStringWithRemainingTime:(double)remainingTime;
+(id)speechWithDistance:(double)distance roundValues:(BOOL)values useMetric:(BOOL)metric useYardsForShortDistances:(BOOL)shortDistances;
+(id)_maps_voiceOverLocalizedDistanceStringWithMeters:(unsigned)meters inMetric:(BOOL)metric displaysYardsForShortDistances:(BOOL)shortDistances includeTrip:(BOOL)trip;
+(id)_maps_localizedDistanceStringWithMeters:(unsigned)meters inMetric:(BOOL)metric displaysYardsForShortDistances:(BOOL)shortDistances includeTrip:(BOOL)trip abbreviated:(BOOL)abbreviated;
+(id)_maps_formattedStringForFloat:(float)aFloat useIncreasedPrecision:(BOOL)precision;
+(id)_maps_formattedStringForFloat:(float)aFloat;
+(id)_maps_formattedStringForInt:(int)int;
-(NSRange)_maps_rangeForTimePartOfFormattedShortTimeString;
-(id)stringByMarkingAsAddress;
-(id)stringByMakingPhonetic;
-(int)fileCreationDateDescendingSort:(id)sort;
@end

@interface XXUnknownSuperclass (MNExtras)
+(id)stringWithRemainingTime:(double)remainingTime distance:(double)distance timeAttributes:(id)attributes distanceAttributes:(id)attributes4;
@end

@interface XXUnknownSuperclass (MapsCalloutButton)
+(id)_maps_disclosureCalloutButton;
@end

@interface XXUnknownSuperclass (MapsAppDelegate)
@property(readonly, assign, nonatomic) BOOL mapsIsInBackground;
+(id)sharedMapsDelegate;
@end

@interface XXUnknownSuperclass (SearchCompletionsTableViewControllerExtras)
-(id)stringByTrimmingLeadingWhitespace;
@end

@interface XXUnknownSuperclass (MNSearchResultExtras)
-(id)acceptableSpokenName;
@end

@interface XXUnknownSuperclass (SearchFieldItemAdditions)
-(void)updateWithSearchFieldItem:(id)searchFieldItem;
@end

@interface XXUnknownSuperclass (MapsExtras)
+(id)webSourcesBundleIdentifiers;
+(id)mailSourcesBundleIdentifiers;
+(id)messageSourcesBundleIdentifiers;
@end

@interface XXUnknownSuperclass (TransitAppSelectionCell)
+(id)sublabelTextColor;
@end

@interface XXUnknownSuperclass (TransitAppSelectionCell)
-(void)applyHighlightedTransitShadows;
-(void)applyNormalTransitShadows;
@end

@interface XXUnknownSuperclass (TransitAppSuggestionProviderAdditions)
+(id)storePlatformErrorWithUserInfo:(id)userInfo;
+(id)searchErrorWithUserInfo:(id)userInfo;
@end

@interface XXUnknownSuperclass (TransitAppsManagerAdditions)
-(id)coverageFilePath;
@end

@interface XXUnknownSuperclass (TransitStoreAppDictionary)
@property(readonly, assign, nonatomic) BOOL isInstalled;
@property(readonly, assign, nonatomic) BOOL isOfficialApp;
@property(readonly, assign, nonatomic) NSArray* categories;
@property(readonly, assign, nonatomic) NSArray* transitModeKeys;
@property(readonly, assign, nonatomic) NSString* priceFormatted;
@property(readonly, assign, nonatomic) NSString* url;
@property(readonly, assign, nonatomic) unsigned ratingCount;
@property(readonly, assign, nonatomic) float averageRating;
@property(readonly, assign, nonatomic) NSString* creator;
@property(readonly, assign, nonatomic) NSString* bundleId;
@property(readonly, assign, nonatomic) NSString* title;
-(id)bestImageURLForWidth:(float)width;
-(id)_defaultOffer;
-(id)_ratingData;
@end

@interface XXUnknownSuperclass (RouteStepAddtions)
+(id)_mapkit_arrivalWithDate:(id)date allowCountdown:(BOOL)countdown;
+(id)_mapkit_arrivalWithDate:(id)date;
+(id)_mapkit_departureWithDate:(id)date allowCountdown:(BOOL)countdown;
+(id)_referenceDateWithTimeZone:(id)timeZone;
+(id)_mapkit_departureWithDate:(id)date;
@end

@interface XXUnknownSuperclass (SearchPinsManagerAdditions)
-(void)dropPinsForSearchResults:(id)searchResults animate:(BOOL)animate;
-(void)dropPinsForSearchResults:(id)searchResults selectedSearchResult:(id)result animate:(BOOL)animate;
@end

@interface XXUnknownSuperclass (MapExtras)
-(id)stringByRemovingPunctuation;
@end

@interface XXUnknownSuperclass (MNETAManager)
-(id)stepsTable;
@end

@interface XXUnknownSuperclass (RouteAdditions)
-(CGRect)significantFrameWithCanvasSize:(CGSize)canvasSize;
@end

@interface XXUnknownSuperclass (BusinessHourExtras)
@property(readonly, assign, nonatomic) NSString* displayString;
-(BOOL)isAdjacentToTimeRange:(id)timeRange;
@end

@interface XXUnknownSuperclass (LoadingCellAdditions)
-(void)applyLoadingCellStyling;
@end

@interface XXUnknownSuperclass (LoadingCellAdditions)
-(void)centerViewInSuperview;
@end

@interface XXUnknownSuperclass (StarkIAP)
-(id)initWithQuery:(id)query location:(id)location span:(double)span;
@end

@interface XXUnknownSuperclass (MapsInternalExtras)
+(id)mapsInternalExtrasImageNamed:(id)named;
@end

@interface XXUnknownSuperclass (MapsInternalExtras)
+(id)mapsInternalStringForKey:(id)key;
@end

@interface XXUnknownSuperclass (GEOSearchExtras)
+(id)reviewWithYelpJSON:(id)yelpJSON;
@end

@interface XXUnknownSuperclass (GEOSearchExtras)
+(id)userWithYelpJSON:(id)yelpJSON;
@end

@interface XXUnknownSuperclass (GEOSearchExtras)
+(id)photoWithYelpUserJSON:(id)yelpUserJSON;
@end

@interface XXUnknownSuperclass (Maps)
+(id)mapsInternalExtrasBundle;
@end

@interface XXUnknownSuperclass (StarkLikelyRoute)
+(id)_coreroutine_stringForExpectedTraffic:(int)expectedTraffic;
@end
