/* ABPeoplePickerNavigationControllerPrivateDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import "ABPeoplePickerNavigationControllerDelegate.h"


@protocol ABPeoplePickerNavigationControllerPrivateDelegate <ABPeoplePickerNavigationControllerDelegate>
@optional
-(BOOL)peoplePickerNavigationController:(id)controller shouldAllowSelectingPersonWithRecordID:(int)recordID;
-(BOOL)peoplePickerNavigationController:(id)controller shouldContinueAfterSelectingPerson:(void*)person withLinkedPeople:(CFArrayRef)linkedPeople;
-(BOOL)peoplePickerNavigationControllerAllowsShowingPersonsCards:(id)cards;
@end
