/* AutoFetchController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import "AutoFetchController.h"
#import "MFContentProtectionObserver.h"
#import "PCConnectionManagerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSTimer, NSString, NSArray, PCConnectionManager, NSMutableDictionary, PCPersistentTimer;
@protocol AutoFetchControllerDataSource;

@protocol AutoFetchController
-(oneway void)networkConfigurationChanged;
-(oneway void)stopAutoFetch;
-(oneway void)fetchNow:(int)now withSources:(id)sources;
-(oneway void)fetchNow:(int)now withAccounts:(id)accounts;
-(oneway void)fetchNow:(int)now;
-(oneway void)startAutoFetch;
-(oneway void)setDataSource:(id)source;
@end

__attribute__((visibility("hidden")))
@interface AutoFetchController : XXUnknownSuperclass <AutoFetchController, MFContentProtectionObserver, PCConnectionManagerDelegate> {
	id<AutoFetchControllerDataSource> _dataSource;
	double _lastNonvisibleAutoFetchDate;
	PCConnectionManager* _manager;
	NSMutableDictionary* _accountResponsiveness;
	NSMutableSet* _uidsToFetchAfterFirstUnlock;
	PCPersistentTimer* _failedPushTimer;
	NSMutableSet* _failedPushUids;
	unsigned _outstandingAccountChangeFetchRequests;
	int _notifyLockStateToken;
	unsigned long long _holdState;
	unsigned _pmNotifier;
	IONotificationPortRef _pmPort;
	CFRunLoopSourceRef _pmSource;
	int _autoFetchState;
	int _fetchType;
	int _pendingFetchType;
	BOOL _lastAutoFetchHadErrors;
	BOOL _lastAutoFetchHadSources;
	NSArray* _fetchAccounts;
	NSArray* _pendingFetchAccounts;
	NSArray* _visibleSources;
	NSArray* _visibleSourceJobInvocations;
	unsigned _outstandingAutoFetchRequests;
	NSTimer* _networkWakeupTimeout;
	NSString* _firstNotifyingAccountID;
	unsigned _loudestState;
	unsigned _isReachable : 1;
	unsigned _monitoringReachability : 1;
	unsigned _tryFetchWhenReachable : 1;
	unsigned _PCTimerIsRunning : 1;
	unsigned _waitingForFirstUnlock : 1;
}
@property(assign, nonatomic) int autoFetchState;
+(id)sharedController;
-(void)_dumpDiagnosticInformation:(id)information;
-(void)contentProtectionStateChanged:(int)changed previousState:(int)state;
-(void)_finishAutoFetch;
-(void)_createJobListFinished:(id)finished;
-(void)_gatherAllFetchJobs;
-(void)_createJobList;
-(void)_reportSynchronousFetchCompletion:(id)completion;
-(void)_checkForWiFi;
-(BOOL)_shouldAutoFetchAccount:(id)account whenVisible:(BOOL)visible;
-(void)_checkForReachability;
-(oneway void)_reportReachabilityTimeout:(id)timeout;
-(void)_reportReachabilityChange:(id)change;
-(void)_cleanUpReachabilityTimer;
-(void)_startAutoFetch:(int)fetch withAccounts:(id)accounts;
-(void)_accountChangedFinished;
-(void)_failedPushTimerFired:(id)fired;
-(void)_clearFailedPushTimer;
-(void)_pushFetchCompleted:(id)completed;
-(void)_accountContentsDidChange:(id)_accountContents;
-(void)_fetchChangedUids:(id)uids forAccount:(id)account;
-(void)_fetchChangedUids:(id)uids forAccount:(id)account options:(int)options;
-(oneway void)networkConfigurationChanged;
-(void)_lockStateChanged;
-(oneway void)stopAutoFetch;
-(oneway void)startAutoFetch;
-(oneway void)fetchNow:(int)now withSources:(id)sources;
-(oneway void)fetchNow:(int)now withAccounts:(id)accounts;
-(oneway void)fetchNow:(int)now;
-(void)lockStateFetch;
-(BOOL)_tryFetch:(int)fetch withAccounts:(id)accounts;
-(BOOL)_tryFetch:(int)fetch;
-(void)_hasWokenUp;
-(int)_autoFetchOverrideInterval;
-(oneway void)setDataSource:(id)source;
-(void)dealloc;
-(void)startup;
-(id)init;
-(void)connectionManager:(id)manager handleEvent:(int)event;
-(void)handlePollEvent;
-(void)restartPCTimer;
-(void)_registerLockUnlockStateNotification;
@end
