/* BBObserverDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import "NSObject.h"


@protocol BBObserverDelegate <NSObject>
@optional
-(CGSize)observer:(id)observer composedAttachmentSizeForType:(int)type thumbnailWidth:(float)width height:(float)height key:(id)key;
-(id)observer:(id)observer composedAttachmentImageForType:(int)type thumbnailData:(id)data key:(id)key;
-(id)observer:(id)observer multipleThumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)observer;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(void)observer:(id)observer noteServerReceivedResponseForBulletin:(id)bulletin;
-(void)observer:(id)observer noteServerConnectionStateChanged:(BOOL)changed;
-(void)observer:(id)observer noteInvalidatedBulletinIDs:(id)ids;
-(void)observer:(id)observer noteAlertBehaviorOverridesChanged:(unsigned)changed;
-(void)observer:(id)observer purgeReferencesToBulletinID:(id)bulletinID;
-(void)observer:(id)observer noteSectionParametersChanged:(id)changed;
-(void)observer:(id)observer updateSectionInfo:(id)info;
-(void)observer:(id)observer updateSectionInfo:(id)info inCategory:(int)category;
-(void)observer:(id)observer updateSectionOrder:(id)order;
-(void)observer:(id)observer updateSectionOrder:(id)order forCategory:(int)category;
-(void)observer:(id)observer updateSectionOrderRule:(int)rule;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer modifyBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
@end
