/* EditFavoritesController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MailboxUtilsClient.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "AccountFavoritesPickerControllerDelegate.h"

@class NSArray, NSMutableArray;
@protocol EditFavoritesControllerDelegate;

__attribute__((visibility("hidden")))
@interface EditFavoritesController : XXUnknownSuperclass <AccountFavoritesPickerControllerDelegate, MailboxUtilsClient> {
	NSMutableArray* _selectedSmartMailboxes;
	NSMutableArray* _selectedFavoriteMailboxes;
	NSArray* _sortedAccounts;
	NSArray* _sortedMailboxes;
	id<EditFavoritesControllerDelegate> _delegate;
	BOOL _isSingleAccount;
}
@property(readonly, assign, nonatomic) NSArray* selectedFavoriteMailboxes;
@property(readonly, assign, nonatomic) NSArray* selectedSmartMailboxes;
@property(assign, nonatomic) id<EditFavoritesControllerDelegate> delegate;
@property(assign, nonatomic) BOOL isSingleAccount;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(void)didFinish;
-(BOOL)toggleAndReturnSelectedStateForMailbox:(id)mailbox;
-(BOOL)selectedStateForMailbox:(id)mailbox;
-(BOOL)shouldHideNotesForAccount:(id)account;
-(BOOL)shouldHideInbox;
-(void)shouldReloadMailboxesWithOutbox:(id)outbox;
-(void)doneButtonClicked:(id)clicked;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)dealloc;
-(id)init;
@end
