/* FavoriteItem_Mailbox.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "FavoriteItem.h"

@class MailAccount, MFMailboxUid, NSString;

__attribute__((visibility("hidden")))
@interface FavoriteItem_Mailbox : FavoriteItem {
	MFMailboxUid* _mailbox;
	MailAccount* _account;
	int _mailboxType;
	NSString* _accountRelativePath;
	NSString* _displayName;
	BOOL _originalPushState;
}
@property(retain, nonatomic) MFMailboxUid* mailbox;
@property(assign, nonatomic) BOOL originalPushState;
-(void)wasChangedExternally;
-(void)wasRemovedFromCollecion:(id)collecion;
-(void)wasAddedToCollection:(id)collection;
-(id)syncValue;
-(id)syncKey;
-(BOOL)doesSync;
-(void)wasSelected:(id)selected accessoryTapped:(BOOL)tapped;
-(id)representingMailbox;
-(id)_mailbox;
-(id)account;
-(void)configureCell:(id)cell;
-(int)_defaultCellAccessoryType;
-(BOOL)isDeletable;
-(BOOL)isVisible;
-(id)displayName;
-(id)dictionaryRepresentation;
-(id)initWithDictionary:(id)dictionary;
-(unsigned)hash;
-(BOOL)isEqual:(id)equal;
-(void)dealloc;
-(id)initWithMailbox:(id)mailbox;
@end
