/* MailboxContentSelectionModel.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol MailboxContentSelectionModelDataSource;

__attribute__((visibility("hidden")))
@interface MailboxContentSelectionModel : XXUnknownSuperclass {
	id<MailboxContentSelectionModelDataSource> _dataSource;
	CFDictionaryRef _selectedIndicesPerSection;
	CFDictionaryRef _indexToCountMappingPerSection;
	unsigned _messageCount;
	unsigned _conversationCount;
}
-(BOOL)updateSelectionInSection:(unsigned)section inserted:(id)inserted removed:(id)removed updated:(id)updated relocated:(id)relocated destination:(id)destination;
-(void)reselectIndexPathsWithTableView:(id)tableView;
-(void)deselectAllIndexPathsInTableView:(id)tableView;
-(void)select:(BOOL)select indicesInTableView:(id)tableView;
-(void)getSelectionStateHasUnread:(BOOL*)unread hasUnflagged:(BOOL*)unflagged hasNonJunk:(BOOL*)junk supportsFlagging:(BOOL*)flagging;
-(void)_getSelectionStateForSources:(id)sources hasNonJunk:(BOOL*)junk supportsFlagging:(BOOL*)flagging;
-(id)sourcesForSelectedMessages;
-(id)selectedMessagesBySection;
-(id)flaggableMessages;
-(id)selectedMessages;
-(void)deselectIndexPath:(id)path;
-(void)selectIndexPath:(id)path;
-(BOOL)isPathSelected:(id)selected;
-(CFDictionaryRef)_indexToCountMappingForSection:(unsigned)section create:(BOOL)create;
-(void)_enumerateSelectedIndexSections:(id)sections;
-(id)_selectedIndicesForSection:(unsigned)section create:(BOOL)create;
-(unsigned)conversationCount;
-(unsigned)messageCount;
-(void)clear;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource;
-(id)init;
@end
