/* MailNavigationController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIWindow, NSArray;

__attribute__((visibility("hidden")))
@interface MailNavigationController : XXUnknownSuperclass {
	NSArray* _previousViewControllers;
	BOOL _hasAppeared;
	BOOL _poppingFromLeft;
	BOOL _transferNavigationControllerShown;
	UIView* _frozenContentSnapshotView;
	UIWindow* _snapshotWindow;
}
-(void)unfreezeContent;
-(void)freezeContent;
-(void)resignPreparedForTransferOfMessages:(BOOL)messages;
-(void)becomePreparedForTransferOfMessages:(id)messages options:(int)options animated:(BOOL)animated;
-(void)removeChildViewController:(id)controller;
-(void)removeChildViewController:(id)controller notifyDidMove:(BOOL)notify;
-(void)removeViewController:(id)controller;
-(BOOL)isPopping;
-(void)didShowViewController:(id)controller animated:(BOOL)animated;
-(id)popToViewController:(id)viewController animated:(BOOL)animated;
-(id)popViewControllerAnimated:(BOOL)animated;
-(id)popViewControllersPushedFromLeftAnimated:(BOOL)leftAnimated;
-(void)_didPopFromLeft;
-(void)pushViewControllersFromLeft:(id)left animated:(BOOL)animated;
-(void)hideTransferNavigationControllerFromViewController:(id)viewController animated:(BOOL)animated;
-(void)showTransferNavigationController:(id)controller fromViewController:(id)viewController animated:(BOOL)animated;
-(BOOL)canShowTransferNavigationController;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(BOOL)shouldAutorotate;
-(void)dealloc;
@end
