/* MessageResponseContext.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MFMailMessage;

__attribute__((visibility("hidden")))
@interface MessageResponseContext : XXUnknownSuperclass {
	MFMailMessage* message;
	unsigned action;
	BOOL askedForReplyAll;
	BOOL askedForSendAgain;
	BOOL askedForSaveAllAttachments;
	BOOL loadRest;
	BOOL askingAboutPartial;
	BOOL askedAboutPartial;
	BOOL includeAttachments;
	BOOL askingAboutAttachments;
	BOOL askedAboutAttachments;
	BOOL askingAboutDelete;
	BOOL askingAboutDeleteOrArchive;
	BOOL showingSendEml;
	BOOL showingSaveHTML;
}
@end
