/* MFMailComposeDeliveryController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MFDeliveryDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, MFOutgoingMessageDelivery, MFMailboxUid, MFOutgoingMessage, MFMailMessage, MFError;
@protocol MailComposeDeliveryControllerDelegate, NSCoding;

__attribute__((visibility("hidden")))
@interface MFMailComposeDeliveryController : XXUnknownSuperclass <MFDeliveryDelegate> {
	id<MailComposeDeliveryControllerDelegate> _delegate;
	MFOutgoingMessageDelivery* _delivery;
	MFOutgoingMessage* _draftMessage;
	NSString* _sendingAddress;
	MFMailboxUid* _draftMailbox;
	NSString* _draftMessageID;
	MFMailMessage* _originalMessage;
	id<NSCoding> _autosaveIdentifier;
	MFError* _error;
	int _composeType;
}
@property(assign, nonatomic) int composeType;
@property(retain, nonatomic) MFMailMessage* originalMessage;
@property(retain, nonatomic) MFMailboxUid* draftMailbox;
@property(copy, nonatomic) NSString* draftMessageID;
@property(copy, nonatomic) NSString* sendingAddress;
@property(assign, nonatomic) id<MailComposeDeliveryControllerDelegate> delegate;
-(void)notifyUserDeliverySucceeded:(id)succeeded;
-(void)setPercentDone:(double)done;
-(void)_setCodePointTranslationEnabled:(BOOL)enabled;
-(void)_removeDraft;
-(id)error;
-(BOOL)deliverMessage;
-(void)dealloc;
-(id)_initWithDelivery:(id)delivery draftMessage:(id)message;
-(id)initWithComposeController:(id)composeController;
-(id)initWithDraftMessage:(id)draftMessage;
-(id)initWithDelivery:(id)delivery;
@end
