/* MFSearchAlternativePerson.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MFSearchAlternative.h"

@class NSSet, NSString;

__attribute__((visibility("hidden")))
@interface MFSearchAlternativePerson : MFSearchAlternative {
	NSString* _displayName;
	NSSet* _addresses;
}
+(id)alternativeWithOriginalText:(id)originalText displayName:(id)name addresses:(id)addresses;
-(id)criterion;
-(int)_criterionType;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)description;
-(void)dealloc;
-(id)initWithType:(unsigned)type originalText:(id)text;
-(id)initWithType:(unsigned)type originalText:(id)text displayName:(id)name addresses:(id)addresses;
@end
