/* MFSearchAlternativeTimePeriod.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MFSearchAlternative.h"

@class NSDateComponents;

__attribute__((visibility("hidden")))
@interface MFSearchAlternativeTimePeriod : MFSearchAlternative {
	NSDateComponents* _components;
	BOOL _relative;
}
+(id)alternativeWithOriginalText:(id)originalText dateComponents:(id)components relative:(BOOL)relative;
-(id)criterion;
-(void)dealloc;
-(id)initWithType:(unsigned)type originalText:(id)text;
-(id)initWithOriginalText:(id)originalText dateComponents:(id)components;
@end
