/* MFUserAgent.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */



@protocol MFUserAgent
-(BOOL)canRegisterForAPSPush;
-(BOOL)isAllowedToAccessProtectedData;
-(BOOL)isMobileMail;
-(BOOL)isForeground;
-(void)networkActivityEnded:(id)ended;
-(void)networkActivityStarted:(id)started;
-(void)autofetchAccount:(id)account mailboxUid:(id)uid;
-(id)focusedMessage;
-(BOOL)promptUserForPasswordWithTitle:(id)title message:(id)message account:(id)account completionHandler:(id)handler;
@end
