/* NSLayoutManagerDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import "NSObject.h"


@protocol NSLayoutManagerDelegate <NSObject>
@optional
-(void)layoutManager:(id)manager textContainer:(id)container didChangeGeometryFromSize:(CGSize)size;
-(void)layoutManager:(id)manager didCompleteLayoutForTextContainer:(id)textContainer atEnd:(BOOL)end;
-(void)layoutManagerDidInvalidateLayout:(id)layoutManager;
-(CGRect)layoutManager:(id)manager boundingBoxForControlGlyphAtIndex:(unsigned)index forTextContainer:(id)textContainer proposedLineFragment:(CGRect)fragment glyphPosition:(CGPoint)position characterIndex:(unsigned)index6;
-(BOOL)layoutManager:(id)manager shouldBreakLineByHyphenatingBeforeCharacterAtIndex:(unsigned)index;
-(BOOL)layoutManager:(id)manager shouldBreakLineByWordBeforeCharacterAtIndex:(unsigned)index;
-(int)layoutManager:(id)manager shouldUseAction:(int)action forControlCharacterAtIndex:(unsigned)index;
-(float)layoutManager:(id)manager paragraphSpacingAfterGlyphAtIndex:(unsigned)index withProposedLineFragmentRect:(CGRect)proposedLineFragmentRect;
-(float)layoutManager:(id)manager paragraphSpacingBeforeGlyphAtIndex:(unsigned)index withProposedLineFragmentRect:(CGRect)proposedLineFragmentRect;
-(float)layoutManager:(id)manager lineSpacingAfterGlyphAtIndex:(unsigned)index withProposedLineFragmentRect:(CGRect)proposedLineFragmentRect;
-(unsigned)layoutManager:(id)manager shouldGenerateGlyphs:(const unsigned short*)glyphs properties:(const int*)properties characterIndexes:(const unsigned*)indexes font:(id)font forGlyphRange:(NSRange)glyphRange;
@end
