/* PreviousDraftPickerHeaderView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface PreviousDraftPickerHeaderView : XXUnknownSuperclass {
	UILabel* _label;
	UIActivityIndicatorView* _activityIndicatorView;
	BOOL _hasDrafts;
	BOOL _loading;
	BOOL _completedFirstLoad;
}
-(void)updateUI;
-(void)setLoading:(BOOL)loading;
-(void)setHasDrafts:(BOOL)drafts;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
