/* ThreadBannerView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIDateLabel, UILabel;

__attribute__((visibility("hidden")))
@interface ThreadBannerView : XXUnknownSuperclass {
	UILabel* _subjectLabel;
	UIDateLabel* _dateLabel;
}
+(float)defaultHeaderHeight;
-(void)setTableView:(id)view;
-(void)setDateWithMessage:(id)message;
-(void)setText:(id)text;
-(id)_label:(BOOL)label;
-(void)layoutSubviews;
-(CGRect)rectForDateWithBounds:(CGRect)bounds;
-(CGRect)rectForSubjectWithBounds:(CGRect)bounds;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
