/* TransferMailboxPickerDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileMail-Structs.h"
#import "NSObject.h"


@protocol TransferMailboxPickerDelegate <NSObject>
-(void)transferMailboxPickerControllerDidFinish:(id)transferMailboxPickerController animated:(BOOL)animated;
-(void)transferMailboxPickerController:(id)controller didSelectMailbox:(id)mailbox withMessages:(id)messages;
@optional
-(id)transferMailboxPickerController:(id)controller viewForMessage:(id)message;
-(void)transferMailboxPickerController:(id)controller animateMessageToThumbnailFrame:(CGRect)thumbnailFrame inView:(id)view completion:(id)completion;
-(void)transferMailboxPickerController:(id)controller animateMessageToPoint:(CGPoint)point inView:(id)view didFinishDelegate:(id)delegate selector:(SEL)selector context:(id)context;
@end
