/* MainController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UISnapshotView, UIView;

__attribute__((visibility("hidden")))
@interface MainController : XXUnknownSuperclass {
	UISnapshotView* _fakeStatusBar;
	UIView* _tabControllerView;
}
@property(retain, nonatomic) UIView* tabControllerView;
-(void)viewDidLayoutSubviews;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)dealloc;
@end
