/* MTStopwatchControlsView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MTCircleButton, UIView, StopwatchTimeView;
@protocol StopWatchControlsTarget;

__attribute__((visibility("hidden")))
@interface MTStopwatchControlsView : XXUnknownSuperclass {
	MTCircleButton* _leftButton;
	MTCircleButton* _rightButton;
	UIView* _buttonsBackgroundView;
	UIView* _topKeylineView;
	UIView* _bottomKeylineView;
	int _mode;
	id<StopWatchControlsTarget> _target;
	StopwatchTimeView* _timeView;
}
@property(readonly, assign, nonatomic) StopwatchTimeView* timeView;
@property(readonly, assign, nonatomic) id<StopWatchControlsTarget> target;
@property(assign, nonatomic) int mode;
+(float)defaultHeight;
-(void)layoutSubviews;
-(void)_updateButtons;
-(void)rightButtonPressed:(id)pressed;
-(void)leftButtonPressed:(id)pressed;
-(void)handleLocaleChange;
-(id)_newLapControlButtonWithAction:(SEL)action color:(unsigned)color;
-(void)dealloc;
-(id)initWithTarget:(id)target;
@end
