/* MFDownloadPluginView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MailAttachmentPlugin-Structs.h"
#import "MFMailAttachmentDownloadProgressDisplay.h"
#import "MFMailAttachmentPlugin.h"

@class NSString, UIImageView;

@interface MFDownloadPluginView : MFMailAttachmentPlugin <MFMailAttachmentDownloadProgressDisplay> {
	UIImageView* _spinny;
	NSString* _totalString;
	unsigned _totalSize;
	unsigned _shouldDrawCutout : 1;
	unsigned _shouldUseHiResArtwork : 1;
	unsigned _handlingTap : 1;
	unsigned _downloadInitiatedByUser : 1;
}
-(BOOL)isScalable;
-(void)drawRect:(CGRect)rect;
-(void)prepareUI;
-(id)newFilenameViewWithSettings:(id)settings textColor:(id)color maxWidth:(float)width;
-(id)newImageWithSettings:(id)settings;
-(void)downloadProgressDidUpdatePercentageComplete:(float)downloadProgress;
-(void)_resize;
-(void)layoutSubviews;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)_handleTap:(id)tap;
-(void)dealloc;
-(BOOL)downloadInitiatedByUser;
-(void)downloadProgressDidCancel;
-(void)downloadProgressDidStart;
-(void)stopSpinny;
-(void)startSpinny;
-(void)setHighlighted:(BOOL)highlighted;
-(id)initWithFrame:(CGRect)frame arguments:(id)arguments;
@end
