/* MFMailAttachmentPlugInDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MailAttachmentPlugin-Structs.h"
#import "NSObject.h"


@protocol MFMailAttachmentPlugInDelegate <NSObject>
@optional
-(void)attachment:(id)attachment displayMenuFromRect:(CGRect)rect iconRect:(CGRect)rect3 inView:(id)view;
-(void)attachment:(id)attachment displayViewerFromRect:(CGRect)rect inView:(id)view;
-(void)attachment:(id)attachment didFinishDownloadWithProgress:(id)progress;
-(void)attachment:(id)attachment cancelDownloadWithProgress:(id)progress;
-(void)attachment:(id)attachment startDownloadWithProgress:(id)progress;
-(id)attachment:(id)attachment iconForSize:(CGSize)size;
@end
