/* MFPrintingPluginView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MailAttachmentPlugin-Structs.h"
#import "MFMailAttachmentPlugin.h"


@interface MFPrintingPluginView : MFMailAttachmentPlugin {
}
-(void)drawRectForPrinting:(CGRect)printing;
-(void)_printView:(id)view;
-(void)prepareUI;
-(void)layoutSubviews;
-(id)newFilesizeViewWithSize:(id)size;
-(id)newFilenameViewWithSettings:(id)settings;
-(id)documentIcon;
@end
