/* TESettingsController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "ACUIAppInstallerDelegate.h"

@class ACAccountType, ACAccount, NSArray, NSMutableDictionary, PSSpecifier, ACUIAppInstaller, SLNetworkReachabilityWarning;

@interface TESettingsController : XXUnknownSuperclass <ACUIAppInstallerDelegate> {
	ACAccountType* _tencentWeiboAccountType;
	ACAccount* _signInAccount;
	NSArray* _accounts;
	NSMutableDictionary* _authorizedAppList;
	NSArray* _accountStateDependentSpecifiers;
	NSArray* _authorizedAppListSpecifiers;
	PSSpecifier* _signInButtonSpecifier;
	PSSpecifier* _updateContactsSpecifier;
	ACUIAppInstaller* _tencentWeiboAppInstaller;
	SLNetworkReachabilityWarning* _networkWarning;
}
-(void).cxx_destruct;
-(void)_learnMoreLinkButtonTapped:(id)tapped;
-(id)_tencentWeiboAccountType;
-(void)_accountStoreDidChange:(id)_accountStore;
-(void)_willEnterForeground:(id)foreground;
-(void)_accountCreated:(id)created;
-(void)_createNewAccountButtonTapped:(id)tapped;
-(void)_updateSignInButton;
-(void)_textFieldValueDidChange:(id)_textFieldValue;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)appInstallerWillStart:(id)appInstaller;
-(id)_tencentWeiboApp;
-(id)_tencentWeiboAppInstaller;
-(void)_updateInstallCell:(id)cell;
-(void)_installButtonTapped:(id)tapped;
-(void)_showAppDownloadAlert;
-(void)_setAppAllowedAccess:(id)access withSpecifier:(id)specifier;
-(id)_isAppAllowedAccountAccessWithSpecifier:(id)specifier;
-(void)_reloadAuthorizedAppList;
-(void)_handleAccountAuthenticationWithResult:(BOOL)result error:(id)error;
-(void)_signInButtonTapped:(id)buttonTapped;
-(void)setPassword:(id)password;
-(void)setUsername:(id)username;
-(id)_passwordWithSpecifier:(id)specifier;
-(void)_setPassword:(id)password withSpecifier:(id)specifier;
-(id)_usernameWithSpecifier:(id)specifier;
-(void)_setUsername:(id)username withSpecifier:(id)specifier;
-(id)_learnMoreLinkSpecifier;
-(id)_installWeiboCellSpecifier;
-(id)_createNewAccountButtonSpecifier;
-(id)_specifierForAccount:(id)account;
-(id)_authorizedAppsListSpecifiers;
-(id)_loginSpecifiers;
-(id)_accountListSpecifiers;
-(id)_noAccountsSpecifiers;
-(id)specifiers;
-(void)_stopObservingAccountStoreDidChangeNotification;
-(void)_beginObservingAccountStoreDidChangeNotification;
-(void)returnPressedAtEnd;
-(id)_networkWarning;
-(void)viewWillAppear:(BOOL)view;
-(id)navigationItem;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end
