/* AirTrafficSettingsHostCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UILabel;

@interface AirTrafficSettingsHostCell : XXUnknownSuperclass {
	UILabel* _syncedClassesLabel;
	UILabel* _timestampLabel;
	NSString* _syncedClassesText;
	NSString* _timestampText;
	float _textWidth;
}
@property(assign, nonatomic) float textWidth;
@property(retain, nonatomic) NSString* timestampText;
@property(retain, nonatomic) NSString* syncedClassesText;
-(void)dealloc;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)layoutSubviews;
-(void)refreshCellContentsWithSpecifier:(id)specifier;
-(BOOL)canReload;
@end
