/* ServiceProductPageComposeReviewViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "SKUIComposeReviewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SKUIComposeReviewViewController, ServiceProductPageViewController;

__attribute__((visibility("hidden")))
@interface ServiceProductPageComposeReviewViewController : XXUnknownSuperclass <SKUIComposeReviewDelegate> {
	ServiceProductPageViewController* _parentProductPageViewController;
	SKUIComposeReviewViewController* _underlyingViewController;
}
@property(assign, nonatomic) __weak ServiceProductPageViewController* parentProductPageViewController;
-(void)composeReviewViewControllerDidSubmit:(id)composeReviewViewController;
-(void)composeReviewViewControllerDidCancel:(id)composeReviewViewController;
-(BOOL)composeReviewViewController:(id)controller shouldSubmitReview:(id)review;
-(void)loadView;
-(void)setClientInterface:(id)interface;
-(void)prepareWithCompletionBlock:(id)completionBlock;
-(void)dealloc;
@end
