/* ASLaunchNotificationsController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SKUILoadURLOperation, UIViewController, NSOperationQueue, SKUIClientContext, ASApplePackPage;

__attribute__((visibility("hidden")))
@interface ASLaunchNotificationsController : XXUnknownSuperclass {
	SKUILoadURLOperation* _applePackOperation;
	ASApplePackPage* _applePackPage;
	SKUIClientContext* _clientContext;
	BOOL _didDisplayThisRunCycle;
	NSOperationQueue* _operationQueue;
	UIViewController* _parentViewController;
}
@property(retain, nonatomic) SKUIClientContext* clientContext;
-(void).cxx_destruct;
-(void)_setApplePackDisplayed:(BOOL)displayed;
-(void)_setApplePack:(id)pack error:(id)error;
-(void)_reloadApplePackPage;
-(void)_loadApplePack;
-(BOOL)_hasDisplayedApplePack;
-(void)_displayApplePack;
-(void)_applicationDidEnterBackground:(id)_application;
-(void)itemStateCenterRestrictionsChanged:(id)changed;
-(void)displayAvailableNotifications;
-(void)checkForNotifications;
-(void)dealloc;
-(id)initWithParentViewController:(id)parentViewController;
@end
