/* ASPurchasedHeaderView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AppStore-Structs.h"

@class UIControl, NSString, SKUIClientContext, UISegmentedControl, UISearchBar, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface ASPurchasedHeaderView : XXUnknownSuperclass {
	SKUIClientContext* _clientContext;
	UISegmentedControl* _filterLocalAppsControl;
	UISearchBar* _searchBar;
	BOOL _searchBarHidden;
	UIButton* _sortButton;
	UILabel* _sortByLabel;
}
@property(assign, nonatomic, getter=isSearchBarHidden) BOOL searchBarHidden;
@property(readonly, assign, nonatomic) UISearchBar* searchBar;
@property(copy, nonatomic) NSString* sortTypeTitle;
@property(readonly, assign, nonatomic) UIControl* sortTypeControl;
@property(assign, nonatomic) BOOL filtersLocalApps;
@property(readonly, assign, nonatomic) UIControl* filterLocalAppsControl;
@property(retain, nonatomic) SKUIClientContext* clientContext;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame;
@end
