/* ASUpdateCellLayout.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "AppStore-Structs.h"

@class UILabel, NSString, SKUITextBoxView;

__attribute__((visibility("hidden")))
@interface ASUpdateCellLayout : XXUnknownSuperclass {
	BOOL _isIPad;
	UILabel* _lastUpdateDateLabel;
	BOOL _showsWhatsNewButton;
	UILabel* _titleLabel;
	long long _versionIdentifier;
	UILabel* _versionLabel;
	UILabel* _whatsNewButtonLabel;
	SKUITextBoxView* _whatsNewTextBox;
	float _whatsNewWidth;
}
@property(assign, nonatomic) float whatsNewWidth;
@property(copy, nonatomic) NSString* versionString;
@property(assign, nonatomic) long long versionIdentifier;
@property(copy, nonatomic) NSString* title;
@property(assign, nonatomic) BOOL showsWhatsNewButton;
@property(copy, nonatomic) NSString* lastUpdateDateString;
-(void).cxx_destruct;
-(id)_whatsNewButtonLabel;
-(unsigned)_adjustedStateFlagForItemState:(id)itemState;
-(void)setItemState:(id)state animated:(BOOL)animated;
-(void)layoutForItemOfferChange;
-(void)setBackgroundColor:(id)color;
-(void)layoutSubviews;
-(void)setWhatsNewWithTextFrame:(CTFrameRef)textFrame numberOfVisibleLines:(int)visibleLines;
-(id)initWithTableViewCell:(id)tableViewCell;
-(id)initWithCollectionViewCell:(id)collectionViewCell;
@end
