/* PHSettingsBlacklistBundleController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <Foundation/NSNumber.h>

@class NSArray;

@interface PHSettingsBlacklistBundleController : NSNumber {
	NSArray* _specifiersArray;
}
@property(retain, nonatomic) NSArray* specifiersArray;
-(void)dealloc;
-(id)specifiersWithSpecifier:(id)specifier;
@end
