/* BackForwardView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WebSheet-Structs.h"

@class WebSheetView, UIButton;

__attribute__((visibility("hidden")))
@interface BackForwardView : XXUnknownSuperclass {
	UIButton* _backButton;
	UIButton* _forwardButton;
	WebSheetView* _webSheet;
}
@property(assign, nonatomic) WebSheetView* webSheet;
-(void)forwardButtonPressed;
-(void)backButtonPressed;
-(void)updateButtons;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
-(id)_newNavigationButtonWithImage:(id)image action:(SEL)action;
@end
