/* WebSheet.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "WebSheet-Structs.h"
#import "WebSheetView.h"
#import "XXUnknownSuperclass.h"
#import "BackForwardView.h"
#import "WebSheetAppDelegate.h"
#import "UIWebViewDelegate.h"
#import "UIWebViewPrivateDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIApplicationDelegate.h"
#import "NSObject.h"
