/* PLInteractiveNavigationControllerDelegate.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol PLInteractiveNavigationControllerDelegate <NSObject>
@optional
-(void)interactiveNavigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)interactiveNavigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
@end
