/* VideosRentalErrorResolver.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class VideosRentalAlertView, NSError, VideosRentalData;

__attribute__((visibility("hidden")))
@interface VideosRentalErrorResolver : XXUnknownSuperclass <UIAlertViewDelegate> {
	NSError* _error;
	VideosRentalAlertView* _playbackAlertView;
	VideosRentalData* _rentalData;
}
-(void).cxx_destruct;
-(id)_mediaItem;
-(BOOL)_errorIsFairPlayError:(id)error;
-(void)_destroyPlaybackAlertView;
-(void)_cancelPlaybackAlertView:(BOOL)view;
-(void)_rentalDataDidLoadNotification:(id)_rentalData;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)alertViewCancel:(id)cancel;
-(void)resolveError:(id)error;
-(void)dealloc;
-(id)initWithMediaItem:(id)mediaItem;
-(id)init;
@end
