/* VideosTableViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "VideosTableCellDelegate.h"

@class VideosTableHeaderView;

__attribute__((visibility("hidden")))
@interface VideosTableViewController : XXUnknownSuperclass <VideosTableCellDelegate> {
	VideosTableHeaderView* _headerView;
}
-(void).cxx_destruct;
-(void)_updatePrompt;
-(void)_updateNavigationBarButtons;
-(void)_allowsDeletionDidChange:(id)_allowsDeletion;
-(void)selectItem:(id)item animated:(BOOL)animated;
-(void)tableCellWantsToCancelCloudDownload:(id)cancelCloudDownload;
-(void)tableCellWantsCloudDownload:(id)download;
-(id)viewForHeaderInTableView:(id)tableView;
-(float)heightForHeaderInTableView:(id)tableView;
-(id)_createTableView;
-(void)dataSourceDidInvalidate;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view shouldHighlightRowAtIndexPath:(id)indexPath;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)contentScrollView;
-(void)dealloc;
-(id)initWithDataSource:(id)dataSource cellConfigurationClass:(Class)aClass;
@end
