/* VideosTableCell.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class VideosDownloadProgress, UIImageView, MPCloudDownloadButton, UIColor, NSString, UILabel, MPMediaItemImageRequest, MPMediaDownloadObserver;
@protocol VideosTableCellDelegate;

__attribute__((visibility("hidden")))
@interface VideosTableCell : XXUnknownSuperclass {
	MPMediaItemImageRequest* _imageRequest;
	MPMediaDownloadObserver* _downloadObserver;
	BOOL _usesUnplayedIndicator;
	BOOL _cloud;
	id<VideosTableCellDelegate> _delegate;
	int _playedState;
	float _artworkWidth;
	UIImageView* _artworkView;
	UIImageView* _unplayedIndicator;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	MPCloudDownloadButton* _cloudButton;
	VideosDownloadProgress* _progressButton;
}
@property(readonly, assign, nonatomic) UIColor* imageBackgroundColor;
@property(readonly, assign, nonatomic) VideosDownloadProgress* progressButton;
@property(readonly, assign, nonatomic) MPCloudDownloadButton* cloudButton;
@property(readonly, assign, nonatomic) UILabel* subtitleLabel;
@property(readonly, assign, nonatomic) UILabel* titleLabel;
@property(readonly, assign, nonatomic) UIImageView* unplayedIndicator;
@property(readonly, assign, nonatomic) UIImageView* artworkView;
@property(assign, nonatomic) float artworkWidth;
@property(assign, nonatomic) BOOL cloud;
@property(assign, nonatomic) int playedState;
@property(assign, nonatomic) BOOL usesUnplayedIndicator;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) NSString* title;
@property(assign, nonatomic) __weak id<VideosTableCellDelegate> delegate;
-(void).cxx_destruct;
-(void)_cancelDownload:(id)download;
-(void)_download:(id)download;
-(void)updateWithDownloadObserver:(id)downloadObserver forMediaItem:(id)mediaItem;
-(void)setArtworkImage:(id)image;
-(void)loadImageWithRequest:(id)request inCache:(id)cache;
-(void)prepareForReuse;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end
