/* VideosAVItem.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface VideosAVItem : XXUnknownSuperclass {
}
-(id)_mediaSelectionOptionFromGroup:(id)group withTrackID:(int)trackID;
-(id)_fallbackAudioOptionFromOptions:(id)options locale:(id)locale strict:(BOOL)strict;
-(void)setupPlaybackInfo;
-(void)handlePlaybackFinishedTime:(double)time finishedByHittingEnd:(BOOL)end;
@end
