/* VideosRentalDataStore.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSOperationQueue, NSMutableDictionary, ML3QueryResultSet, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface VideosRentalDataStore : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _dispatchQueue;
	NSMutableSet* _localNotifications;
	NSOperationQueue* _operationQueue;
	int _pendingRentalEventCount;
	NSMutableDictionary* _rentalDataByPID;
	ML3QueryResultSet* _resultSet;
	BOOL _shouldReloadRentalData;
}
+(id)existingInstance;
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)_scheduleRentalEvents;
-(void)_resetLocalNotifications;
-(id)_rentalDataForMediaItem:(id)mediaItem;
-(void)_loadRentalDataFromLibrary;
-(id)_rentalItems;
-(BOOL)_isLoadingRentalData:(id)data;
-(void)_handleFinishedOperation:(id)operation;
-(void)_enqueueOperation:(id)operation;
-(void)_libraryDisplayValuesDidChange:(id)_libraryDisplayValues;
-(void)_libraryDidChangeNotification:(id)_library;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)resetRentalDataForMediaItem:(id)mediaItem reason:(unsigned)reason;
-(void)resetAllDataForReason:(unsigned)reason;
-(id)rentalDataForMediaItem:(id)mediaItem;
-(void)loadRentalDataFromLibrary;
-(void)loadRentalData:(id)data withReason:(int)reason;
-(BOOL)handleLocalNotification:(id)notification;
-(void)dealloc;
-(id)init;
@end
