/* BuddyLocationController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Setup-Structs.h"

@class NSSet, NSDictionary, NSArray;

__attribute__((visibility("hidden")))
@interface BuddyLocationController : XXUnknownSuperclass {
	BOOL _guessedCountryFromTelephony;
	NSArray* _guessedCountries;
	NSDictionary* _aliasDict;
	NSSet* _validCountries;
	WiFiManagerClient* fWifiManager;
	WiFiDeviceClient* fWifiDevice;
}
@property(retain, nonatomic) NSArray* guessedCountries;
+(id)sharedBuddyLocationController;
-(void)reset;
-(void)dealloc;
-(void)_closeWifiConnection;
-(void)_scanComplete:(id)complete error:(BOOL)error;
-(void)_startWifiScan;
-(id)guessedLanguages;
-(BOOL)getCountryFromTelephony;
-(BOOL)guessedCountryFromTelephony;
-(id)init;
-(void)_setGuessedCountryDefault:(id)aDefault;
-(id)_countriesFromDefaults;
-(id)_checkedArrayForString:(id)string;
-(id)_checkForAliasesOrInvalid:(id)aliasesOrInvalid;
-(id)_checkForAliases:(id)aliases;
-(id)aliasDict;
-(id)_countryFromTelephony;
@end
