/* BuddySwitchPage.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Setup-Structs.h"
#import "BuddyTableViewController.h"
#import "BuddyController.h"

@class UIButton, UISwitch, UILabel, UIImage, NSString, UITableViewCell;

__attribute__((visibility("hidden")))
@interface BuddySwitchPage : BuddyTableViewController <BuddyController> {
	UIButton* _whatIsButton;
	UITableViewCell* _tableCell;
	id _delegate;
	UISwitch* _switch;
	NSString* _cellLabel;
	UIImage* _cellImage;
	UILabel* _infoLabel;
	UISwitch* _switchButton;
}
@property(readonly, assign, nonatomic) UISwitch* switchButton;
@property(retain, nonatomic) UIImage* cellImage;
@property(retain, nonatomic) NSString* cellLabel;
+(float)infoLabelFontSize;
+(float)infoLabelTopMargin;
+(void)initialize;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)viewDidLayoutSubviews;
-(void)layoutOneLabel:(id)label yOrigin:(float)origin constrict:(BOOL)constrict;
-(void)dealloc;
-(void)setDelegate:(id)delegate;
-(void)_whatIsPressed;
-(void)donePressed;
-(id)initWithLabelText:(id)labelText infoText:(id)text numberOfLines:(int)lines;
-(id)initWithLabelText:(id)labelText infoText:(id)text;
@end
