/* BuddyCloudConfigDisclosureViewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Setup-Structs.h"
#import "SetupChoiceController.h"

@class SetupChoice, BuddyLabelAndLinkFooterView, UILabel, UINavigationController, NSError, BuddyCloudConfigController, BuddyCloudConfigAboutConfigurationContainerController;

__attribute__((visibility("hidden")))
@interface BuddyCloudConfigDisclosureViewController : SetupChoiceController {
	BOOL _isMandatory;
	BuddyCloudConfigController* _configController;
	NSError* _lastRetrievalError;
	UILabel* _disclosureLabel;
	BuddyLabelAndLinkFooterView* _footer;
	SetupChoice* _acceptChoice;
	SetupChoice* _skipChoice;
	UINavigationController* _aboutController;
	BuddyCloudConfigAboutConfigurationContainerController* _aboutConfigurationContainerController;
}
@property(retain, nonatomic) BuddyCloudConfigAboutConfigurationContainerController* aboutConfigurationContainerController;
@property(assign, nonatomic) UINavigationController* aboutController;
@property(assign, nonatomic) BOOL isMandatory;
@property(retain, nonatomic) SetupChoice* skipChoice;
@property(retain, nonatomic) SetupChoice* acceptChoice;
@property(retain, nonatomic) BuddyLabelAndLinkFooterView* footer;
@property(retain, nonatomic) UILabel* disclosureLabel;
@property(retain, nonatomic) NSError* lastRetrievalError;
@property(assign, nonatomic) BuddyCloudConfigController* configController;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)showAboutConfiguration:(id)configuration;
-(void)controllerDone;
-(void)_retrieveEnterpriseConfiguration;
-(void)dealloc;
-(void)viewDidLayoutSubviews;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)_setupForCloudConfigurationState;
-(id)init;
@end
