/* iForgotView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "Setup-Structs.h"
#import "UIWebViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIToolbar, UIWebView, UIAlertView;

__attribute__((visibility("hidden")))
@interface iForgotView : XXUnknownSuperclass <UIWebViewDelegate> {
	UIToolbar* _toolbar;
	UIWebView* _webView;
	BOOL _loaded;
	BOOL _dismissed;
	BOOL _needLoadingIndicator;
	UIAlertView* _failedToConnectAlert;
}
@property(readonly, assign, nonatomic) BOOL needLoadingIndicator;
-(void)dealloc;
-(void)webView:(id)view didFailLoadWithError:(id)error;
-(void)webViewDidFinishLoad:(id)webView;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)_showiForgotFailure:(id)failure;
-(void)layoutSubviews;
-(void)donePressed:(id)pressed;
-(void)_iForgotConnect:(id)connect;
-(void)willDismiss;
-(void)load;
-(id)initWithFrame:(CGRect)frame;
@end
