/* RestoreProgressController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "BuddyController.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class RestoreFromBackupController;

__attribute__((visibility("hidden")))
@interface RestoreProgressController : XXUnknownSuperclass <BuddyController> {
	RestoreFromBackupController* _restoreFromBackupController;
}
-(void)viewDidAppear:(BOOL)view;
-(void)setDelegate:(id)delegate;
-(void)setRestoreFromBackupController:(id)backupController;
@end
