/* SLFacebookSettingsController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SLFacebookRegistrationBuddyDelegate.h"
#import "SLFacebookLoginInfoViewControllerDelegate.h"
#import "SLFacebookContactUpaterDelegate.h"
#import "ACUIAppInstallerDelegate.h"

@class ACAccountType, ACUIAppInstaller, UIAlertView, NSObject, SLFacebookContactUpdater, NSDictionary, SLFacebookUpdateContactsFooterView, ACAccount, NSString, PSSpecifier, PSSetupController, SLFacebookRegistrationBuddy;
@protocol OS_dispatch_queue;

@interface SLFacebookSettingsController : XXUnknownSuperclass <SLFacebookRegistrationBuddyDelegate, SLFacebookLoginInfoViewControllerDelegate, SLFacebookContactUpaterDelegate, ACUIAppInstallerDelegate> {
	PSSpecifier* _signInButtonSpecifier;
	PSSpecifier* _updateContactsSpecifier;
	ACAccount* _account;
	ACAccountType* _facebookAccountType;
	NSString* _email;
	NSString* _password;
	PSSetupController* _loginInfoViewControllerWrapper;
	SLFacebookUpdateContactsFooterView* _updateContactsFooterView;
	ACUIAppInstaller* _facebookAppInstaller;
	SLFacebookRegistrationBuddy* _registrationBuddy;
	SLFacebookContactUpdater* _contactUpdater;
	UIAlertView* _appInstallAlert;
	BOOL _shouldPresentSignInInfo;
	BOOL _userWantsToMergeContacts;
	BOOL _isSavingNewAccount;
	NSObject<OS_dispatch_queue>* _accessQueue;
	NSDictionary* _accessList;
	int _mode;
}
@property(assign, nonatomic) int mode;
-(void).cxx_destruct;
-(void)_learnMoreLinkButtonTapped:(id)tapped;
-(void)_showErrorMessage:(id)message withTitle:(id)title;
-(void)_fetchNameForAccount:(id)account;
-(id)_facebookAccountType;
-(void)_accountStoreDidChange:(id)_accountStore;
-(void)_stopObservingAccountStoreDidChangeNotification;
-(void)_beginObservingAccountStoreDidChangeNotification;
-(BOOL)_isFacebookParentalRestrictionEnabled;
-(id)_accessList;
-(void)_setAppAllowedAccess:(id)access withSpecifier:(id)specifier;
-(id)_isAppAllowedAccountAccessWithSpecifier:(id)specifier;
-(BOOL)_confirmContactsMerge;
-(id)operationsHelper:(id)helper desiredDataclassActionFromPicker:(id)picker;
-(void)operationsHelper:(id)helper didRemoveAccount:(id)account withSuccess:(BOOL)success error:(id)error;
-(void)operationsHelper:(id)helper willRemoveAccount:(id)account;
-(void)_confirmAccountDeletion;
-(void)_deleteButtonTapped:(id)tapped;
-(void)contactUpdater:(id)updater didFinishUpdatingContacts:(int)contacts;
-(void)contactUpdater:(id)updater didUpdateProgress:(float)progress;
-(void)_cancelUpdateContactsTapped:(id)tapped;
-(void)_updateContactsTapped:(id)tapped;
-(void)registrationBuddy:(id)buddy didFailWithErrorCode:(int)errorCode;
-(void)registrationBuddy:(id)buddy didCompleteWithUsername:(id)username password:(id)password;
-(void)registrationBuddyDidCancel:(id)registrationBuddy;
-(id)presentingViewControllerforRegistrationBuddy:(id)buddy;
-(void)_createNewAccountButtonTapped:(id)tapped;
-(void)_handleAccountAuthenticationWithResult:(BOOL)result error:(id)error;
-(void)operationsHelper:(id)helper didSaveAccount:(id)account withSuccess:(BOOL)success error:(id)error;
-(void)_authenticateAndAddAccount;
-(void)loginInfoViewController:(id)controller userDidProvideConsent:(BOOL)user;
-(void)_dismissLegalPrompt;
-(void)_presentLegalPrompt;
-(void)_updateDoneButton;
-(void)_updateSignInButton;
-(void)_textFieldValueDidChange:(id)_textFieldValue;
-(void)doneButtonTapped:(id)tapped;
-(void)_signInButtonSpecifierTapped:(id)buttonSpecifierTapped;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)appInstallerWillStart:(id)appInstaller;
-(id)_facebookApp;
-(id)_facebookAppInstaller;
-(void)_updateInstallCell:(id)cell;
-(void)_installButtonTapped:(id)tapped;
-(void)_showAppDownloadAlert;
-(id)_isDataclassEnabledWithSpecifier:(id)specifier;
-(void)_setDataclassEnabled:(id)enabled withSpecifier:(id)specifier;
-(void)setPassword:(id)password;
-(void)setUsername:(id)username;
-(id)_passwordWithSpecifier:(id)specifier;
-(void)_setPassword:(id)password withSpecifier:(id)specifier;
-(id)_usernameWithSpecifier:(id)specifier;
-(void)_setUsername:(id)username withSpecifier:(id)specifier;
-(id)_passwordSpecifier;
-(id)_loginSpecifiers;
-(id)_specifierForAccount:(id)account;
-(id)_facebookAppSettingsSpecifier;
-(id)_createNewAccountSpecifier;
-(id)_learnMoreLinkGroup;
-(id)_installFacebookSpecifiers;
-(id)_authorizedAppsListSpecifiers;
-(id)_dataclassSpecifiers;
-(id)_specifiersForMergingContacts;
-(id)_specifiersForVerificationMode;
-(id)_specifiersForAccountMode;
-(id)_specifiersForNoAccountMode;
-(void)_willEnterForeground:(id)foreground;
-(void)returnPressedAtEnd;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)_updateViewMode;
-(id)_loadFreshSpecifiers;
-(id)specifiers;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)shouldReloadSpecifiersOnResume;
-(id)navigationItem;
-(void)dealloc;
-(id)init;
@end
