/* SLFacebookMergeContactsFooterView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "PSHeaderFooterView.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIActivityIndicatorView;

@interface SLFacebookMergeContactsFooterView : XXUnknownSuperclass <PSHeaderFooterView> {
	UIActivityIndicatorView* _activityIndicator;
	UILabel* _footerLabel;
}
-(void).cxx_destruct;
-(float)preferredHeightForWidth:(float)width;
-(void)layoutSubviews;
-(id)initWithSpecifier:(id)specifier;
@end
