/* RemindersCardStackView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import "Reminders-Structs.h"
#import "RemindersCardViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, NSMutableArray, NSMutableDictionary, RemindersCardController, NSTimer;
@protocol UIScrollViewDelegate, RemindersCardStackViewDataSource, RemindersCardStackViewDelegate;

__attribute__((visibility("hidden")))
@interface RemindersCardStackView : XXUnknownSuperclass <RemindersCardViewDelegate, UIGestureRecognizerDelegate> {
	RemindersCardController* _currentlyDisplayedCard;
	NSMutableArray* _cardPileViews;
	unsigned _displayedCardIndex;
	UIView* _pileContainer;
	int _presentationState;
	NSMutableDictionary* _cardControllersByID;
	RemindersCardController* _reorderdCard;
	unsigned _previousIndexOfReorderedCard;
	CGPoint _reorderedCardViewPositionInFrame;
	CGPoint _panningVelocity;
	NSTimer* _autoscrollTimer;
	BOOL _isReordering;
	BOOL _reorderPeekCompensated;
	BOOL _hasScrolledUp;
	BOOL _hasScrolledDown;
	NSMutableDictionary* _cardViewsInFlightByID;
	unsigned _userInteractionCounter;
	NSMutableDictionary* _animatorsByID;
	BOOL _gestureInteractionEnabled;
	id<RemindersCardStackViewDataSource> _datasource;
}
@property(assign, nonatomic) BOOL gestureInteractionEnabled;
@property(readonly, assign, nonatomic) BOOL isReordering;
@property(assign, nonatomic) unsigned displayedCardIndex;
@property(assign, nonatomic) int presentationState;
@property(assign, nonatomic) id<RemindersCardStackViewDataSource> datasource;
@property(assign, nonatomic) id<UIScrollViewDelegate, RemindersCardStackViewDelegate> delegate;
-(void).cxx_destruct;
-(void)cardView:(id)view panned:(CGPoint)panned withVelocity:(CGPoint)velocity;
-(BOOL)cardViewShouldAllowPanning:(id)cardView;
-(void)cardViewPanDidEnd:(id)cardViewPan;
-(void)cardViewPanDidBegin:(id)cardViewPan;
-(void)cardViewTapped:(id)tapped;
-(void)_removeDimmingFromPileWithAnimation:(BOOL)animation;
-(void)_addDimmingToPileWithAnimation:(BOOL)animation;
-(unsigned)_indexForPosition:(CGPoint)position;
-(float)_rubberBandYOffsetForIndex:(unsigned)index;
-(void)_setPresentedCardView:(id)view;
-(id)_cardViewAtIndex:(unsigned)index;
-(void)_enumerateLoadedCardViews:(id)views;
-(id)_sortedCardViewIndexes;
-(void)_removeMotionEffectsFromModalPile;
-(void)_addMotionEffectsToModalPile;
-(void)_reorderPositionChangedForCardView:(id)cardView velocity:(CGPoint)velocity;
-(void)_stopAutoscrollTimer;
-(void)_autoscrollForReordering:(id)reordering;
-(void)_autoscrollIfNecessary;
-(void)_animateCardView:(id)view toIndex:(unsigned)index reorderAfter:(double)after;
-(void)_transformCardView:(id)view toState:(int)state startTime:(float)time duration:(float)duration;
-(void)_transformCardView:(id)view toState:(int)state startTime:(float)time animated:(BOOL)animated;
-(void)_translateCardView:(id)view toState:(int)state startTime:(float)time animated:(BOOL)animated;
-(void)_positionCardViewForModalPresentation:(id)modalPresentation atIndex:(unsigned)index;
-(void)_animateCardViewToModalPresentation:(id)modalPresentation atIndex:(unsigned)index indexes:(id)indexes animationIndex:(unsigned*)index4;
-(void)_positionCardViewForStackPresentation:(id)stackPresentation atIndex:(unsigned)index;
-(void)_animateCardViewToStackPresentation:(id)stackPresentation atIndex:(unsigned)index indexes:(id)indexes animationIndex:(unsigned*)index4 fromGesture:(BOOL)gesture;
-(unsigned)_lastIndex;
-(CATransform3D)_transformForCardView:(id)cardView forState:(int)state;
-(CGPoint)_positionForCardView:(id)cardView atIndex:(unsigned)index forState:(int)state;
-(float)_scaleForCardView:(id)cardView forState:(int)state;
-(float)_xPositionForCardView:(id)cardView forState:(int)state;
-(unsigned)_indexOfCardView:(id)cardView;
-(float)_yForCardInPileAtIndex:(unsigned)index;
-(float)_yForModallyPresentedCard;
-(float)_nativeYOfCardAtBounds;
-(float)_yForCardInTableAtIndex:(unsigned)index;
-(float)_yPositionForCardAtIndex:(unsigned)index forState:(int)state;
-(void)_endCardPanWithGestureRecognizer:(id)gestureRecognizer;
-(void)_beginCardPanWithGestureRecognizer:(id)gestureRecognizer;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)_handleModalCardGesture:(id)gesture;
-(void)_cleanUpAnimatorForCardView:(id)cardView;
-(void)_addPanGestureRecognizerToCardView:(id)cardView;
-(id)_animatorForGestureRecognizer:(id)gestureRecognizer;
-(void)_presentStackViewWithAnimation:(BOOL)animation fromGesture:(BOOL)gesture;
-(void)_presentCardViewPostAnimationActions;
-(void)_presentCardView:(id)view animated:(BOOL)animated;
-(void)_cleanupPileContainerView;
-(void)_createCardPileContainerView;
-(void)_generateCardPileWithVisibleIndexes:(NSRange)visibleIndexes reservePlace:(BOOL)place;
-(NSRange)_rangeOfEagerLoadedIndexes;
-(id)_arrayOfStackedIndexes;
-(NSRange)_rangeOfVisibleIndexes;
-(NSRange)_rangeOfAllIndexes;
-(int)_startVisibleIndex;
-(float)_cardHeightMultiplier;
-(void)_removeCardAsSubviewWithID:(id)anId;
-(void)_addCardAsSubview:(id)subview forIndex:(unsigned)index;
-(void)_arrangeCards;
-(void)_loadPresentedCard;
-(void)_tileCardsForState:(int)state eager:(BOOL)eager;
-(id)_setupCardViewAtIndex:(unsigned)index forState:(int)state addedAsSubview:(BOOL*)subview;
-(CGSize)_contentSize;
-(void)setContentOffset:(CGPoint)offset;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)tileCardsEagerly:(BOOL)eagerly;
-(void)swapCard:(id)card forNewCard:(id)newCard atIndex:(unsigned)index;
-(void)deleteCard:(id)card atIndex:(unsigned)index;
-(void)insertCard:(id)card atIndex:(unsigned)index;
-(void)reloadData;
-(void)stageCardInPresentationState:(int)presentationState atIndex:(unsigned)index;
-(void)setPresentationState:(int)state animated:(BOOL)animated;
-(void)_positionPileContainerForPresentedCardWithAnimation:(BOOL)animation delay:(float)delay;
-(id)initWithFrame:(CGRect)frame;
@end
