/* RemindersCardVerticalPanAnimator.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "Reminders-Structs.h"

@class _UIDynamicValueAnimation, UIPanGestureRecognizer, UIView;

__attribute__((visibility("hidden")))
@interface RemindersCardVerticalPanAnimator : XXUnknownSuperclass {
	_UIDynamicValueAnimation* _panningAnimation;
	UIPanGestureRecognizer* _gestureRecognizer;
	UIView* _panningCardView;
	float _panningViewTargetScale;
	CGPoint _panningViewStartPosition;
	CGPoint _panningViewTargetPosition;
}
@property(assign, nonatomic) float panningViewTargetScale;
@property(assign, nonatomic) CGPoint panningViewTargetPosition;
@property(assign, nonatomic) CGPoint panningViewStartPosition;
@property(retain, nonatomic) UIView* panningCardView;
@property(retain, nonatomic) UIPanGestureRecognizer* gestureRecognizer;
-(void).cxx_destruct;
-(void)dismissWithStartVelocity:(float)startVelocity completion:(id)completion;
-(id)_dynamicAnimationWithStart:(float)start target:(float)target initialVelocity:(float)velocity;
-(void)layoutViewsWithY:(float)y;
-(void)stop;
-(id)initWithCardView:(id)cardView;
@end
