/* RemindersInlineEditSubviewController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class EKReminder;
@protocol RemindersInlineEditSubviewControllerDelegate;

__attribute__((visibility("hidden")))
@interface RemindersInlineEditSubviewController : XXUnknownSuperclass {
	EKReminder* _reminder;
	id<RemindersInlineEditSubviewControllerDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<RemindersInlineEditSubviewControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)commitFullScreen;
-(void)cancelFullScreen;
-(float)desiredHeight;
-(void)viewDidLoad;
-(void)clearValue;
-(BOOL)pushChangesIntoReminder;
-(void)updateFromReminder;
-(void)setReminder:(id)reminder;
-(id)initWithReminder:(id)reminder;
@end
