/* EKBBTodayProvider.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "EKBBDataProvider.h"
#import "BBDataProvider.h"

@class NSArray, NSTimer, NSObject, EKEventDescriptionGenerator;
@protocol OS_dispatch_queue;

@interface EKBBTodayProvider : EKBBDataProvider <BBDataProvider> {
	NSObject<OS_dispatch_queue>* _bulletinRefreshQueue;
	EKEventDescriptionGenerator* _descriptionGenerator;
	NSArray* _birthdayEvents;
	NSArray* _upcomingEvents;
	NSArray* _todayEvents;
	NSArray* _tomorrowEvents;
	NSTimer* _updateCountdownTimer;
	NSTimer* _startCountdownTimer;
	BOOL _isShowingBirthdayBulletin;
	BOOL _isShowingUpcomingEventBulletin;
	BOOL _isShowingTomorrowBulletin;
}
-(void).cxx_destruct;
-(void)_resetTimers;
-(void)_updateCountdownTimerDidFire:(id)_updateCountdownTimer;
-(void)_startCountdownTimerDidFire:(id)_startCountdownTimer;
-(void)_scheduleTimerForUpdatingCountdownToEvent:(id)event;
-(void)_scheduleTimerForStartingCountdownToEvent:(id)event;
-(void)_refreshTomorrowBulletin;
-(void)_refreshUpcomingEventBulletin;
-(void)_refreshBirthdayBulletin;
-(void)_selectedCalendarsChanged:(id)changed;
-(void)_significantTimeChange:(id)change;
-(void)_resetAllEvents;
-(void)_eventDescriptionWasInvalidated:(id)invalidated;
-(BOOL)_isEvent:(id)event equivalentToEvent:(id)event2;
-(BOOL)_doesListOfEvents:(id)events containEquivalentForEvent:(id)event;
-(BOOL)_isListOfEvents:(id)events equivalentToListOfEvents:(id)events2;
-(void)databaseChanged:(id)changed;
-(id)_dateForEndOfTomorrow;
-(id)_dateForBeginningOfTomorrow;
-(id)_tomorrowComponents;
-(id)_dateForEndOfToday;
-(id)_dateForBeginningOfToday;
-(id)_todayComponents;
-(BOOL)_isEventFirstForToday:(id)today;
-(BOOL)_isAllDayOrDeclinedEvent:(id)event;
-(id)_loadBirthdayEventsForToday;
-(id)_loadTodayEvents;
-(id)_loadTomorrowEvents;
-(id)_loadUpcomingEvents;
-(id)_todayEvents;
-(id)_tomorrowEvents;
-(id)_upcomingEvents;
-(id)_birthdayEventsForToday;
-(id)_selectedCalendars;
-(id)_expirationDateForTomorrowSnippet;
-(id)_createTomorrowBulletin;
-(id)_createUpcomingEventBulletin;
-(id)_createBirthdayBulletin;
-(id)bulletinsWithRequestParameters:(id)requestParameters lastCleared:(id)cleared;
-(id)defaultSectionInfo;
-(id)sortDescriptors;
-(id)sectionIdentifier;
-(BOOL)supportsAlerts;
-(void)dealloc;
-(id)init;
@end
