/* EKBBDataProvider.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BBDataProvider.h"

@class NSTimer, NSMutableDictionary, EKEventStore, NSObject;
@protocol OS_dispatch_source, OS_dispatch_queue;

@interface EKBBDataProvider : XXUnknownSuperclass <BBDataProvider> {
	NSObject<OS_dispatch_queue>* _alertQueue;
	NSObject<OS_dispatch_queue>* _databaseQueue;
	NSMutableDictionary* _alerts;
	NSTimer* _syncTimer;
	BOOL _pendingChanges;
	NSObject<OS_dispatch_queue>* _eventStoreQueue;
	EKEventStore* _eventStore;
	NSObject<OS_dispatch_source>* _eventStoreIdleTimerSource;
}
-(void).cxx_destruct;
-(id)expirationDateForAlertInfo:(id)alertInfo;
-(void)_syncDidEnd;
-(void)_syncDidStart;
-(void)_syncTimerFired:(id)fired;
-(void)_killSyncTimer;
-(void)_resetSyncTimer;
-(void)alarmsDidFire:(id)alarms;
-(void)_alarmsDidFire:(id)_alarms;
-(id)_bulletinRequestWithAlertInfo:(id)alertInfo;
-(void)_bulletinRequestAcknowledged:(id)acknowledged alertInfo:(id)info performActions:(id)actions;
-(void)bulletinClosed:(id)closed;
-(void)_addAlertModalContent:(id)content bulletin:(id)bulletin;
-(void)_withdrawAlertBulletin:(id)bulletin;
-(id)messageStringForAlert:(id)alert;
-(id)actionButtonTitleForAlertInfo:(id)alertInfo;
-(id)defaultURLForAlertInfo:(id)alertInfo;
-(id)emptyModalTitle;
-(id)modalMessageForAlertInfo:(id)alertInfo;
-(id)modalTitleForAlertInfo:(id)alertInfo;
-(id)entityScheme;
-(void)clearAlerts;
-(void)removeAlerts:(id)alerts;
-(void)acknowledgeAlerts:(id)alerts;
-(id)alerts;
-(void)databaseChanged:(id)changed;
-(void)_killEventStoreIdleTimer;
-(void)_resetEventStoreIdleTimer;
-(unsigned)allowedEntityTypes;
-(void)_timeZoneChanged:(id)changed;
-(id)eventStore;
-(void)_databaseChanged;
-(id)_findAlarmForCalendarItem:(id)calendarItem matchingExternalID:(id)anId;
-(BOOL)syncsBulletinDismissal;
-(id)sectionIdentifier;
-(id)sortDescriptors;
-(id)bulletinsFilteredBy:(unsigned)by count:(unsigned)count lastCleared:(id)cleared;
-(BOOL)supportsAlerts;
-(void)dataProviderDidLoad;
-(void)dealloc;
-(id)init;
@end
