/* DayCircleView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileCal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface DayCircleView : XXUnknownSuperclass {
	UIColor* _color;
}
@property(retain, nonatomic) UIColor* color;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
@end
