/* PadMonthWeekTransitionView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileCal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, PadWeekViewController, PadMonthViewController, NSArray, EKCalendarDate;

__attribute__((visibility("hidden")))
@interface PadMonthWeekTransitionView : XXUnknownSuperclass {
	NSArray* _monthStateNumbers;
	NSArray* _weekStateNumbers;
	NSArray* _weekdayLabels;
	UIView* _topMonthImage;
	UIView* _bottomMonthImage;
	UIView* _monthSelectedWeekEvents;
	UIView* _monthSelectedWeekHighlight;
	UIView* _weekCircleView;
	UIView* _monthCircleView;
	PadWeekViewController* _weekViewController;
	PadMonthViewController* _monthViewController;
	UIView* _topLine;
	EKCalendarDate* _selectedDate;
	CGRect _frameOfWeekInMonth;
	CGRect _frameOfEventsInMonth;
	CGPoint _weekViewOriginalPoint;
	int _labelSyncOffset;
@private
	float _bottomMonthImageInset;
@protected
	int _weekTodayIndex;
	int _monthTodayIndex;
	id _completion;
}
-(void).cxx_destruct;
-(id)_createSnapshotFromView:(id)view frame:(CGRect)frame;
-(id)_createImageViewFromImage:(id)image frame:(CGRect)frame;
-(id)_captureImageFromView:(id)view opaque:(BOOL)opaque;
-(id)_copyLabel:(id)label;
-(id)_fittedCenteredLabelFromLabel:(id)label;
-(id)_generateImageViewFromLabel:(id)label;
-(id)_copyLabels:(id)labels;
-(id)_generateImagesFromLabels:(id)labels usingSuperViewForConversion:(id)conversion;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)animationDidStart:(id)animation;
-(CGRect)_estimatedCircleFrameForMonthState;
-(CGRect)_estimatedCircleFrameForWeekState;
-(CGSize)_estimatedWeekToMonthScale;
-(id)_correspondingWeekViewForMonthIndex:(int)monthIndex;
-(id)_correspondingMonthViewForWeekIndex:(int)weekIndex;
-(void)_synchronizeLabelsWithWeekLabels:(id)weekLabels monthLabels:(id)labels;
-(void)_animateWithDuration:(double)duration delay:(double)delay animations:(id)animations;
-(void)_perform:(id)perform afterDelay:(double)delay;
-(void)_haltAllAnimations;
-(void)_animateLabelsToWeekState;
-(void)_animateWeekdayLabel:(id)label toMonthWithNumberStartFrame:(CGRect)numberStartFrame destinationFrame:(CGRect)frame;
-(void)_animateLabelsToMonthState;
-(void)_animateToWeekState;
-(void)_animateToMonthState;
-(void)_setToWeekStartState;
-(void)_setToMonthStartState;
-(void)_setUpWithMonthViewController:(id)monthViewController weekViewController:(id)controller selectedDate:(id)date calendar:(id)calendar;
-(double)animationDuration;
-(void)animateToWeekWithCompletion:(id)completion;
-(void)animateToMonthWithCompletion:(id)completion;
-(void)prepareWithSelectedDate:(id)selectedDate monthViewController:(id)controller weekViewController:(id)controller3 calendar:(id)calendar;
@end
