/* PadMonthWeekOccurrencesView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileCal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class EKEvent, NSMutableArray, EKCalendarDate;

__attribute__((visibility("hidden")))
@interface PadMonthWeekOccurrencesView : XXUnknownSuperclass {
	opaque_pthread_mutex_t _drawLock;
	int _frameCount;
	CGRect* _dayFrames;
	NSMutableArray* _layedOutRows;
	NSMutableArray* _singleDayEventBuckets;
	int _numberOfVisibleRows;
	BOOL _isZoomedDay;
	BOOL _hasDrawnBefore;
	EKCalendarDate* _startDate;
	EKCalendarDate* _endDate;
	int _dayCount;
	EKEvent* _selectedOccurrence;
}
@property(assign) BOOL hasDrawnBefore;
@property(assign, nonatomic) BOOL isZoomedDay;
@property(retain, nonatomic) EKEvent* selectedOccurrence;
@property(assign, nonatomic) int dayCount;
@property(retain, nonatomic) EKCalendarDate* endDate;
@property(retain, nonatomic) EKCalendarDate* startDate;
-(void).cxx_destruct;
-(void)willMoveToSuperview:(id)superview;
-(void)displayLayer:(id)layer;
-(void)setNeedsDisplay;
-(void)_updateOccurrencesBounds;
-(id)_occurrenceViewForEventOccurrence:(id)eventOccurrence;
-(BOOL)hasOccurrences;
-(void)setOccurrences:(id)occurrences;
-(NSRange)_dayRangeForOccurrence:(id)occurrence;
-(id)_dequeueNextOccurrenceforDay:(unsigned)day;
-(void)_layoutSingleOccurrence:(id)occurrence index:(unsigned)index;
-(void)drawIntoContext:(CGContextRef)context;
-(void)layoutSubviews;
-(void)_rebuildFrameStorage;
-(CGRect)_frameForStartColumn:(unsigned)startColumn endColumn:(unsigned)column dayRow:(unsigned)row occurrenceRow:(unsigned)row4 splitLeftEdge:(BOOL)edge splitRightEdge:(BOOL)edge6;
-(CGRect)_frameForStartColumn:(unsigned)startColumn endColumn:(unsigned)column dayRow:(unsigned)row occurrenceRow:(unsigned)row4;
-(id)occurrenceViewForOccurrence:(id)occurrence onDay:(id)day;
-(CGRect)frameForOccurrenceAfterLastOnDay:(id)occurrenceAfterLastOnDay;
-(CGRect)frameForLastOccurrenceOnDay:(id)lastOccurrenceOnDay;
-(CGRect)frameForOccurrence:(id)occurrence onDay:(id)day;
-(id)occurrenceAtPoint:(CGPoint)point;
-(void)setStartDate:(id)date endDate:(id)date2 dayCount:(int)count;
-(void)dealloc;
-(id)description;
-(id)initWithFrame:(CGRect)frame;
@end
