/* PadRootNavigationController.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "RootNavigationController.h"
#import "UIPopoverControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class UIPopoverController, UIBarButtonItem, UISearchBar, UIButton;

__attribute__((visibility("hidden")))
@interface PadRootNavigationController : RootNavigationController <UINavigationControllerDelegate, UIPopoverControllerDelegate> {
	UIPopoverController* _padPopoverController;
	UISearchBar* _searchBar;
	UIBarButtonItem* _searchContainerViewBarItem;
}
@property(retain, nonatomic) UIButton* searchButton;
@property(retain, nonatomic) UIBarButtonItem* searchContainerViewBarItem;
@property(retain, nonatomic) UISearchBar* searchBar;
@property(retain, nonatomic) UIPopoverController* padPopoverController;
+(id)_searchBarWithRedMagnifyingGlass;
+(id)_redMagnifyingGlass;
-(void).cxx_destruct;
-(id)showSearchAnimated:(BOOL)animated;
-(id)showInboxAnimated:(BOOL)animated;
-(void)showAddPopoverAnimated:(BOOL)animated;
-(void)inboxPressed;
-(void)calendarsPressed;
-(void)todayPressed;
-(void)addEventPressed;
-(void)searchPressed;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(id)_searchDoneBlock;
-(void)_collapseSearchBarAnimated:(BOOL)animated;
-(void)_expandSearchBarRevealingPopoverController:(id)controller animated:(BOOL)animated;
-(float)_animationDuration:(BOOL)duration;
-(void)addNavigationBarButtonItemsWithViewController:(id)viewController;
-(BOOL)_activePopoverIsSearch;
-(void)_closeActivePopover;
-(id)_doneBlock;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(BOOL)popoverControllerShouldDismissPopover:(id)popoverController;
-(id)_initializedPopoverControllerWithContentViewController:(id)contentViewController;
-(unsigned)supportedInterfaceOrientations;
-(id)initWithRootViewController:(id)rootViewController model:(id)model;
@end
