/* YearMonthTransitionMonthView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "MobileCal-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIColor, NSArray;

__attribute__((visibility("hidden")))
@interface YearMonthTransitionMonthView : XXUnknownSuperclass {
	BOOL _hasValidOrigin;
	float _topInset;
	NSArray* _weekViews;
}
@property(retain, nonatomic) NSArray* weekViews;
@property(readonly, assign, nonatomic) UIColor* monthLabelColor;
@property(readonly, assign, nonatomic) NSString* monthLabelText;
@property(readonly, assign, nonatomic) CGRect monthLabelFrame;
@property(readonly, assign, nonatomic) CGRect monthFrameInMonthView;
@property(readonly, assign, nonatomic) CGRect monthFrame;
@property(assign, nonatomic) BOOL hasValidOrigin;
@property(assign, nonatomic) float topInset;
-(void).cxx_destruct;
-(CGRect)_adjustFrame:(CGRect)frame;
@end
