/* PHHandsetDialerView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "PHAbstractDialerView.h"
#import "FaceTime-Structs.h"
#import "TPDialerKeypadDelegate.h"

@class UIView, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface PHHandsetDialerView : PHAbstractDialerView <TPDialerKeypadDelegate> {
	UIView* _leftBlankView;
	UIView* _rightBlankView;
	UIView* _bottomBlankView;
	UIView* _topBlankView;
	NSLayoutConstraint* _statusBarToLCDViewConstraint;
}
@property(retain) NSLayoutConstraint* statusBarToLCDViewConstraint;
@property(retain) UIView* topBlankView;
@property(retain) UIView* bottomBlankView;
@property(retain) UIView* rightBlankView;
@property(retain) UIView* leftBlankView;
-(id)layoutConstraintMetrics;
-(id)newCallButton;
-(id)newNumberPadView;
-(id)newLCDView;
-(id)dialerColor;
-(void)updateLCDContraintsForStatusBar;
-(void)setInCallMode:(BOOL)callMode;
-(void)createConstraints;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end
