/* PHRecentsPersonFaceTimeHeaderSummaryView.h Was Dumped By @greensnow_tweak on Sunday, 16 June 2013 at 02:49:00 PM AEST On IOS 7 Beta 1 Firmware. */
/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "FaceTime-Structs.h"
#import "PHRecentsPersonHeaderSummaryView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface PHRecentsPersonFaceTimeHeaderSummaryView : XXUnknownSuperclass <PHRecentsPersonHeaderSummaryView> {
	UILabel* _topmostLabel;
	UILabel* _bottommostLabel;
	float _intrinsicContentHeight;
}
@property(assign) float intrinsicContentHeight;
@property(assign) UILabel* bottommostLabel;
@property(assign) UILabel* topmostLabel;
-(CGSize)sizeThatFits:(CGSize)fits;
-(CGSize)intrinsicContentSize;
-(id)initWithFrame:(CGRect)frame recentCall:(id)call occurrenceDate:(id)date type:(int)type duration:(double)duration category:(int)category dataUsage:(double)usage;
@end
